/* 
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */
package com.egain.sdk;

import static com.egain.sdk.operations.Operations.AsyncRequestOperation;

import com.egain.sdk.models.operations.GetpopulararticlesRequest;
import com.egain.sdk.models.operations.async.GetpopulararticlesRequestBuilder;
import com.egain.sdk.models.operations.async.GetpopulararticlesResponse;
import com.egain.sdk.operations.Getpopulararticles;
import com.egain.sdk.utils.Headers;
import jakarta.annotation.Nonnull;
import java.util.concurrent.CompletableFuture;


public class AsyncPopulararticles {
    private static final Headers _headers = Headers.EMPTY;
    private final SDKConfiguration sdkConfiguration;
    private final Populararticles syncSDK;

    AsyncPopulararticles(Populararticles syncSDK, SDKConfiguration sdkConfiguration) {
        this.sdkConfiguration = sdkConfiguration;
        this.syncSDK = syncSDK;
    }

    /**
     * Switches to the sync SDK.
     * 
     * @return The sync SDK
     */
    public Populararticles sync() {
        return syncSDK;
    }


    /**
     * Get Popular Articles
     * 
     * <p>## Overview
     * The Popular Articles API allows a user to retrieve popular articles.
     * ## Prerequisites
     * * Only displayable articles are returned. An Article is displayable when "Include in browse on
     * portals" property is enable for the Article.
     * ## Permissions
     * * Agent permissions: The following permissions are required if user is an Agent:
     * * If Article has Access Tags, Article must be available for agent's current user profile.
     * * If Article has Publish Views, at least one edition of Article must be available for agent's
     * current user profile.
     * * If Article has filters and tags query parameter provided, Article filters must match provided tags
     * or tag groups.
     * * Customer permissions: The following permissions are required if user is a Customer:
     * * If Article has Access tags:
     * * Portal must have default user profile, and;
     * * Article must be available for portal's default user profile.
     * * If Article has Publish Views:
     * * Portal must have default user profile, and;
     * * At least one edition must be available for portal's default user profile.
     * *  If Article has filters and tags query parameter provided, Article filters must match provided
     * tags or tag groups.
     * 
     * @return The async call builder
     */
    public GetpopulararticlesRequestBuilder getpopulararticles() {
        return new GetpopulararticlesRequestBuilder(sdkConfiguration);
    }

    /**
     * Get Popular Articles
     * 
     * <p>## Overview
     * The Popular Articles API allows a user to retrieve popular articles.
     * ## Prerequisites
     * * Only displayable articles are returned. An Article is displayable when "Include in browse on
     * portals" property is enable for the Article.
     * ## Permissions
     * * Agent permissions: The following permissions are required if user is an Agent:
     * * If Article has Access Tags, Article must be available for agent's current user profile.
     * * If Article has Publish Views, at least one edition of Article must be available for agent's
     * current user profile.
     * * If Article has filters and tags query parameter provided, Article filters must match provided tags
     * or tag groups.
     * * Customer permissions: The following permissions are required if user is a Customer:
     * * If Article has Access tags:
     * * Portal must have default user profile, and;
     * * Article must be available for portal's default user profile.
     * * If Article has Publish Views:
     * * Portal must have default user profile, and;
     * * At least one edition must be available for portal's default user profile.
     * *  If Article has filters and tags query parameter provided, Article filters must match provided
     * tags or tag groups.
     * 
     * @param request The request object containing all the parameters for the API call.
     * @return {@code CompletableFuture<GetpopulararticlesResponse>} - The async response
     */
    public CompletableFuture<GetpopulararticlesResponse> getpopulararticles(@Nonnull GetpopulararticlesRequest request) {
        AsyncRequestOperation<GetpopulararticlesRequest, GetpopulararticlesResponse> operation
              = new Getpopulararticles.Async(sdkConfiguration, _headers);
        return operation.doRequest(request)
            .thenCompose(operation::handleResponse);
    }

}
