/* 
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */
package com.egain.sdk;

import static com.egain.sdk.operations.Operations.AsyncRequestOperation;

import com.egain.sdk.models.components.AcceptLanguage;
import com.egain.sdk.models.components.LanguageQueryParameter;
import com.egain.sdk.models.operations.GetAllArticleListsRequest;
import com.egain.sdk.models.operations.GetArticleListDetailsRequest;
import com.egain.sdk.models.operations.async.GetAllArticleListsRequestBuilder;
import com.egain.sdk.models.operations.async.GetAllArticleListsResponse;
import com.egain.sdk.models.operations.async.GetArticleListDetailsRequestBuilder;
import com.egain.sdk.models.operations.async.GetArticleListDetailsResponse;
import com.egain.sdk.operations.GetAllArticleLists;
import com.egain.sdk.operations.GetArticleListDetails;
import com.egain.sdk.utils.Headers;
import jakarta.annotation.Nonnull;
import jakarta.annotation.Nullable;
import java.lang.String;
import java.util.concurrent.CompletableFuture;


public class AsyncArticlelists {
    private static final Headers _headers = Headers.EMPTY;
    private final SDKConfiguration sdkConfiguration;
    private final Articlelists syncSDK;

    AsyncArticlelists(Articlelists syncSDK, SDKConfiguration sdkConfiguration) {
        this.sdkConfiguration = sdkConfiguration;
        this.syncSDK = syncSDK;
    }

    /**
     * Switches to the sync SDK.
     * 
     * @return The sync SDK
     */
    public Articlelists sync() {
        return syncSDK;
    }


    /**
     * Get All Article Lists
     * 
     * <p>## Overview
     * The Get All Article Lists API returns all quick Article lists that are configured for a portal.
     * 
     * @return The async call builder
     */
    public GetAllArticleListsRequestBuilder getAllArticleLists() {
        return new GetAllArticleListsRequestBuilder(sdkConfiguration);
    }

    /**
     * Get All Article Lists
     * 
     * <p>## Overview
     * The Get All Article Lists API returns all quick Article lists that are configured for a portal.
     * 
     * @param acceptLanguage 
     * @param portalID The ID of the portal being accessed.<br><br>A portal ID is composed of a 2-4 letter prefix, followed by a dash and 4-15 digits.
     * @return {@code CompletableFuture<GetAllArticleListsResponse>} - The async response
     */
    public CompletableFuture<GetAllArticleListsResponse> getAllArticleLists(@Nonnull AcceptLanguage acceptLanguage, @Nonnull String portalID) {
        return getAllArticleLists(acceptLanguage, portalID, null);
    }

    /**
     * Get All Article Lists
     * 
     * <p>## Overview
     * The Get All Article Lists API returns all quick Article lists that are configured for a portal.
     * 
     * @param acceptLanguage 
     * @param portalID The ID of the portal being accessed.<br><br>A portal ID is composed of a 2-4 letter prefix, followed by a dash and 4-15 digits.
     * @param language 
     * @return {@code CompletableFuture<GetAllArticleListsResponse>} - The async response
     */
    public CompletableFuture<GetAllArticleListsResponse> getAllArticleLists(
            @Nonnull AcceptLanguage acceptLanguage, @Nonnull String portalID,
            @Nullable LanguageQueryParameter language) {
        GetAllArticleListsRequest request = new GetAllArticleListsRequest(acceptLanguage, portalID, language);
        AsyncRequestOperation<GetAllArticleListsRequest, GetAllArticleListsResponse> operation
              = new GetAllArticleLists.Async(sdkConfiguration, _headers);
        return operation.doRequest(request)
            .thenCompose(operation::handleResponse);
    }


    /**
     * Get Article List by ID
     * 
     * <p>## Overview
     * The Get Article Lists by ID API returns the details of a quick access Article list that is
     * configured for a portal.
     * 
     * <p>Only those articles in the quick access list articles are returned and are:
     * 
     * <p>- Available for current user profile.
     * - Tagged with at least one of the provided tags, if tags query parameter is provided.
     * - Displayable. An Article is displayable if "Include in browse on portals" property is enable for
     * the Article.
     * 
     * @return The async call builder
     */
    public GetArticleListDetailsRequestBuilder getArticleListDetails() {
        return new GetArticleListDetailsRequestBuilder(sdkConfiguration);
    }

    /**
     * Get Article List by ID
     * 
     * <p>## Overview
     * The Get Article Lists by ID API returns the details of a quick access Article list that is
     * configured for a portal.
     * 
     * <p>Only those articles in the quick access list articles are returned and are:
     * 
     * <p>- Available for current user profile.
     * - Tagged with at least one of the provided tags, if tags query parameter is provided.
     * - Displayable. An Article is displayable if "Include in browse on portals" property is enable for
     * the Article.
     * 
     * @param request The request object containing all the parameters for the API call.
     * @return {@code CompletableFuture<GetArticleListDetailsResponse>} - The async response
     */
    public CompletableFuture<GetArticleListDetailsResponse> getArticleListDetails(@Nonnull GetArticleListDetailsRequest request) {
        AsyncRequestOperation<GetArticleListDetailsRequest, GetArticleListDetailsResponse> operation
              = new GetArticleListDetails.Async(sdkConfiguration, _headers);
        return operation.doRequest(request)
            .thenCompose(operation::handleResponse);
    }

}
