/* 
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */
package com.egain.sdk;

import static com.egain.sdk.operations.Operations.AsyncRequestOperation;

import com.egain.sdk.models.components.AcceptLanguage;
import com.egain.sdk.models.components.ArticleResultAdditionalAttributes;
import com.egain.sdk.models.components.AttachmentAdditionalAttributes;
import com.egain.sdk.models.components.CreateSuggestion;
import com.egain.sdk.models.components.ModifySuggestion;
import com.egain.sdk.models.operations.DeleteSuggestionRequest;
import com.egain.sdk.models.operations.GetRelatedArticlesForSuggestionRequest;
import com.egain.sdk.models.operations.GetSuggestionAttachmentByIdRequest;
import com.egain.sdk.models.operations.GetSuggestionAttachmentsRequest;
import com.egain.sdk.models.operations.GetSuggestionCommentsRequest;
import com.egain.sdk.models.operations.GetSuggestionRequest;
import com.egain.sdk.models.operations.MakeSuggestionRequest;
import com.egain.sdk.models.operations.ModifySuggestionsRequest;
import com.egain.sdk.models.operations.SearchSuggestionRequest;
import com.egain.sdk.models.operations.async.DeleteSuggestionRequestBuilder;
import com.egain.sdk.models.operations.async.DeleteSuggestionResponse;
import com.egain.sdk.models.operations.async.GetRelatedArticlesForSuggestionRequestBuilder;
import com.egain.sdk.models.operations.async.GetRelatedArticlesForSuggestionResponse;
import com.egain.sdk.models.operations.async.GetSuggestionAttachmentByIdRequestBuilder;
import com.egain.sdk.models.operations.async.GetSuggestionAttachmentByIdResponse;
import com.egain.sdk.models.operations.async.GetSuggestionAttachmentsRequestBuilder;
import com.egain.sdk.models.operations.async.GetSuggestionAttachmentsResponse;
import com.egain.sdk.models.operations.async.GetSuggestionCommentsRequestBuilder;
import com.egain.sdk.models.operations.async.GetSuggestionCommentsResponse;
import com.egain.sdk.models.operations.async.GetSuggestionRequestBuilder;
import com.egain.sdk.models.operations.async.GetSuggestionResponse;
import com.egain.sdk.models.operations.async.MakeSuggestionRequestBuilder;
import com.egain.sdk.models.operations.async.MakeSuggestionResponse;
import com.egain.sdk.models.operations.async.ModifySuggestionsRequestBuilder;
import com.egain.sdk.models.operations.async.ModifySuggestionsResponse;
import com.egain.sdk.models.operations.async.SearchSuggestionRequestBuilder;
import com.egain.sdk.models.operations.async.SearchSuggestionResponse;
import com.egain.sdk.operations.DeleteSuggestion;
import com.egain.sdk.operations.GetRelatedArticlesForSuggestion;
import com.egain.sdk.operations.GetSuggestion;
import com.egain.sdk.operations.GetSuggestionAttachmentById;
import com.egain.sdk.operations.GetSuggestionAttachments;
import com.egain.sdk.operations.GetSuggestionComments;
import com.egain.sdk.operations.MakeSuggestion;
import com.egain.sdk.operations.ModifySuggestions;
import com.egain.sdk.operations.SearchSuggestion;
import com.egain.sdk.utils.Headers;
import jakarta.annotation.Nonnull;
import jakarta.annotation.Nullable;
import java.lang.String;
import java.util.List;
import java.util.concurrent.CompletableFuture;


public class AsyncSuggestion {
    private static final Headers _headers = Headers.EMPTY;
    private final SDKConfiguration sdkConfiguration;
    private final Suggestion syncSDK;

    AsyncSuggestion(Suggestion syncSDK, SDKConfiguration sdkConfiguration) {
        this.sdkConfiguration = sdkConfiguration;
        this.syncSDK = syncSDK;
    }

    /**
     * Switches to the sync SDK.
     * 
     * @return The sync SDK
     */
    public Suggestion sync() {
        return syncSDK;
    }


    /**
     * Make a Suggestion
     * 
     * <p>## Overview
     * The Make a Suggestion API allows users to create an Article Suggestion from within a knowledge
     * portal.
     * 
     * <p>## Prerequisites
     * * Enable the setting "Manage a Suggestion" for the portal specified in the URL.
     * * If the user is a Customer, enable the setting "Allow Customer Access" for the portal.
     * * If you want to add an attachment to a Suggestion, first call the Generate Signed URL to Upload API
     * to add an attachment using the provided returned altID in attachment request.
     * 
     * @return The async call builder
     */
    public MakeSuggestionRequestBuilder makeSuggestion() {
        return new MakeSuggestionRequestBuilder(sdkConfiguration);
    }

    /**
     * Make a Suggestion
     * 
     * <p>## Overview
     * The Make a Suggestion API allows users to create an Article Suggestion from within a knowledge
     * portal.
     * 
     * <p>## Prerequisites
     * * Enable the setting "Manage a Suggestion" for the portal specified in the URL.
     * * If the user is a Customer, enable the setting "Allow Customer Access" for the portal.
     * * If you want to add an attachment to a Suggestion, first call the Generate Signed URL to Upload API
     * to add an attachment using the provided returned altID in attachment request.
     * 
     * @param acceptLanguage 
     * @param portalID The ID of the portal being accessed.<br><br>A portal ID is composed of a 2-4 letter prefix, followed by a dash and 4-15 digits.
     * @return {@code CompletableFuture<MakeSuggestionResponse>} - The async response
     */
    public CompletableFuture<MakeSuggestionResponse> makeSuggestion(@Nonnull AcceptLanguage acceptLanguage, @Nonnull String portalID) {
        return makeSuggestion(acceptLanguage, portalID, null);
    }

    /**
     * Make a Suggestion
     * 
     * <p>## Overview
     * The Make a Suggestion API allows users to create an Article Suggestion from within a knowledge
     * portal.
     * 
     * <p>## Prerequisites
     * * Enable the setting "Manage a Suggestion" for the portal specified in the URL.
     * * If the user is a Customer, enable the setting "Allow Customer Access" for the portal.
     * * If you want to add an attachment to a Suggestion, first call the Generate Signed URL to Upload API
     * to add an attachment using the provided returned altID in attachment request.
     * 
     * @param acceptLanguage 
     * @param portalID The ID of the portal being accessed.<br><br>A portal ID is composed of a 2-4 letter prefix, followed by a dash and 4-15 digits.
     * @param body This schema contains information about a Suggestion.
     * @return {@code CompletableFuture<MakeSuggestionResponse>} - The async response
     */
    public CompletableFuture<MakeSuggestionResponse> makeSuggestion(
            @Nonnull AcceptLanguage acceptLanguage, @Nonnull String portalID,
            @Nullable CreateSuggestion body) {
        MakeSuggestionRequest request = new MakeSuggestionRequest(acceptLanguage, portalID, body);
        AsyncRequestOperation<MakeSuggestionRequest, MakeSuggestionResponse> operation
              = new MakeSuggestion.Async(sdkConfiguration, _headers);
        return operation.doRequest(request)
            .thenCompose(operation::handleResponse);
    }


    /**
     * Modify Suggestion
     * 
     * <p>## Overview
     * The Modify Suggestion API allows authenticated users to modify their own Suggestion.
     * 
     * <p>## Prerequisites
     * * Enable the setting "Manage a Suggestion" for the portal specified in the URL.
     * * If the user is a Customer, enable the setting "Allow Customer Access" for the portal.
     * * The "Suggestion ID" specified in the request body must exist and belong to the user.
     * * The status of this Suggestion as returned by the Get Suggestion by ID API must be "pending".
     * * At least one of the optional request body attributes must be provided.
     * 
     * @return The async call builder
     */
    public ModifySuggestionsRequestBuilder modifySuggestions() {
        return new ModifySuggestionsRequestBuilder(sdkConfiguration);
    }

    /**
     * Modify Suggestion
     * 
     * <p>## Overview
     * The Modify Suggestion API allows authenticated users to modify their own Suggestion.
     * 
     * <p>## Prerequisites
     * * Enable the setting "Manage a Suggestion" for the portal specified in the URL.
     * * If the user is a Customer, enable the setting "Allow Customer Access" for the portal.
     * * The "Suggestion ID" specified in the request body must exist and belong to the user.
     * * The status of this Suggestion as returned by the Get Suggestion by ID API must be "pending".
     * * At least one of the optional request body attributes must be provided.
     * 
     * @param acceptLanguage 
     * @param portalID The ID of the portal being accessed.<br><br>A portal ID is composed of a 2-4 letter prefix, followed by a dash and 4-15 digits.
     * @return {@code CompletableFuture<ModifySuggestionsResponse>} - The async response
     */
    public CompletableFuture<ModifySuggestionsResponse> modifySuggestions(@Nonnull AcceptLanguage acceptLanguage, @Nonnull String portalID) {
        return modifySuggestions(acceptLanguage, portalID, null);
    }

    /**
     * Modify Suggestion
     * 
     * <p>## Overview
     * The Modify Suggestion API allows authenticated users to modify their own Suggestion.
     * 
     * <p>## Prerequisites
     * * Enable the setting "Manage a Suggestion" for the portal specified in the URL.
     * * If the user is a Customer, enable the setting "Allow Customer Access" for the portal.
     * * The "Suggestion ID" specified in the request body must exist and belong to the user.
     * * The status of this Suggestion as returned by the Get Suggestion by ID API must be "pending".
     * * At least one of the optional request body attributes must be provided.
     * 
     * @param acceptLanguage 
     * @param portalID The ID of the portal being accessed.<br><br>A portal ID is composed of a 2-4 letter prefix, followed by a dash and 4-15 digits.
     * @param body This schema contains information about modifying a Suggestion.
     * @return {@code CompletableFuture<ModifySuggestionsResponse>} - The async response
     */
    public CompletableFuture<ModifySuggestionsResponse> modifySuggestions(
            @Nonnull AcceptLanguage acceptLanguage, @Nonnull String portalID,
            @Nullable ModifySuggestion body) {
        ModifySuggestionsRequest request = new ModifySuggestionsRequest(acceptLanguage, portalID, body);
        AsyncRequestOperation<ModifySuggestionsRequest, ModifySuggestionsResponse> operation
              = new ModifySuggestions.Async(sdkConfiguration, _headers);
        return operation.doRequest(request)
            .thenCompose(operation::handleResponse);
    }


    /**
     * Get Suggestion by Status
     * 
     * <p>## Overview
     * The Get Suggestion by Status API allows authenticated users to retrieve their own suggestions based
     * on Suggestion status.
     * 
     * <p>## Prerequisites
     * * Enable the setting "My Suggestions" for the portal specified in the URL.
     * * If the user is a customer, enable the setting "Allow Customer Access" for the portal.
     * 
     * @return The async call builder
     */
    public SearchSuggestionRequestBuilder searchSuggestion() {
        return new SearchSuggestionRequestBuilder(sdkConfiguration);
    }

    /**
     * Get Suggestion by Status
     * 
     * <p>## Overview
     * The Get Suggestion by Status API allows authenticated users to retrieve their own suggestions based
     * on Suggestion status.
     * 
     * <p>## Prerequisites
     * * Enable the setting "My Suggestions" for the portal specified in the URL.
     * * If the user is a customer, enable the setting "Allow Customer Access" for the portal.
     * 
     * @param request The request object containing all the parameters for the API call.
     * @return {@code CompletableFuture<SearchSuggestionResponse>} - The async response
     */
    public CompletableFuture<SearchSuggestionResponse> searchSuggestion(@Nonnull SearchSuggestionRequest request) {
        AsyncRequestOperation<SearchSuggestionRequest, SearchSuggestionResponse> operation
              = new SearchSuggestion.Async(sdkConfiguration, _headers);
        return operation.doRequest(request)
            .thenCompose(operation::handleResponse);
    }


    /**
     * Get Suggestion by ID
     * 
     * <p>## Overview
     * The Get Suggestion by ID API allows authenticated users to retrieve their own suggestions.
     * 
     * <p>## Prerequisites
     * * Enable the setting "My Suggestions" for the portal specified in the URL.
     * * If the user is a customer, enable the setting "Allow Customer Access" for the portal.
     * * The "Suggestion for the ID" specified in the URL must belong to the user.
     * 
     * @return The async call builder
     */
    public GetSuggestionRequestBuilder getSuggestion() {
        return new GetSuggestionRequestBuilder(sdkConfiguration);
    }

    /**
     * Get Suggestion by ID
     * 
     * <p>## Overview
     * The Get Suggestion by ID API allows authenticated users to retrieve their own suggestions.
     * 
     * <p>## Prerequisites
     * * Enable the setting "My Suggestions" for the portal specified in the URL.
     * * If the user is a customer, enable the setting "Allow Customer Access" for the portal.
     * * The "Suggestion for the ID" specified in the URL must belong to the user.
     * 
     * @param request The request object containing all the parameters for the API call.
     * @return {@code CompletableFuture<GetSuggestionResponse>} - The async response
     */
    public CompletableFuture<GetSuggestionResponse> getSuggestion(@Nonnull GetSuggestionRequest request) {
        AsyncRequestOperation<GetSuggestionRequest, GetSuggestionResponse> operation
              = new GetSuggestion.Async(sdkConfiguration, _headers);
        return operation.doRequest(request)
            .thenCompose(operation::handleResponse);
    }


    /**
     * Delete a Suggestion
     * 
     * <p>## Overview
     * The Delete a Suggestion API allows authenticated users to delete their own Suggestion.
     * 
     * <p>## Prerequisites
     * * Enable the setting "Manage a Suggestion" for the portal specified in the URL.
     * * If the user is a customer, enable the setting "Allow Customer Access" for the portal.
     * * The Suggestion must belong to the user.
     * * The status of the Suggestion must not be "approved".
     * 
     * @return The async call builder
     */
    public DeleteSuggestionRequestBuilder deleteSuggestion() {
        return new DeleteSuggestionRequestBuilder(sdkConfiguration);
    }

    /**
     * Delete a Suggestion
     * 
     * <p>## Overview
     * The Delete a Suggestion API allows authenticated users to delete their own Suggestion.
     * 
     * <p>## Prerequisites
     * * Enable the setting "Manage a Suggestion" for the portal specified in the URL.
     * * If the user is a customer, enable the setting "Allow Customer Access" for the portal.
     * * The Suggestion must belong to the user.
     * * The status of the Suggestion must not be "approved".
     * 
     * @param acceptLanguage 
     * @param portalID The ID of the portal being accessed.<br><br>A portal ID is composed of a 2-4 letter prefix, followed by a dash and 4-15 digits.
     * @param suggestionID The ID of the Suggestion.<br><br>A Suggestion ID is composed of a 2-4 letter prefix, followed by a dash and 4-15 digits.
     * @return {@code CompletableFuture<DeleteSuggestionResponse>} - The async response
     */
    public CompletableFuture<DeleteSuggestionResponse> deleteSuggestion(
            @Nonnull AcceptLanguage acceptLanguage, @Nonnull String portalID,
            @Nonnull String suggestionID) {
        DeleteSuggestionRequest request = new DeleteSuggestionRequest(acceptLanguage, portalID, suggestionID);
        AsyncRequestOperation<DeleteSuggestionRequest, DeleteSuggestionResponse> operation
              = new DeleteSuggestion.Async(sdkConfiguration, _headers);
        return operation.doRequest(request)
            .thenCompose(operation::handleResponse);
    }


    /**
     * Get Related Articles for Suggestion
     * 
     * <p>## Overview
     * The Get Related Articles for Suggestion API allows authenticated users to retrieve related articles
     * for a Suggestion.
     * 
     * <p>## Prerequisites
     * * Enable the setting "My Suggestions" for the portal specified in the URL.
     * * If the user is a customer, enable the setting "Allow Customer Access" for the portal.
     * * The Suggestion specified in the URL must belong to the user.
     * 
     * @return The async call builder
     */
    public GetRelatedArticlesForSuggestionRequestBuilder getRelatedArticlesForSuggestion() {
        return new GetRelatedArticlesForSuggestionRequestBuilder(sdkConfiguration);
    }

    /**
     * Get Related Articles for Suggestion
     * 
     * <p>## Overview
     * The Get Related Articles for Suggestion API allows authenticated users to retrieve related articles
     * for a Suggestion.
     * 
     * <p>## Prerequisites
     * * Enable the setting "My Suggestions" for the portal specified in the URL.
     * * If the user is a customer, enable the setting "Allow Customer Access" for the portal.
     * * The Suggestion specified in the URL must belong to the user.
     * 
     * @param acceptLanguage 
     * @param portalID The ID of the portal being accessed.<br><br>A portal ID is composed of a 2-4 letter prefix, followed by a dash and 4-15 digits.
     * @param suggestionID The ID of the Suggestion.<br><br>A Suggestion ID is composed of a 2-4 letter prefix, followed by a dash and 4-15 digits.
     * @return {@code CompletableFuture<GetRelatedArticlesForSuggestionResponse>} - The async response
     */
    public CompletableFuture<GetRelatedArticlesForSuggestionResponse> getRelatedArticlesForSuggestion(
            @Nonnull AcceptLanguage acceptLanguage, @Nonnull String portalID,
            @Nonnull String suggestionID) {
        return getRelatedArticlesForSuggestion(
                acceptLanguage, null, portalID,
                suggestionID);
    }

    /**
     * Get Related Articles for Suggestion
     * 
     * <p>## Overview
     * The Get Related Articles for Suggestion API allows authenticated users to retrieve related articles
     * for a Suggestion.
     * 
     * <p>## Prerequisites
     * * Enable the setting "My Suggestions" for the portal specified in the URL.
     * * If the user is a customer, enable the setting "Allow Customer Access" for the portal.
     * * The Suggestion specified in the URL must belong to the user.
     * 
     * @param acceptLanguage 
     * @param articleResultAdditionalAttributes The attributes of an Article to be returned *in addition to* the default list of attributes, listed below. Multiple additional attributes can be specified using a comma-separated list. Passing 'all' will return all attributes.
     *         
     *         #### Default Attributes
     *         These Article attributes are always returned:
     *         
     *         | Name | Description 
     *         | ---- | -----------
     *         | id | The ID of the Article.
     *         | name  | The name of the Article.
     *         | articleType | The Article Type and its attributes.
     *         | createdBy | The ID, first name, middle name and last name of the user that created the Article.
     *         | createdDate | The date that the Article was created.
     *         | hasAttachments | True: The Article has one or more attachments.<br>False: The Article does not have any attachments.
     *         | languageCode | The language code of the Article language. 
     *         | modifiedBy | The ID, first name, middle name and last name of the user that last modified the Article.
     *         | modifiedDate | The date that the Article was last modified on.
     *         | link | The link object, used to retrieve the details of the Article.
     *         | versionId | The ID of the Article version that is returned.
     *         
     * @param portalID The ID of the portal being accessed.<br><br>A portal ID is composed of a 2-4 letter prefix, followed by a dash and 4-15 digits.
     * @param suggestionID The ID of the Suggestion.<br><br>A Suggestion ID is composed of a 2-4 letter prefix, followed by a dash and 4-15 digits.
     * @return {@code CompletableFuture<GetRelatedArticlesForSuggestionResponse>} - The async response
     */
    public CompletableFuture<GetRelatedArticlesForSuggestionResponse> getRelatedArticlesForSuggestion(
            @Nonnull AcceptLanguage acceptLanguage, @Nullable List<ArticleResultAdditionalAttributes> articleResultAdditionalAttributes,
            @Nonnull String portalID, @Nonnull String suggestionID) {
        GetRelatedArticlesForSuggestionRequest request = new GetRelatedArticlesForSuggestionRequest(
                acceptLanguage, articleResultAdditionalAttributes, portalID,
                suggestionID);
        AsyncRequestOperation<GetRelatedArticlesForSuggestionRequest, GetRelatedArticlesForSuggestionResponse> operation
              = new GetRelatedArticlesForSuggestion.Async(sdkConfiguration, _headers);
        return operation.doRequest(request)
            .thenCompose(operation::handleResponse);
    }


    /**
     * Get Suggestion Comments
     * 
     * <p>## Overview
     * The Get Suggestion Comments API allows authenticated users to retrieve all comments for a
     * Suggestion.
     * 
     * <p>## Prerequisites
     * * Enable the setting "My Suggestions" for the portal specified in the URL.
     * * If the user is a customer, enable the setting "Allow Customer Access" for the portal.
     * * The Suggestion specified in the URL must belong to the user.
     * 
     * @return The async call builder
     */
    public GetSuggestionCommentsRequestBuilder getSuggestionComments() {
        return new GetSuggestionCommentsRequestBuilder(sdkConfiguration);
    }

    /**
     * Get Suggestion Comments
     * 
     * <p>## Overview
     * The Get Suggestion Comments API allows authenticated users to retrieve all comments for a
     * Suggestion.
     * 
     * <p>## Prerequisites
     * * Enable the setting "My Suggestions" for the portal specified in the URL.
     * * If the user is a customer, enable the setting "Allow Customer Access" for the portal.
     * * The Suggestion specified in the URL must belong to the user.
     * 
     * @param acceptLanguage 
     * @param portalID The ID of the portal being accessed.<br><br>A portal ID is composed of a 2-4 letter prefix, followed by a dash and 4-15 digits.
     * @param suggestionID The ID of the Suggestion.<br><br>A Suggestion ID is composed of a 2-4 letter prefix, followed by a dash and 4-15 digits.
     * @return {@code CompletableFuture<GetSuggestionCommentsResponse>} - The async response
     */
    public CompletableFuture<GetSuggestionCommentsResponse> getSuggestionComments(
            @Nonnull AcceptLanguage acceptLanguage, @Nonnull String portalID,
            @Nonnull String suggestionID) {
        GetSuggestionCommentsRequest request = new GetSuggestionCommentsRequest(acceptLanguage, portalID, suggestionID);
        AsyncRequestOperation<GetSuggestionCommentsRequest, GetSuggestionCommentsResponse> operation
              = new GetSuggestionComments.Async(sdkConfiguration, _headers);
        return operation.doRequest(request)
            .thenCompose(operation::handleResponse);
    }


    /**
     * Get Suggestion Attachments
     * 
     * <p>## Overview
     * The Get Suggestion Attachments API allows authenticated users to retrieve attachments for a
     * Suggestion.
     * 
     * <p>## Prerequisites
     * * Enable the setting "My Suggestions" for the portal specified in the URL
     * * If the user is a customer, enable the setting "Allow Customer Access" for the portal.
     * * The Suggestion specified in the URL must belong to the user.
     * 
     * @return The async call builder
     */
    public GetSuggestionAttachmentsRequestBuilder getSuggestionAttachments() {
        return new GetSuggestionAttachmentsRequestBuilder(sdkConfiguration);
    }

    /**
     * Get Suggestion Attachments
     * 
     * <p>## Overview
     * The Get Suggestion Attachments API allows authenticated users to retrieve attachments for a
     * Suggestion.
     * 
     * <p>## Prerequisites
     * * Enable the setting "My Suggestions" for the portal specified in the URL
     * * If the user is a customer, enable the setting "Allow Customer Access" for the portal.
     * * The Suggestion specified in the URL must belong to the user.
     * 
     * @param acceptLanguage 
     * @param portalID The ID of the portal being accessed.<br><br>A portal ID is composed of a 2-4 letter prefix, followed by a dash and 4-15 digits.
     * @param suggestionID The ID of the Suggestion.<br><br>A Suggestion ID is composed of a 2-4 letter prefix, followed by a dash and 4-15 digits.
     * @return {@code CompletableFuture<GetSuggestionAttachmentsResponse>} - The async response
     */
    public CompletableFuture<GetSuggestionAttachmentsResponse> getSuggestionAttachments(
            @Nonnull AcceptLanguage acceptLanguage, @Nonnull String portalID,
            @Nonnull String suggestionID) {
        GetSuggestionAttachmentsRequest request = new GetSuggestionAttachmentsRequest(acceptLanguage, portalID, suggestionID);
        AsyncRequestOperation<GetSuggestionAttachmentsRequest, GetSuggestionAttachmentsResponse> operation
              = new GetSuggestionAttachments.Async(sdkConfiguration, _headers);
        return operation.doRequest(request)
            .thenCompose(operation::handleResponse);
    }


    /**
     * Get Suggestion Attachment by ID
     * 
     * <p>## Overview
     * The Get Suggestion Attachment by ID API allows authenticated users to get the details of an
     * attachment that belongs to their own Suggestion. It also allows the download of attachment content.
     * 
     * <p>## Prerequisites
     * * Enable the setting "My Suggestions" for the portal specified in the URL
     * * If the user is a customer, enable the setting "Allow Customer Access" for the portal.
     * * The Suggestion specified in the URL must belong to the user.
     * 
     * @return The async call builder
     */
    public GetSuggestionAttachmentByIdRequestBuilder getSuggestionAttachmentById() {
        return new GetSuggestionAttachmentByIdRequestBuilder(sdkConfiguration);
    }

    /**
     * Get Suggestion Attachment by ID
     * 
     * <p>## Overview
     * The Get Suggestion Attachment by ID API allows authenticated users to get the details of an
     * attachment that belongs to their own Suggestion. It also allows the download of attachment content.
     * 
     * <p>## Prerequisites
     * * Enable the setting "My Suggestions" for the portal specified in the URL
     * * If the user is a customer, enable the setting "Allow Customer Access" for the portal.
     * * The Suggestion specified in the URL must belong to the user.
     * 
     * @param acceptLanguage 
     * @param portalID The ID of the portal being accessed.<br><br>A portal ID is composed of a 2-4 letter prefix, followed by a dash and 4-15 digits.
     * @param attachmentID The ID of the attachment.<br><br>An attachment ID is composed of a 2-4 letter prefix, followed by a dash and 4-15 digits.
     * @return {@code CompletableFuture<GetSuggestionAttachmentByIdResponse>} - The async response
     */
    public CompletableFuture<GetSuggestionAttachmentByIdResponse> getSuggestionAttachmentById(
            @Nonnull AcceptLanguage acceptLanguage, @Nonnull String portalID,
            @Nonnull String attachmentID) {
        return getSuggestionAttachmentById(
                acceptLanguage, portalID, attachmentID,
                null);
    }

    /**
     * Get Suggestion Attachment by ID
     * 
     * <p>## Overview
     * The Get Suggestion Attachment by ID API allows authenticated users to get the details of an
     * attachment that belongs to their own Suggestion. It also allows the download of attachment content.
     * 
     * <p>## Prerequisites
     * * Enable the setting "My Suggestions" for the portal specified in the URL
     * * If the user is a customer, enable the setting "Allow Customer Access" for the portal.
     * * The Suggestion specified in the URL must belong to the user.
     * 
     * @param acceptLanguage 
     * @param portalID The ID of the portal being accessed.<br><br>A portal ID is composed of a 2-4 letter prefix, followed by a dash and 4-15 digits.
     * @param attachmentID The ID of the attachment.<br><br>An attachment ID is composed of a 2-4 letter prefix, followed by a dash and 4-15 digits.
     * @param attachmentAdditionalAttributes The attributes of an attachment to be returned, along with the default attachment details.
     *         
     *         | Attribute    | Description                        |
     *         |--------------|------------------------------------|
     *         | id         | Unique identifier for the attachment |
     *         | fileName   | Name of the file                   |
     *         | contentType| Content type of the file              |
     *         | size       | Size of the file in bytes          |
     *         | link       | Link to the attachment             | 
     *         
     * @return {@code CompletableFuture<GetSuggestionAttachmentByIdResponse>} - The async response
     */
    public CompletableFuture<GetSuggestionAttachmentByIdResponse> getSuggestionAttachmentById(
            @Nonnull AcceptLanguage acceptLanguage, @Nonnull String portalID,
            @Nonnull String attachmentID, @Nullable List<AttachmentAdditionalAttributes> attachmentAdditionalAttributes) {
        GetSuggestionAttachmentByIdRequest request = new GetSuggestionAttachmentByIdRequest(
                acceptLanguage, portalID, attachmentID,
                attachmentAdditionalAttributes);
        AsyncRequestOperation<GetSuggestionAttachmentByIdRequest, GetSuggestionAttachmentByIdResponse> operation
              = new GetSuggestionAttachmentById.Async(sdkConfiguration, _headers);
        return operation.doRequest(request)
            .thenCompose(operation::handleResponse);
    }

}
