/* 
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */
package com.egain.sdk;

import static com.egain.sdk.operations.Operations.RequestOperation;

import com.egain.sdk.models.operations.RetrieveChunksRequest;
import com.egain.sdk.models.operations.RetrieveChunksRequestBuilder;
import com.egain.sdk.models.operations.RetrieveChunksResponse;
import com.egain.sdk.operations.RetrieveChunks;
import com.egain.sdk.utils.Headers;
import jakarta.annotation.Nonnull;
import jakarta.annotation.Nullable;
import java.lang.String;


public class Retrieve {
    private static final Headers _headers = Headers.EMPTY;
    private final SDKConfiguration sdkConfiguration;
    private final AsyncRetrieve asyncSDK;

    Retrieve(SDKConfiguration sdkConfiguration) {
        this.sdkConfiguration = sdkConfiguration;
        this.asyncSDK = new AsyncRetrieve(this, sdkConfiguration);
    }

    /**
     * Switches to the async SDK.
     * 
     * @return The async SDK
     */
    public AsyncRetrieve async() {
        return asyncSDK;
    }

    /**
     * Retrieve Chunks
     * 
     * <p>The Retrieve API enables enterprises to directly access relevant content chunks from their
     * organizational knowledge sources. It is designed for scenarios where developers want granular
     * control over retrieved information, such as powering custom search, analytics, or
     * retrieval-augmented generation (RAG) pipelines.
     * 
     * <p>The Retrieve API's response will either be a Certified Answer or a list of chunks.
     * - **Certified Answers Response**: This response is observed when there's a matching certified answer
     * to the user's query.
     * - **Chunk List Response**: This response is observed, if there is no matched Certified Answer.
     * 
     * <p>Responses for both chunks and certified answers include relevance scores and metadata. By leveraging
     * the Retrieve API, organizations can build tailored experiences while retaining confidence in the
     * source material.
     * 
     * @return The call builder
     */
    public RetrieveChunksRequestBuilder retrieveChunks() {
        return new RetrieveChunksRequestBuilder(sdkConfiguration);
    }

    /**
     * Retrieve Chunks
     * 
     * <p>The Retrieve API enables enterprises to directly access relevant content chunks from their
     * organizational knowledge sources. It is designed for scenarios where developers want granular
     * control over retrieved information, such as powering custom search, analytics, or
     * retrieval-augmented generation (RAG) pipelines.
     * 
     * <p>The Retrieve API's response will either be a Certified Answer or a list of chunks.
     * - **Certified Answers Response**: This response is observed when there's a matching certified answer
     * to the user's query.
     * - **Chunk List Response**: This response is observed, if there is no matched Certified Answer.
     * 
     * <p>Responses for both chunks and certified answers include relevance scores and metadata. By leveraging
     * the Retrieve API, organizations can build tailored experiences while retaining confidence in the
     * source material.
     * 
     * @param request The request object containing all the parameters for the API call.
     * @return The response from the API call
     * @throws RuntimeException subclass if the API call fails
     */
    public RetrieveChunksResponse retrieveChunks(@Nonnull RetrieveChunksRequest request) {
        return retrieveChunks(request, null);
    }

    /**
     * Retrieve Chunks
     * 
     * <p>The Retrieve API enables enterprises to directly access relevant content chunks from their
     * organizational knowledge sources. It is designed for scenarios where developers want granular
     * control over retrieved information, such as powering custom search, analytics, or
     * retrieval-augmented generation (RAG) pipelines.
     * 
     * <p>The Retrieve API's response will either be a Certified Answer or a list of chunks.
     * - **Certified Answers Response**: This response is observed when there's a matching certified answer
     * to the user's query.
     * - **Chunk List Response**: This response is observed, if there is no matched Certified Answer.
     * 
     * <p>Responses for both chunks and certified answers include relevance scores and metadata. By leveraging
     * the Retrieve API, organizations can build tailored experiences while retaining confidence in the
     * source material.
     * 
     * @param request The request object containing all the parameters for the API call.
     * @param serverURL Overrides the server URL.
     * @return The response from the API call
     * @throws RuntimeException subclass if the API call fails
     */
    public RetrieveChunksResponse retrieveChunks(@Nonnull RetrieveChunksRequest request, @Nullable String serverURL) {
        RequestOperation<RetrieveChunksRequest, RetrieveChunksResponse> operation
              = new RetrieveChunks.Sync(sdkConfiguration, serverURL, _headers);
        return operation.handleResponse(operation.doRequest(request));
    }

}
