/* 
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */
package com.egain.sdk;

import static com.egain.sdk.operations.Operations.RequestOperation;

import com.egain.sdk.models.components.AcceptLanguage;
import com.egain.sdk.models.components.MandatoryLanguageQueryParameter;
import com.egain.sdk.models.operations.GetTopicBreadcrumbForArticleRequest;
import com.egain.sdk.models.operations.GetTopicBreadcrumbForArticleRequestBuilder;
import com.egain.sdk.models.operations.GetTopicBreadcrumbForArticleResponse;
import com.egain.sdk.models.operations.GetalltopicsRequest;
import com.egain.sdk.models.operations.GetalltopicsRequestBuilder;
import com.egain.sdk.models.operations.GetalltopicsResponse;
import com.egain.sdk.models.operations.GetancestortopicsRequest;
import com.egain.sdk.models.operations.GetancestortopicsRequestBuilder;
import com.egain.sdk.models.operations.GetancestortopicsResponse;
import com.egain.sdk.models.operations.GetchildtopicsRequest;
import com.egain.sdk.models.operations.GetchildtopicsRequestBuilder;
import com.egain.sdk.models.operations.GetchildtopicsResponse;
import com.egain.sdk.operations.GetTopicBreadcrumbForArticle;
import com.egain.sdk.operations.Getalltopics;
import com.egain.sdk.operations.Getancestortopics;
import com.egain.sdk.operations.Getchildtopics;
import com.egain.sdk.utils.Headers;
import jakarta.annotation.Nonnull;
import java.lang.String;


public class Topic {
    private static final Headers _headers = Headers.EMPTY;
    private final SDKConfiguration sdkConfiguration;
    private final AsyncTopic asyncSDK;

    Topic(SDKConfiguration sdkConfiguration) {
        this.sdkConfiguration = sdkConfiguration;
        this.asyncSDK = new AsyncTopic(this, sdkConfiguration);
    }

    /**
     * Switches to the async SDK.
     * 
     * @return The async SDK
     */
    public AsyncTopic async() {
        return asyncSDK;
    }

    /**
     * Get Topic Breadcrumb for Article
     * 
     * <p>## Overview
     * * Use this API to retrieve the topic breadcrumb for an article in a portal. A breadcrumb shows the
     * hierarchical path from the root topic to the article's primary topic.
     * 
     * @return The call builder
     */
    public GetTopicBreadcrumbForArticleRequestBuilder getTopicBreadcrumbForArticle() {
        return new GetTopicBreadcrumbForArticleRequestBuilder(sdkConfiguration);
    }

    /**
     * Get Topic Breadcrumb for Article
     * 
     * <p>## Overview
     * * Use this API to retrieve the topic breadcrumb for an article in a portal. A breadcrumb shows the
     * hierarchical path from the root topic to the article's primary topic.
     * 
     * @param acceptLanguage 
     * @param portalID The ID of the portal being accessed.<br><br>A portal ID is composed of a 2-4 letter prefix, followed by a dash and 4-15 digits.
     * @param articleID The ID of the Article.<br><br>An Article ID is composed of a 2-4 letter prefix followed by a dash and 4-15 digits.
     * @param language 
     * @return The response from the API call
     * @throws RuntimeException subclass if the API call fails
     */
    public GetTopicBreadcrumbForArticleResponse getTopicBreadcrumbForArticle(
            @Nonnull AcceptLanguage acceptLanguage, @Nonnull String portalID,
            @Nonnull String articleID, @Nonnull MandatoryLanguageQueryParameter language) {
        GetTopicBreadcrumbForArticleRequest request = new GetTopicBreadcrumbForArticleRequest(
                acceptLanguage, portalID, articleID,
                language);
        RequestOperation<GetTopicBreadcrumbForArticleRequest, GetTopicBreadcrumbForArticleResponse> operation
              = new GetTopicBreadcrumbForArticle.Sync(sdkConfiguration, _headers);
        return operation.handleResponse(operation.doRequest(request));
    }

    /**
     * Get Immediate Child Topics
     * 
     * <p>## Overview
     * The Get Immediate Child Topics API retrieves details about a topic and it's immediate child topics.
     * The <code>$level</code> attribute determines how deep the topic hierarchy should go, or how many
     * child topics of a topic are returned in the response.
     * 
     * @return The call builder
     */
    public GetchildtopicsRequestBuilder getchildtopics() {
        return new GetchildtopicsRequestBuilder(sdkConfiguration);
    }

    /**
     * Get Immediate Child Topics
     * 
     * <p>## Overview
     * The Get Immediate Child Topics API retrieves details about a topic and it's immediate child topics.
     * The <code>$level</code> attribute determines how deep the topic hierarchy should go, or how many
     * child topics of a topic are returned in the response.
     * 
     * @param request The request object containing all the parameters for the API call.
     * @return The response from the API call
     * @throws RuntimeException subclass if the API call fails
     */
    public GetchildtopicsResponse getchildtopics(@Nonnull GetchildtopicsRequest request) {
        RequestOperation<GetchildtopicsRequest, GetchildtopicsResponse> operation
              = new Getchildtopics.Sync(sdkConfiguration, _headers);
        return operation.handleResponse(operation.doRequest(request));
    }

    /**
     * Get All Ancestor Topics
     * 
     * <p>## Overview
     * The Get All Ancestor Topics API retrieves the hierarchy from the root topic down to the given topic.
     * 
     * @return The call builder
     */
    public GetancestortopicsRequestBuilder getancestortopics() {
        return new GetancestortopicsRequestBuilder(sdkConfiguration);
    }

    /**
     * Get All Ancestor Topics
     * 
     * <p>## Overview
     * The Get All Ancestor Topics API retrieves the hierarchy from the root topic down to the given topic.
     * 
     * @param request The request object containing all the parameters for the API call.
     * @return The response from the API call
     * @throws RuntimeException subclass if the API call fails
     */
    public GetancestortopicsResponse getancestortopics(@Nonnull GetancestortopicsRequest request) {
        RequestOperation<GetancestortopicsRequest, GetancestortopicsResponse> operation
              = new Getancestortopics.Sync(sdkConfiguration, _headers);
        return operation.handleResponse(operation.doRequest(request));
    }

    /**
     * Get All Topics
     * 
     * <p>## Overview
     * The Get All Topics API retrieves the topic tree for a portal. The <code>$level</code> attribute
     * determines how deep the topic hierarchy should go, or how many child topics of a topic are returned
     * in the response.
     * 
     * @return The call builder
     */
    public GetalltopicsRequestBuilder getalltopics() {
        return new GetalltopicsRequestBuilder(sdkConfiguration);
    }

    /**
     * Get All Topics
     * 
     * <p>## Overview
     * The Get All Topics API retrieves the topic tree for a portal. The <code>$level</code> attribute
     * determines how deep the topic hierarchy should go, or how many child topics of a topic are returned
     * in the response.
     * 
     * @param request The request object containing all the parameters for the API call.
     * @return The response from the API call
     * @throws RuntimeException subclass if the API call fails
     */
    public GetalltopicsResponse getalltopics(@Nonnull GetalltopicsRequest request) {
        RequestOperation<GetalltopicsRequest, GetalltopicsResponse> operation
              = new Getalltopics.Sync(sdkConfiguration, _headers);
        return operation.handleResponse(operation.doRequest(request));
    }

}
