/* 
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */
package com.egain.sdk.models.operations.async;

import static com.egain.sdk.operations.Operations.AsyncRequestOperation;

import com.egain.sdk.SDKConfiguration;
import com.egain.sdk.models.components.AcceptLanguage;
import com.egain.sdk.models.components.LanguageQueryParameter;
import com.egain.sdk.models.operations.CreateQuickpickRequest;
import com.egain.sdk.operations.CreateQuickpick;
import com.egain.sdk.utils.Headers;
import com.egain.sdk.utils.Utils;
import jakarta.annotation.Nonnull;
import jakarta.annotation.Nullable;
import java.lang.String;
import java.util.concurrent.CompletableFuture;

public class CreateQuickpickRequestBuilder {
    private final SDKConfiguration sdkConfiguration;
    private final Headers _headers = new Headers();
    private final CreateQuickpickRequest.Builder pojoBuilder;
    private CreateQuickpickRequest request;
    private boolean _setterCalled;

    public CreateQuickpickRequestBuilder(SDKConfiguration sdkConfiguration) {
        this.sdkConfiguration = sdkConfiguration;
        this.pojoBuilder = CreateQuickpickRequest.builder();
    }

    public CreateQuickpickRequestBuilder acceptLanguage(@Nonnull AcceptLanguage acceptLanguage) {
        this.pojoBuilder.acceptLanguage(acceptLanguage);
        this._setterCalled = true;
        return this;
    }

    public CreateQuickpickRequestBuilder portalID(@Nonnull String portalID) {
        this.pojoBuilder.portalID(portalID);
        this._setterCalled = true;
        return this;
    }

    public CreateQuickpickRequestBuilder language(@Nullable LanguageQueryParameter language) {
        this.pojoBuilder.language(language);
        this._setterCalled = true;
        return this;
    }

    public CreateQuickpickRequestBuilder body(@Nonnull com.egain.sdk.models.components.CreateQuickpick body) {
        this.pojoBuilder.body(body);
        this._setterCalled = true;
        return this;
    }

    private CreateQuickpickRequest _buildRequest() {
        if (this._setterCalled) {
            this.request = this.pojoBuilder.build();
        }
        return this.request;
    }
    
    public CreateQuickpickRequestBuilder header(String name, String value) {
        Utils.checkNotNull(name, "name");
        Utils.checkNotNull(value, "value");
        this._headers.add(name, value);
        return this;
    }

    /**
    * Executes the request and returns the response.
    *
    * @return The response from the server.
    */
    public CompletableFuture<CreateQuickpickResponse> call() {
        AsyncRequestOperation<CreateQuickpickRequest, CreateQuickpickResponse> operation
              = new CreateQuickpick.Async(sdkConfiguration, _headers);
        return operation.doRequest(this._buildRequest())
            .thenCompose(operation::handleResponse);
    }
}
