/* 
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */
package com.egain.sdk.models.operations.async;

import static com.egain.sdk.operations.Operations.AsyncRequestOperation;

import com.egain.sdk.SDKConfiguration;
import com.egain.sdk.models.components.ImportContent;
import com.egain.sdk.operations.CreateImportJob;
import com.egain.sdk.utils.Headers;
import com.egain.sdk.utils.Utils;
import jakarta.annotation.Nonnull;
import jakarta.annotation.Nullable;
import java.lang.String;
import java.util.concurrent.CompletableFuture;

public class CreateImportJobRequestBuilder {
    private final SDKConfiguration sdkConfiguration;
    private final Headers _headers = new Headers();
    private ImportContent request;
    private String serverURL;

    public CreateImportJobRequestBuilder(SDKConfiguration sdkConfiguration) {
        this.sdkConfiguration = sdkConfiguration;
    }

    public CreateImportJobRequestBuilder request(@Nonnull ImportContent request) {
        this.request = Utils.checkNotNull(request, "request");
        return this;
    }

    public CreateImportJobRequestBuilder serverURL(@Nullable String serverURL) {
        this.serverURL = serverURL;
        return this;
    }

    private ImportContent _buildRequest() {
        return this.request;
    }
    
    public CreateImportJobRequestBuilder header(String name, String value) {
        Utils.checkNotNull(name, "name");
        Utils.checkNotNull(value, "value");
        this._headers.add(name, value);
        return this;
    }

    /**
    * Executes the request and returns the response.
    *
    * @return The response from the server.
    */
    public CompletableFuture<CreateImportJobResponse> call() {
        AsyncRequestOperation<ImportContent, CreateImportJobResponse> operation
              = new CreateImportJob.Async(sdkConfiguration, serverURL, _headers);
        return operation.doRequest(this._buildRequest())
            .thenCompose(operation::handleResponse);
    }
}
