/* 
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */
package com.egain.sdk.models.operations.async;

import static com.egain.sdk.operations.Operations.AsyncRequestOperation;

import com.egain.sdk.SDKConfiguration;
import com.egain.sdk.models.operations.GetAnnouncementArticlesRequest;
import com.egain.sdk.operations.GetAnnouncementArticles;
import com.egain.sdk.utils.Headers;
import com.egain.sdk.utils.Utils;
import jakarta.annotation.Nonnull;
import java.util.concurrent.CompletableFuture;

public class GetAnnouncementArticlesRequestBuilder {
    private final SDKConfiguration sdkConfiguration;
    private final Headers _headers = new Headers();
    private GetAnnouncementArticlesRequest request;

    public GetAnnouncementArticlesRequestBuilder(SDKConfiguration sdkConfiguration) {
        this.sdkConfiguration = sdkConfiguration;
    }

    public GetAnnouncementArticlesRequestBuilder request(@Nonnull GetAnnouncementArticlesRequest request) {
        this.request = Utils.checkNotNull(request, "request");
        return this;
    }

    private GetAnnouncementArticlesRequest _buildRequest() {
        return this.request;
    }
    
    public GetAnnouncementArticlesRequestBuilder header(String name, String value) {
        Utils.checkNotNull(name, "name");
        Utils.checkNotNull(value, "value");
        this._headers.add(name, value);
        return this;
    }

    /**
    * Executes the request and returns the response.
    *
    * @return The response from the server.
    */
    public CompletableFuture<GetAnnouncementArticlesResponse> call() {
        AsyncRequestOperation<GetAnnouncementArticlesRequest, GetAnnouncementArticlesResponse> operation
              = new GetAnnouncementArticles.Async(sdkConfiguration, _headers);
        return operation.doRequest(this._buildRequest())
            .thenCompose(operation::handleResponse);
    }
}
