/* 
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */
package com.egain.sdk.models.operations.async;

import static com.egain.sdk.operations.Operations.AsyncRequestOperation;

import com.egain.sdk.SDKConfiguration;
import com.egain.sdk.models.operations.GetArticlePersonalizationRequest;
import com.egain.sdk.operations.GetArticlePersonalization;
import com.egain.sdk.utils.Headers;
import com.egain.sdk.utils.Utils;
import jakarta.annotation.Nonnull;
import java.util.concurrent.CompletableFuture;

public class GetArticlePersonalizationRequestBuilder {
    private final SDKConfiguration sdkConfiguration;
    private final Headers _headers = new Headers();
    private GetArticlePersonalizationRequest request;

    public GetArticlePersonalizationRequestBuilder(SDKConfiguration sdkConfiguration) {
        this.sdkConfiguration = sdkConfiguration;
    }

    public GetArticlePersonalizationRequestBuilder request(@Nonnull GetArticlePersonalizationRequest request) {
        this.request = Utils.checkNotNull(request, "request");
        return this;
    }

    private GetArticlePersonalizationRequest _buildRequest() {
        return this.request;
    }
    
    public GetArticlePersonalizationRequestBuilder header(String name, String value) {
        Utils.checkNotNull(name, "name");
        Utils.checkNotNull(value, "value");
        this._headers.add(name, value);
        return this;
    }

    /**
    * Executes the request and returns the response.
    *
    * @return The response from the server.
    */
    public CompletableFuture<GetArticlePersonalizationResponse> call() {
        AsyncRequestOperation<GetArticlePersonalizationRequest, GetArticlePersonalizationResponse> operation
              = new GetArticlePersonalization.Async(sdkConfiguration, _headers);
        return operation.doRequest(this._buildRequest())
            .thenCompose(operation::handleResponse);
    }
}
