/* 
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */
package com.egain.sdk.models.operations.async;

import static com.egain.sdk.operations.Operations.AsyncRequestOperation;

import com.egain.sdk.SDKConfiguration;
import com.egain.sdk.models.operations.GetancestortopicsRequest;
import com.egain.sdk.operations.Getancestortopics;
import com.egain.sdk.utils.Headers;
import com.egain.sdk.utils.Utils;
import jakarta.annotation.Nonnull;
import java.util.concurrent.CompletableFuture;

public class GetancestortopicsRequestBuilder {
    private final SDKConfiguration sdkConfiguration;
    private final Headers _headers = new Headers();
    private GetancestortopicsRequest request;

    public GetancestortopicsRequestBuilder(SDKConfiguration sdkConfiguration) {
        this.sdkConfiguration = sdkConfiguration;
    }

    public GetancestortopicsRequestBuilder request(@Nonnull GetancestortopicsRequest request) {
        this.request = Utils.checkNotNull(request, "request");
        return this;
    }

    private GetancestortopicsRequest _buildRequest() {
        return this.request;
    }
    
    public GetancestortopicsRequestBuilder header(String name, String value) {
        Utils.checkNotNull(name, "name");
        Utils.checkNotNull(value, "value");
        this._headers.add(name, value);
        return this;
    }

    /**
    * Executes the request and returns the response.
    *
    * @return The response from the server.
    */
    public CompletableFuture<GetancestortopicsResponse> call() {
        AsyncRequestOperation<GetancestortopicsRequest, GetancestortopicsResponse> operation
              = new Getancestortopics.Async(sdkConfiguration, _headers);
        return operation.doRequest(this._buildRequest())
            .thenCompose(operation::handleResponse);
    }
}
