/* 
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */
package com.egain.sdk.models.operations.async;

import static com.egain.sdk.operations.Operations.AsyncRequestOperation;

import com.egain.sdk.SDKConfiguration;
import com.egain.sdk.models.operations.GetalltopicsRequest;
import com.egain.sdk.operations.Getalltopics;
import com.egain.sdk.utils.Headers;
import com.egain.sdk.utils.Utils;
import jakarta.annotation.Nonnull;
import java.util.concurrent.CompletableFuture;

public class GetalltopicsRequestBuilder {
    private final SDKConfiguration sdkConfiguration;
    private final Headers _headers = new Headers();
    private GetalltopicsRequest request;

    public GetalltopicsRequestBuilder(SDKConfiguration sdkConfiguration) {
        this.sdkConfiguration = sdkConfiguration;
    }

    public GetalltopicsRequestBuilder request(@Nonnull GetalltopicsRequest request) {
        this.request = Utils.checkNotNull(request, "request");
        return this;
    }

    private GetalltopicsRequest _buildRequest() {
        return this.request;
    }
    
    public GetalltopicsRequestBuilder header(String name, String value) {
        Utils.checkNotNull(name, "name");
        Utils.checkNotNull(value, "value");
        this._headers.add(name, value);
        return this;
    }

    /**
    * Executes the request and returns the response.
    *
    * @return The response from the server.
    */
    public CompletableFuture<GetalltopicsResponse> call() {
        AsyncRequestOperation<GetalltopicsRequest, GetalltopicsResponse> operation
              = new Getalltopics.Async(sdkConfiguration, _headers);
        return operation.doRequest(this._buildRequest())
            .thenCompose(operation::handleResponse);
    }
}
