/* 
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */
package com.egain.sdk.models.operations.async;

import static com.egain.sdk.operations.Operations.AsyncRequestOperation;

import com.egain.sdk.SDKConfiguration;
import com.egain.sdk.models.components.AcceptLanguage;
import com.egain.sdk.models.operations.GetPromptTemplateByIdLanguageCode;
import com.egain.sdk.models.operations.GetPromptTemplateByIdRequest;
import com.egain.sdk.operations.GetPromptTemplateById;
import com.egain.sdk.utils.Headers;
import com.egain.sdk.utils.Utils;
import jakarta.annotation.Nonnull;
import jakarta.annotation.Nullable;
import java.lang.String;
import java.util.concurrent.CompletableFuture;

public class GetPromptTemplateByIdRequestBuilder {
    private final SDKConfiguration sdkConfiguration;
    private final Headers _headers = new Headers();
    private final GetPromptTemplateByIdRequest.Builder pojoBuilder;
    private GetPromptTemplateByIdRequest request;
    private String serverURL;
    private boolean _setterCalled;

    public GetPromptTemplateByIdRequestBuilder(SDKConfiguration sdkConfiguration) {
        this.sdkConfiguration = sdkConfiguration;
        this.pojoBuilder = GetPromptTemplateByIdRequest.builder();
    }

    public GetPromptTemplateByIdRequestBuilder acceptLanguage(@Nonnull AcceptLanguage acceptLanguage) {
        this.pojoBuilder.acceptLanguage(acceptLanguage);
        this._setterCalled = true;
        return this;
    }

    public GetPromptTemplateByIdRequestBuilder department(@Nonnull String department) {
        this.pojoBuilder.department(department);
        this._setterCalled = true;
        return this;
    }

    public GetPromptTemplateByIdRequestBuilder languageCode(@Nonnull GetPromptTemplateByIdLanguageCode languageCode) {
        this.pojoBuilder.languageCode(languageCode);
        this._setterCalled = true;
        return this;
    }

    public GetPromptTemplateByIdRequestBuilder promptID(@Nonnull String promptID) {
        this.pojoBuilder.promptID(promptID);
        this._setterCalled = true;
        return this;
    }

    public GetPromptTemplateByIdRequestBuilder serverURL(@Nullable String serverURL) {
        this.serverURL = serverURL;
        return this;
    }

    private GetPromptTemplateByIdRequest _buildRequest() {
        if (this._setterCalled) {
            this.request = this.pojoBuilder.build();
        }
        return this.request;
    }
    
    public GetPromptTemplateByIdRequestBuilder header(String name, String value) {
        Utils.checkNotNull(name, "name");
        Utils.checkNotNull(value, "value");
        this._headers.add(name, value);
        return this;
    }

    /**
    * Executes the request and returns the response.
    *
    * @return The response from the server.
    */
    public CompletableFuture<GetPromptTemplateByIdResponse> call() {
        AsyncRequestOperation<GetPromptTemplateByIdRequest, GetPromptTemplateByIdResponse> operation
              = new GetPromptTemplateById.Async(sdkConfiguration, serverURL, _headers);
        return operation.doRequest(this._buildRequest())
            .thenCompose(operation::handleResponse);
    }
}
