/* 
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */
package com.egain.sdk.models.operations.async;

import static com.egain.sdk.operations.Operations.AsyncRequestOperation;

import com.egain.sdk.SDKConfiguration;
import com.egain.sdk.models.components.AcceptLanguage;
import com.egain.sdk.models.operations.GetSuggestionAttachmentsRequest;
import com.egain.sdk.operations.GetSuggestionAttachments;
import com.egain.sdk.utils.Headers;
import com.egain.sdk.utils.Utils;
import jakarta.annotation.Nonnull;
import java.lang.String;
import java.util.concurrent.CompletableFuture;

public class GetSuggestionAttachmentsRequestBuilder {
    private final SDKConfiguration sdkConfiguration;
    private final Headers _headers = new Headers();
    private final GetSuggestionAttachmentsRequest.Builder pojoBuilder;
    private GetSuggestionAttachmentsRequest request;
    private boolean _setterCalled;

    public GetSuggestionAttachmentsRequestBuilder(SDKConfiguration sdkConfiguration) {
        this.sdkConfiguration = sdkConfiguration;
        this.pojoBuilder = GetSuggestionAttachmentsRequest.builder();
    }

    public GetSuggestionAttachmentsRequestBuilder acceptLanguage(@Nonnull AcceptLanguage acceptLanguage) {
        this.pojoBuilder.acceptLanguage(acceptLanguage);
        this._setterCalled = true;
        return this;
    }

    public GetSuggestionAttachmentsRequestBuilder portalID(@Nonnull String portalID) {
        this.pojoBuilder.portalID(portalID);
        this._setterCalled = true;
        return this;
    }

    public GetSuggestionAttachmentsRequestBuilder suggestionID(@Nonnull String suggestionID) {
        this.pojoBuilder.suggestionID(suggestionID);
        this._setterCalled = true;
        return this;
    }

    private GetSuggestionAttachmentsRequest _buildRequest() {
        if (this._setterCalled) {
            this.request = this.pojoBuilder.build();
        }
        return this.request;
    }
    
    public GetSuggestionAttachmentsRequestBuilder header(String name, String value) {
        Utils.checkNotNull(name, "name");
        Utils.checkNotNull(value, "value");
        this._headers.add(name, value);
        return this;
    }

    /**
    * Executes the request and returns the response.
    *
    * @return The response from the server.
    */
    public CompletableFuture<GetSuggestionAttachmentsResponse> call() {
        AsyncRequestOperation<GetSuggestionAttachmentsRequest, GetSuggestionAttachmentsResponse> operation
              = new GetSuggestionAttachments.Async(sdkConfiguration, _headers);
        return operation.doRequest(this._buildRequest())
            .thenCompose(operation::handleResponse);
    }
}
