/* 
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */
package com.egain.sdk.models.operations.async;

import static com.egain.sdk.operations.Operations.AsyncRequestOperation;

import com.egain.sdk.SDKConfiguration;
import com.egain.sdk.models.components.AcceptLanguage;
import com.egain.sdk.models.components.ModifySuggestion;
import com.egain.sdk.models.operations.ModifySuggestionsRequest;
import com.egain.sdk.operations.ModifySuggestions;
import com.egain.sdk.utils.Headers;
import com.egain.sdk.utils.Utils;
import jakarta.annotation.Nonnull;
import jakarta.annotation.Nullable;
import java.lang.String;
import java.util.concurrent.CompletableFuture;

public class ModifySuggestionsRequestBuilder {
    private final SDKConfiguration sdkConfiguration;
    private final Headers _headers = new Headers();
    private final ModifySuggestionsRequest.Builder pojoBuilder;
    private ModifySuggestionsRequest request;
    private boolean _setterCalled;

    public ModifySuggestionsRequestBuilder(SDKConfiguration sdkConfiguration) {
        this.sdkConfiguration = sdkConfiguration;
        this.pojoBuilder = ModifySuggestionsRequest.builder();
    }

    public ModifySuggestionsRequestBuilder acceptLanguage(@Nonnull AcceptLanguage acceptLanguage) {
        this.pojoBuilder.acceptLanguage(acceptLanguage);
        this._setterCalled = true;
        return this;
    }

    public ModifySuggestionsRequestBuilder portalID(@Nonnull String portalID) {
        this.pojoBuilder.portalID(portalID);
        this._setterCalled = true;
        return this;
    }

    public ModifySuggestionsRequestBuilder body(@Nullable ModifySuggestion body) {
        this.pojoBuilder.body(body);
        this._setterCalled = true;
        return this;
    }

    private ModifySuggestionsRequest _buildRequest() {
        if (this._setterCalled) {
            this.request = this.pojoBuilder.build();
        }
        return this.request;
    }
    
    public ModifySuggestionsRequestBuilder header(String name, String value) {
        Utils.checkNotNull(name, "name");
        Utils.checkNotNull(value, "value");
        this._headers.add(name, value);
        return this;
    }

    /**
    * Executes the request and returns the response.
    *
    * @return The response from the server.
    */
    public CompletableFuture<ModifySuggestionsResponse> call() {
        AsyncRequestOperation<ModifySuggestionsRequest, ModifySuggestionsResponse> operation
              = new ModifySuggestions.Async(sdkConfiguration, _headers);
        return operation.doRequest(this._buildRequest())
            .thenCompose(operation::handleResponse);
    }
}
