workflowVersion: 1.0.0
speakeasyVersion: latest
sources:
    Knowledge Portal Manager APIs:
        inputs:
            - location: ../speakeasy/aiservices/v4/api-with-overlay.yaml
            - location: ../speakeasy/contentmgr/v4/api-with-overlay.yaml
            - location: ../speakeasy/portalmgr/v4/api-with-overlay.yaml
        output: .speakeasy/out.openapi.yaml
        registry:
            location: registry.speakeasyapi.dev/egain-corporation/portalmgr/knowledge-portal-manager-ap-is
targets:
    egain:
        target: java
        source: Knowledge Portal Manager APIs
        publish:
            java:
                ossrhUsername: $ossrh_username
                ossrhPassword: $ossrh_password
                gpgSecretKey: $java_gpg_secret_key
                gpgPassPhrase: $java_gpg_passphrase
        codeSamples:
            registry:
                location: registry.speakeasyapi.dev/egain-corporation/portalmgr/knowledge-portal-manager-ap-is-java-code-samples
            labelOverride:
                fixedValue: Java (SDK)
            blocking: false
