/* 
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */
package com.egain.sdk.models.components;

import com.fasterxml.jackson.annotation.JsonValue;
import java.lang.String;
import java.util.Objects;
import java.util.Optional;

/**
 * ActionSearchType
 * 
 * <p>type of the action
 */
public enum ActionSearchType {
    CONTROL("control"),
    ARTICLE("article");

    @JsonValue
    private final String value;

    ActionSearchType(String value) {
        this.value = value;
    }
    
    public String value() {
        return value;
    }
    
    public static Optional<ActionSearchType> fromValue(String value) {
        for (ActionSearchType o: ActionSearchType.values()) {
            if (Objects.deepEquals(o.value, value)) {
                return Optional.of(o);
            }
        }
        return Optional.empty();
    }
}

