/* 
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */
package com.egain.sdk.models.components;

import com.egain.sdk.utils.Utils;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonProperty;
import jakarta.annotation.Nonnull;
import java.lang.Override;
import java.lang.String;
import java.util.Optional;


public class AISearchResponse {
    /**
     * Top search results with relevance scores
     */
    @JsonProperty("searchResults")
    private SearchResults searchResults;

    @JsonCreator
    public AISearchResponse(
            @JsonProperty("searchResults") @Nonnull SearchResults searchResults) {
        this.searchResults = Optional.ofNullable(searchResults)
            .orElseThrow(() -> new IllegalArgumentException("searchResults cannot be null"));
    }

    /**
     * Top search results with relevance scores
     */
    public SearchResults searchResults() {
        return this.searchResults;
    }

    public static Builder builder() {
        return new Builder();
    }


    /**
     * Top search results with relevance scores
     */
    public AISearchResponse withSearchResults(@Nonnull SearchResults searchResults) {
        this.searchResults = Utils.checkNotNull(searchResults, "searchResults");
        return this;
    }


    @Override
    public boolean equals(java.lang.Object o) {
        if (this == o) {
            return true;
        }
        if (o == null || getClass() != o.getClass()) {
            return false;
        }
        AISearchResponse other = (AISearchResponse) o;
        return 
            Utils.enhancedDeepEquals(this.searchResults, other.searchResults);
    }
    
    @Override
    public int hashCode() {
        return Utils.enhancedHash(
            searchResults);
    }
    
    @Override
    public String toString() {
        return Utils.toString(AISearchResponse.class,
                "searchResults", searchResults);
    }

    @SuppressWarnings("UnusedReturnValue")
    public final static class Builder {

        private SearchResults searchResults;

        private Builder() {
          // force use of static builder() method
        }

        /**
         * Top search results with relevance scores
         */
        public Builder searchResults(@Nonnull SearchResults searchResults) {
            this.searchResults = Utils.checkNotNull(searchResults, "searchResults");
            return this;
        }

        public AISearchResponse build() {
            return new AISearchResponse(
                searchResults);
        }

    }
}
