/* 
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */
package com.egain.sdk.models.components;

import com.egain.sdk.utils.Utils;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonInclude.Include;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import jakarta.annotation.Nullable;
import java.lang.Override;
import java.lang.String;
import java.util.List;
import java.util.Optional;

/**
 * AllAccessiblePortals
 * 
 * <p>Success
 */
public class AllAccessiblePortals {
    /**
     * portals
     */
    @JsonInclude(Include.NON_ABSENT)
    @JsonProperty("portal")
    private List<AccessiblePortal> portal;


    @JsonInclude(Include.NON_ABSENT)
    @JsonProperty("paginationInfo")
    private PaginationInfo paginationInfo;

    @JsonCreator
    public AllAccessiblePortals(
            @JsonProperty("portal") @Nullable List<AccessiblePortal> portal,
            @JsonProperty("paginationInfo") @Nullable PaginationInfo paginationInfo) {
        this.portal = portal;
        this.paginationInfo = paginationInfo;
    }
    
    public AllAccessiblePortals() {
        this(null, null);
    }

    /**
     * portals
     */
    public Optional<List<AccessiblePortal>> portal() {
        return Optional.ofNullable(this.portal);
    }

    public Optional<PaginationInfo> paginationInfo() {
        return Optional.ofNullable(this.paginationInfo);
    }

    public static Builder builder() {
        return new Builder();
    }


    /**
     * portals
     */
    public AllAccessiblePortals withPortal(@Nullable List<AccessiblePortal> portal) {
        this.portal = portal;
        return this;
    }


    public AllAccessiblePortals withPaginationInfo(@Nullable PaginationInfo paginationInfo) {
        this.paginationInfo = paginationInfo;
        return this;
    }


    @Override
    public boolean equals(java.lang.Object o) {
        if (this == o) {
            return true;
        }
        if (o == null || getClass() != o.getClass()) {
            return false;
        }
        AllAccessiblePortals other = (AllAccessiblePortals) o;
        return 
            Utils.enhancedDeepEquals(this.portal, other.portal) &&
            Utils.enhancedDeepEquals(this.paginationInfo, other.paginationInfo);
    }
    
    @Override
    public int hashCode() {
        return Utils.enhancedHash(
            portal, paginationInfo);
    }
    
    @Override
    public String toString() {
        return Utils.toString(AllAccessiblePortals.class,
                "portal", portal,
                "paginationInfo", paginationInfo);
    }

    @SuppressWarnings("UnusedReturnValue")
    public final static class Builder {

        private List<AccessiblePortal> portal;

        private PaginationInfo paginationInfo;

        private Builder() {
          // force use of static builder() method
        }

        /**
         * portals
         */
        public Builder portal(@Nullable List<AccessiblePortal> portal) {
            this.portal = portal;
            return this;
        }

        public Builder paginationInfo(@Nullable PaginationInfo paginationInfo) {
            this.paginationInfo = paginationInfo;
            return this;
        }

        public AllAccessiblePortals build() {
            return new AllAccessiblePortals(
                portal, paginationInfo);
        }

    }
}
