/* 
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */
package com.egain.sdk.models.components;

import com.fasterxml.jackson.annotation.JsonValue;
import java.lang.String;
import java.util.Objects;
import java.util.Optional;

/**
 * AnswersResponseAnswerType
 * 
 * <p>Indicates whether the answer was extracted directly from documents or generated by the LLM.
 */
public enum AnswersResponseAnswerType {
    CERTIFIED("certified"),
    GENERATIVE("generative");

    @JsonValue
    private final String value;

    AnswersResponseAnswerType(String value) {
        this.value = value;
    }
    
    public String value() {
        return value;
    }
    
    public static Optional<AnswersResponseAnswerType> fromValue(String value) {
        for (AnswersResponseAnswerType o: AnswersResponseAnswerType.values()) {
            if (Objects.deepEquals(o.value, value)) {
                return Optional.of(o);
            }
        }
        return Optional.empty();
    }
}

