/* 
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */
package com.egain.sdk.models.components;

import com.egain.sdk.utils.Utils;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonInclude.Include;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import jakarta.annotation.Nullable;
import java.lang.Long;
import java.lang.Override;
import java.lang.String;
import java.util.Optional;


public class ArticleAttachment {
    /**
     * The ID of the attachment.
     */
    @JsonInclude(Include.NON_ABSENT)
    @JsonProperty("id")
    private String id;

    /**
     * The name of the attachment.
     */
    @JsonInclude(Include.NON_ABSENT)
    @JsonProperty("name")
    private String name;

    /**
     * The size of the attachment in bytes. The maximum size is limited to 25MB.
     */
    @JsonInclude(Include.NON_ABSENT)
    @JsonProperty("size")
    private Long size;

    /**
     * The type of attachment.
     */
    @JsonInclude(Include.NON_ABSENT)
    @JsonProperty("type")
    private ArticleAttachmentType type;

    /**
     * Defines the relationship between this resource and another object.
     */
    @JsonInclude(Include.NON_ABSENT)
    @JsonProperty("link")
    private Link link;

    @JsonCreator
    public ArticleAttachment(
            @JsonProperty("id") @Nullable String id,
            @JsonProperty("name") @Nullable String name,
            @JsonProperty("size") @Nullable Long size,
            @JsonProperty("type") @Nullable ArticleAttachmentType type,
            @JsonProperty("link") @Nullable Link link) {
        this.id = id;
        this.name = name;
        this.size = size;
        this.type = type;
        this.link = link;
    }
    
    public ArticleAttachment() {
        this(null, null, null,
            null, null);
    }

    /**
     * The ID of the attachment.
     */
    public Optional<String> id() {
        return Optional.ofNullable(this.id);
    }

    /**
     * The name of the attachment.
     */
    public Optional<String> name() {
        return Optional.ofNullable(this.name);
    }

    /**
     * The size of the attachment in bytes. The maximum size is limited to 25MB.
     */
    public Optional<Long> size() {
        return Optional.ofNullable(this.size);
    }

    /**
     * The type of attachment.
     */
    public Optional<ArticleAttachmentType> type() {
        return Optional.ofNullable(this.type);
    }

    /**
     * Defines the relationship between this resource and another object.
     */
    public Optional<Link> link() {
        return Optional.ofNullable(this.link);
    }

    public static Builder builder() {
        return new Builder();
    }


    /**
     * The ID of the attachment.
     */
    public ArticleAttachment withId(@Nullable String id) {
        this.id = id;
        return this;
    }


    /**
     * The name of the attachment.
     */
    public ArticleAttachment withName(@Nullable String name) {
        this.name = name;
        return this;
    }


    /**
     * The size of the attachment in bytes. The maximum size is limited to 25MB.
     */
    public ArticleAttachment withSize(@Nullable Long size) {
        this.size = size;
        return this;
    }


    /**
     * The type of attachment.
     */
    public ArticleAttachment withType(@Nullable ArticleAttachmentType type) {
        this.type = type;
        return this;
    }


    /**
     * Defines the relationship between this resource and another object.
     */
    public ArticleAttachment withLink(@Nullable Link link) {
        this.link = link;
        return this;
    }


    @Override
    public boolean equals(java.lang.Object o) {
        if (this == o) {
            return true;
        }
        if (o == null || getClass() != o.getClass()) {
            return false;
        }
        ArticleAttachment other = (ArticleAttachment) o;
        return 
            Utils.enhancedDeepEquals(this.id, other.id) &&
            Utils.enhancedDeepEquals(this.name, other.name) &&
            Utils.enhancedDeepEquals(this.size, other.size) &&
            Utils.enhancedDeepEquals(this.type, other.type) &&
            Utils.enhancedDeepEquals(this.link, other.link);
    }
    
    @Override
    public int hashCode() {
        return Utils.enhancedHash(
            id, name, size,
            type, link);
    }
    
    @Override
    public String toString() {
        return Utils.toString(ArticleAttachment.class,
                "id", id,
                "name", name,
                "size", size,
                "type", type,
                "link", link);
    }

    @SuppressWarnings("UnusedReturnValue")
    public final static class Builder {

        private String id;

        private String name;

        private Long size;

        private ArticleAttachmentType type;

        private Link link;

        private Builder() {
          // force use of static builder() method
        }

        /**
         * The ID of the attachment.
         */
        public Builder id(@Nullable String id) {
            this.id = id;
            return this;
        }

        /**
         * The name of the attachment.
         */
        public Builder name(@Nullable String name) {
            this.name = name;
            return this;
        }

        /**
         * The size of the attachment in bytes. The maximum size is limited to 25MB.
         */
        public Builder size(@Nullable Long size) {
            this.size = size;
            return this;
        }

        /**
         * The type of attachment.
         */
        public Builder type(@Nullable ArticleAttachmentType type) {
            this.type = type;
            return this;
        }

        /**
         * Defines the relationship between this resource and another object.
         */
        public Builder link(@Nullable Link link) {
            this.link = link;
            return this;
        }

        public ArticleAttachment build() {
            return new ArticleAttachment(
                id, name, size,
                type, link);
        }

    }
}
