/* 
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */
package com.egain.sdk.models.components;

import com.egain.sdk.utils.Utils;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonInclude.Include;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import jakarta.annotation.Nonnull;
import jakarta.annotation.Nullable;
import java.lang.Override;
import java.lang.String;
import java.util.List;
import java.util.Optional;

/**
 * ArticleList
 * 
 * <p>Success
 */
public class ArticleList {
    /**
     * The name of the article list.
     */
    @JsonProperty("name")
    private String name;

    /**
     * The ID of the article list.<br><br>An article list ID is either a 4-digit number or composed of a
     * 2-4 letter prefix, followed by a dash and 4-15 digits.
     */
    @JsonProperty("id")
    private String id;

    /**
     * The description of the article list. The maximum allowed article list description size is 1 KB.
     */
    @JsonInclude(Include.NON_ABSENT)
    @JsonProperty("description")
    private String description;

    /**
     * The type of the article list.
     */
    @JsonInclude(Include.NON_ABSENT)
    @JsonProperty("typeId")
    private String typeId;

    /**
     * An array of articles that belong to the article list.
     */
    @JsonInclude(Include.NON_ABSENT)
    @JsonProperty("articles")
    private List<ArticleResult> articles;

    /**
     * Defines the relationship between this resource and another object.
     */
    @JsonInclude(Include.NON_ABSENT)
    @JsonProperty("link")
    private Link link;

    @JsonCreator
    public ArticleList(
            @JsonProperty("name") @Nonnull String name,
            @JsonProperty("id") @Nonnull String id,
            @JsonProperty("description") @Nullable String description,
            @JsonProperty("typeId") @Nullable String typeId,
            @JsonProperty("articles") @Nullable List<ArticleResult> articles,
            @JsonProperty("link") @Nullable Link link) {
        this.name = Optional.ofNullable(name)
            .orElseThrow(() -> new IllegalArgumentException("name cannot be null"));
        this.id = Optional.ofNullable(id)
            .orElseThrow(() -> new IllegalArgumentException("id cannot be null"));
        this.description = description;
        this.typeId = typeId;
        this.articles = articles;
        this.link = link;
    }
    
    public ArticleList(
            @Nonnull String name,
            @Nonnull String id) {
        this(name, id, null,
            null, null, null);
    }

    /**
     * The name of the article list.
     */
    public String name() {
        return this.name;
    }

    /**
     * The ID of the article list.<br><br>An article list ID is either a 4-digit number or composed of a
     * 2-4 letter prefix, followed by a dash and 4-15 digits.
     */
    public String id() {
        return this.id;
    }

    /**
     * The description of the article list. The maximum allowed article list description size is 1 KB.
     */
    public Optional<String> description() {
        return Optional.ofNullable(this.description);
    }

    /**
     * The type of the article list.
     */
    public Optional<String> typeId() {
        return Optional.ofNullable(this.typeId);
    }

    /**
     * An array of articles that belong to the article list.
     */
    public Optional<List<ArticleResult>> articles() {
        return Optional.ofNullable(this.articles);
    }

    /**
     * Defines the relationship between this resource and another object.
     */
    public Optional<Link> link() {
        return Optional.ofNullable(this.link);
    }

    public static Builder builder() {
        return new Builder();
    }


    /**
     * The name of the article list.
     */
    public ArticleList withName(@Nonnull String name) {
        this.name = Utils.checkNotNull(name, "name");
        return this;
    }


    /**
     * The ID of the article list.<br><br>An article list ID is either a 4-digit number or composed of a
     * 2-4 letter prefix, followed by a dash and 4-15 digits.
     */
    public ArticleList withId(@Nonnull String id) {
        this.id = Utils.checkNotNull(id, "id");
        return this;
    }


    /**
     * The description of the article list. The maximum allowed article list description size is 1 KB.
     */
    public ArticleList withDescription(@Nullable String description) {
        this.description = description;
        return this;
    }


    /**
     * The type of the article list.
     */
    public ArticleList withTypeId(@Nullable String typeId) {
        this.typeId = typeId;
        return this;
    }


    /**
     * An array of articles that belong to the article list.
     */
    public ArticleList withArticles(@Nullable List<ArticleResult> articles) {
        this.articles = articles;
        return this;
    }


    /**
     * Defines the relationship between this resource and another object.
     */
    public ArticleList withLink(@Nullable Link link) {
        this.link = link;
        return this;
    }


    @Override
    public boolean equals(java.lang.Object o) {
        if (this == o) {
            return true;
        }
        if (o == null || getClass() != o.getClass()) {
            return false;
        }
        ArticleList other = (ArticleList) o;
        return 
            Utils.enhancedDeepEquals(this.name, other.name) &&
            Utils.enhancedDeepEquals(this.id, other.id) &&
            Utils.enhancedDeepEquals(this.description, other.description) &&
            Utils.enhancedDeepEquals(this.typeId, other.typeId) &&
            Utils.enhancedDeepEquals(this.articles, other.articles) &&
            Utils.enhancedDeepEquals(this.link, other.link);
    }
    
    @Override
    public int hashCode() {
        return Utils.enhancedHash(
            name, id, description,
            typeId, articles, link);
    }
    
    @Override
    public String toString() {
        return Utils.toString(ArticleList.class,
                "name", name,
                "id", id,
                "description", description,
                "typeId", typeId,
                "articles", articles,
                "link", link);
    }

    @SuppressWarnings("UnusedReturnValue")
    public final static class Builder {

        private String name;

        private String id;

        private String description;

        private String typeId;

        private List<ArticleResult> articles;

        private Link link;

        private Builder() {
          // force use of static builder() method
        }

        /**
         * The name of the article list.
         */
        public Builder name(@Nonnull String name) {
            this.name = Utils.checkNotNull(name, "name");
            return this;
        }

        /**
         * The ID of the article list.<br><br>An article list ID is either a 4-digit number or composed of a
         * 2-4 letter prefix, followed by a dash and 4-15 digits.
         */
        public Builder id(@Nonnull String id) {
            this.id = Utils.checkNotNull(id, "id");
            return this;
        }

        /**
         * The description of the article list. The maximum allowed article list description size is 1 KB.
         */
        public Builder description(@Nullable String description) {
            this.description = description;
            return this;
        }

        /**
         * The type of the article list.
         */
        public Builder typeId(@Nullable String typeId) {
            this.typeId = typeId;
            return this;
        }

        /**
         * An array of articles that belong to the article list.
         */
        public Builder articles(@Nullable List<ArticleResult> articles) {
            this.articles = articles;
            return this;
        }

        /**
         * Defines the relationship between this resource and another object.
         */
        public Builder link(@Nullable Link link) {
            this.link = link;
            return this;
        }

        public ArticleList build() {
            return new ArticleList(
                name, id, description,
                typeId, articles, link);
        }

    }
}
