/* 
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */
package com.egain.sdk.models.components;

import com.egain.sdk.utils.Utils;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonInclude.Include;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import jakarta.annotation.Nullable;
import java.lang.Override;
import java.lang.String;
import java.util.Optional;

/**
 * ArticlePermissionsResult
 * 
 * <p>User permissions on the parent folder.
 */
public class ArticlePermissionsResult {
    /**
     * ID of Article
     */
    @JsonInclude(Include.NON_ABSENT)
    @JsonProperty("articleID")
    private String articleID;

    /**
     * User permissions on the parent folder.
     */
    @JsonInclude(Include.NON_ABSENT)
    @JsonProperty("permissions")
    private ArticlePermissions permissions;

    @JsonCreator
    public ArticlePermissionsResult(
            @JsonProperty("articleID") @Nullable String articleID,
            @JsonProperty("permissions") @Nullable ArticlePermissions permissions) {
        this.articleID = articleID;
        this.permissions = permissions;
    }
    
    public ArticlePermissionsResult() {
        this(null, null);
    }

    /**
     * ID of Article
     */
    public Optional<String> articleID() {
        return Optional.ofNullable(this.articleID);
    }

    /**
     * User permissions on the parent folder.
     */
    public Optional<ArticlePermissions> permissions() {
        return Optional.ofNullable(this.permissions);
    }

    public static Builder builder() {
        return new Builder();
    }


    /**
     * ID of Article
     */
    public ArticlePermissionsResult withArticleID(@Nullable String articleID) {
        this.articleID = articleID;
        return this;
    }


    /**
     * User permissions on the parent folder.
     */
    public ArticlePermissionsResult withPermissions(@Nullable ArticlePermissions permissions) {
        this.permissions = permissions;
        return this;
    }


    @Override
    public boolean equals(java.lang.Object o) {
        if (this == o) {
            return true;
        }
        if (o == null || getClass() != o.getClass()) {
            return false;
        }
        ArticlePermissionsResult other = (ArticlePermissionsResult) o;
        return 
            Utils.enhancedDeepEquals(this.articleID, other.articleID) &&
            Utils.enhancedDeepEquals(this.permissions, other.permissions);
    }
    
    @Override
    public int hashCode() {
        return Utils.enhancedHash(
            articleID, permissions);
    }
    
    @Override
    public String toString() {
        return Utils.toString(ArticlePermissionsResult.class,
                "articleID", articleID,
                "permissions", permissions);
    }

    @SuppressWarnings("UnusedReturnValue")
    public final static class Builder {

        private String articleID;

        private ArticlePermissions permissions;

        private Builder() {
          // force use of static builder() method
        }

        /**
         * ID of Article
         */
        public Builder articleID(@Nullable String articleID) {
            this.articleID = articleID;
            return this;
        }

        /**
         * User permissions on the parent folder.
         */
        public Builder permissions(@Nullable ArticlePermissions permissions) {
            this.permissions = permissions;
            return this;
        }

        public ArticlePermissionsResult build() {
            return new ArticlePermissionsResult(
                articleID, permissions);
        }

    }
}
