/* 
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */
package com.egain.sdk.models.components;

import com.egain.sdk.utils.Utils;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonInclude.Include;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import jakarta.annotation.Nullable;
import java.lang.Override;
import java.lang.String;
import java.util.List;
import java.util.Optional;

/**
 * ArticleRatingsResponse
 * 
 * <p>Success
 */
public class ArticleRatingsResponse {

    @JsonInclude(Include.NON_ABSENT)
    @JsonProperty("articleRatings")
    private List<ArticleRating> articleRatings;


    @JsonInclude(Include.NON_ABSENT)
    @JsonProperty("paginationInfo")
    private PaginationInfo paginationInfo;

    @JsonCreator
    public ArticleRatingsResponse(
            @JsonProperty("articleRatings") @Nullable List<ArticleRating> articleRatings,
            @JsonProperty("paginationInfo") @Nullable PaginationInfo paginationInfo) {
        this.articleRatings = articleRatings;
        this.paginationInfo = paginationInfo;
    }
    
    public ArticleRatingsResponse() {
        this(null, null);
    }

    public Optional<List<ArticleRating>> articleRatings() {
        return Optional.ofNullable(this.articleRatings);
    }

    public Optional<PaginationInfo> paginationInfo() {
        return Optional.ofNullable(this.paginationInfo);
    }

    public static Builder builder() {
        return new Builder();
    }


    public ArticleRatingsResponse withArticleRatings(@Nullable List<ArticleRating> articleRatings) {
        this.articleRatings = articleRatings;
        return this;
    }


    public ArticleRatingsResponse withPaginationInfo(@Nullable PaginationInfo paginationInfo) {
        this.paginationInfo = paginationInfo;
        return this;
    }


    @Override
    public boolean equals(java.lang.Object o) {
        if (this == o) {
            return true;
        }
        if (o == null || getClass() != o.getClass()) {
            return false;
        }
        ArticleRatingsResponse other = (ArticleRatingsResponse) o;
        return 
            Utils.enhancedDeepEquals(this.articleRatings, other.articleRatings) &&
            Utils.enhancedDeepEquals(this.paginationInfo, other.paginationInfo);
    }
    
    @Override
    public int hashCode() {
        return Utils.enhancedHash(
            articleRatings, paginationInfo);
    }
    
    @Override
    public String toString() {
        return Utils.toString(ArticleRatingsResponse.class,
                "articleRatings", articleRatings,
                "paginationInfo", paginationInfo);
    }

    @SuppressWarnings("UnusedReturnValue")
    public final static class Builder {

        private List<ArticleRating> articleRatings;

        private PaginationInfo paginationInfo;

        private Builder() {
          // force use of static builder() method
        }

        public Builder articleRatings(@Nullable List<ArticleRating> articleRatings) {
            this.articleRatings = articleRatings;
            return this;
        }

        public Builder paginationInfo(@Nullable PaginationInfo paginationInfo) {
            this.paginationInfo = paginationInfo;
            return this;
        }

        public ArticleRatingsResponse build() {
            return new ArticleRatingsResponse(
                articleRatings, paginationInfo);
        }

    }
}
