/* 
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */
package com.egain.sdk.models.components;

import com.egain.sdk.utils.Utils;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonInclude.Include;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import jakarta.annotation.Nullable;
import java.lang.Override;
import java.lang.String;
import java.util.List;
import java.util.Optional;

/**
 * ArticleResults
 * 
 * <p>One or more instances of an Article result.
 */
public class ArticleResults {
    /**
     * Article details
     */
    @JsonInclude(Include.NON_ABSENT)
    @JsonProperty("articles")
    private List<ArticleResult> articles;


    @JsonInclude(Include.NON_ABSENT)
    @JsonProperty("paginationInfo")
    private PaginationInfo paginationInfo;

    @JsonCreator
    public ArticleResults(
            @JsonProperty("articles") @Nullable List<ArticleResult> articles,
            @JsonProperty("paginationInfo") @Nullable PaginationInfo paginationInfo) {
        this.articles = articles;
        this.paginationInfo = paginationInfo;
    }
    
    public ArticleResults() {
        this(null, null);
    }

    /**
     * Article details
     */
    public Optional<List<ArticleResult>> articles() {
        return Optional.ofNullable(this.articles);
    }

    public Optional<PaginationInfo> paginationInfo() {
        return Optional.ofNullable(this.paginationInfo);
    }

    public static Builder builder() {
        return new Builder();
    }


    /**
     * Article details
     */
    public ArticleResults withArticles(@Nullable List<ArticleResult> articles) {
        this.articles = articles;
        return this;
    }


    public ArticleResults withPaginationInfo(@Nullable PaginationInfo paginationInfo) {
        this.paginationInfo = paginationInfo;
        return this;
    }


    @Override
    public boolean equals(java.lang.Object o) {
        if (this == o) {
            return true;
        }
        if (o == null || getClass() != o.getClass()) {
            return false;
        }
        ArticleResults other = (ArticleResults) o;
        return 
            Utils.enhancedDeepEquals(this.articles, other.articles) &&
            Utils.enhancedDeepEquals(this.paginationInfo, other.paginationInfo);
    }
    
    @Override
    public int hashCode() {
        return Utils.enhancedHash(
            articles, paginationInfo);
    }
    
    @Override
    public String toString() {
        return Utils.toString(ArticleResults.class,
                "articles", articles,
                "paginationInfo", paginationInfo);
    }

    @SuppressWarnings("UnusedReturnValue")
    public final static class Builder {

        private List<ArticleResult> articles;

        private PaginationInfo paginationInfo;

        private Builder() {
          // force use of static builder() method
        }

        /**
         * Article details
         */
        public Builder articles(@Nullable List<ArticleResult> articles) {
            this.articles = articles;
            return this;
        }

        public Builder paginationInfo(@Nullable PaginationInfo paginationInfo) {
            this.paginationInfo = paginationInfo;
            return this;
        }

        public ArticleResults build() {
            return new ArticleResults(
                articles, paginationInfo);
        }

    }
}
