/* 
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */
package com.egain.sdk.models.components;

import com.fasterxml.jackson.annotation.JsonValue;
import java.lang.String;
import java.util.Objects;
import java.util.Optional;

/**
 * AttachmentContentType
 * 
 * <p>The type of attachment.
 */
public enum AttachmentContentType {
    INTERNAL("INTERNAL"),
    EXTERNAL("EXTERNAL");

    @JsonValue
    private final String value;

    AttachmentContentType(String value) {
        this.value = value;
    }
    
    public String value() {
        return value;
    }
    
    public static Optional<AttachmentContentType> fromValue(String value) {
        for (AttachmentContentType o: AttachmentContentType.values()) {
            if (Objects.deepEquals(o.value, value)) {
                return Optional.of(o);
            }
        }
        return Optional.empty();
    }
}

