/* 
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */
package com.egain.sdk.models.components;

import com.egain.sdk.utils.Utils;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonProperty;
import jakarta.annotation.Nonnull;
import java.lang.Override;
import java.lang.String;
import java.util.Optional;


public class AttachmentUpload {
    /**
     * The name of the attachment.
     */
    @JsonProperty("name")
    private String name;

    /**
     * The size of the attachment in bytes. The maximum size is limited to 25MB.
     */
    @JsonProperty("size")
    private long size;

    @JsonCreator
    public AttachmentUpload(
            @JsonProperty("name") @Nonnull String name,
            @JsonProperty("size") long size) {
        this.name = Optional.ofNullable(name)
            .orElseThrow(() -> new IllegalArgumentException("name cannot be null"));
        this.size = size;
    }

    /**
     * The name of the attachment.
     */
    public String name() {
        return this.name;
    }

    /**
     * The size of the attachment in bytes. The maximum size is limited to 25MB.
     */
    public long size() {
        return this.size;
    }

    public static Builder builder() {
        return new Builder();
    }


    /**
     * The name of the attachment.
     */
    public AttachmentUpload withName(@Nonnull String name) {
        this.name = Utils.checkNotNull(name, "name");
        return this;
    }


    /**
     * The size of the attachment in bytes. The maximum size is limited to 25MB.
     */
    public AttachmentUpload withSize(long size) {
        this.size = size;
        return this;
    }


    @Override
    public boolean equals(java.lang.Object o) {
        if (this == o) {
            return true;
        }
        if (o == null || getClass() != o.getClass()) {
            return false;
        }
        AttachmentUpload other = (AttachmentUpload) o;
        return 
            Utils.enhancedDeepEquals(this.name, other.name) &&
            Utils.enhancedDeepEquals(this.size, other.size);
    }
    
    @Override
    public int hashCode() {
        return Utils.enhancedHash(
            name, size);
    }
    
    @Override
    public String toString() {
        return Utils.toString(AttachmentUpload.class,
                "name", name,
                "size", size);
    }

    @SuppressWarnings("UnusedReturnValue")
    public final static class Builder {

        private String name;

        private long size;

        private Builder() {
          // force use of static builder() method
        }

        /**
         * The name of the attachment.
         */
        public Builder name(@Nonnull String name) {
            this.name = Utils.checkNotNull(name, "name");
            return this;
        }

        /**
         * The size of the attachment in bytes. The maximum size is limited to 25MB.
         */
        public Builder size(long size) {
            this.size = size;
            return this;
        }

        public AttachmentUpload build() {
            return new AttachmentUpload(
                name, size);
        }

    }
}
