/* 
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */
package com.egain.sdk.models.components;

import com.egain.sdk.utils.Utils;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonInclude.Include;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import jakarta.annotation.Nullable;
import java.lang.Integer;
import java.lang.Override;
import java.lang.String;
import java.util.List;
import java.util.Optional;

/**
 * Comments
 * 
 * <p>This schema contains the definition of an array of comments.
 */
public class Comments {
    /**
     * The number of comments.
     */
    @JsonInclude(Include.NON_ABSENT)
    @JsonProperty("count")
    private Integer count;

    /**
     * The list of comments.
     */
    @JsonInclude(Include.NON_ABSENT)
    @JsonProperty("comments")
    private List<Comment> comments;

    @JsonCreator
    public Comments(
            @JsonProperty("count") @Nullable Integer count,
            @JsonProperty("comments") @Nullable List<Comment> comments) {
        this.count = count;
        this.comments = comments;
    }
    
    public Comments() {
        this(null, null);
    }

    /**
     * The number of comments.
     */
    public Optional<Integer> count() {
        return Optional.ofNullable(this.count);
    }

    /**
     * The list of comments.
     */
    public Optional<List<Comment>> comments() {
        return Optional.ofNullable(this.comments);
    }

    public static Builder builder() {
        return new Builder();
    }


    /**
     * The number of comments.
     */
    public Comments withCount(@Nullable Integer count) {
        this.count = count;
        return this;
    }


    /**
     * The list of comments.
     */
    public Comments withComments(@Nullable List<Comment> comments) {
        this.comments = comments;
        return this;
    }


    @Override
    public boolean equals(java.lang.Object o) {
        if (this == o) {
            return true;
        }
        if (o == null || getClass() != o.getClass()) {
            return false;
        }
        Comments other = (Comments) o;
        return 
            Utils.enhancedDeepEquals(this.count, other.count) &&
            Utils.enhancedDeepEquals(this.comments, other.comments);
    }
    
    @Override
    public int hashCode() {
        return Utils.enhancedHash(
            count, comments);
    }
    
    @Override
    public String toString() {
        return Utils.toString(Comments.class,
                "count", count,
                "comments", comments);
    }

    @SuppressWarnings("UnusedReturnValue")
    public final static class Builder {

        private Integer count;

        private List<Comment> comments;

        private Builder() {
          // force use of static builder() method
        }

        /**
         * The number of comments.
         */
        public Builder count(@Nullable Integer count) {
            this.count = count;
            return this;
        }

        /**
         * The list of comments.
         */
        public Builder comments(@Nullable List<Comment> comments) {
            this.comments = comments;
            return this;
        }

        public Comments build() {
            return new Comments(
                count, comments);
        }

    }
}
