/* 
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */
package com.egain.sdk.models.components;

import com.egain.sdk.utils.Utils;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonInclude.Include;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import jakarta.annotation.Nullable;
import java.lang.Override;
import java.lang.String;
import java.util.Optional;

/**
 * ComplianceForArticle
 * 
 * <p>This schema contains the compliance details for an Article.
 */
public class ComplianceForArticle {
    /**
     * The start date for the Article.
     */
    @JsonInclude(Include.NON_ABSENT)
    @JsonProperty("startDate")
    private StartDateDateAndTime startDate;

    /**
     * The end date for the Article.
     */
    @JsonInclude(Include.NON_ABSENT)
    @JsonProperty("dueDate")
    private DueDateDateAndTime dueDate;

    @JsonCreator
    public ComplianceForArticle(
            @JsonProperty("startDate") @Nullable StartDateDateAndTime startDate,
            @JsonProperty("dueDate") @Nullable DueDateDateAndTime dueDate) {
        this.startDate = startDate;
        this.dueDate = dueDate;
    }
    
    public ComplianceForArticle() {
        this(null, null);
    }

    /**
     * The start date for the Article.
     */
    public Optional<StartDateDateAndTime> startDate() {
        return Optional.ofNullable(this.startDate);
    }

    /**
     * The end date for the Article.
     */
    public Optional<DueDateDateAndTime> dueDate() {
        return Optional.ofNullable(this.dueDate);
    }

    public static Builder builder() {
        return new Builder();
    }


    /**
     * The start date for the Article.
     */
    public ComplianceForArticle withStartDate(@Nullable StartDateDateAndTime startDate) {
        this.startDate = startDate;
        return this;
    }


    /**
     * The end date for the Article.
     */
    public ComplianceForArticle withDueDate(@Nullable DueDateDateAndTime dueDate) {
        this.dueDate = dueDate;
        return this;
    }


    @Override
    public boolean equals(java.lang.Object o) {
        if (this == o) {
            return true;
        }
        if (o == null || getClass() != o.getClass()) {
            return false;
        }
        ComplianceForArticle other = (ComplianceForArticle) o;
        return 
            Utils.enhancedDeepEquals(this.startDate, other.startDate) &&
            Utils.enhancedDeepEquals(this.dueDate, other.dueDate);
    }
    
    @Override
    public int hashCode() {
        return Utils.enhancedHash(
            startDate, dueDate);
    }
    
    @Override
    public String toString() {
        return Utils.toString(ComplianceForArticle.class,
                "startDate", startDate,
                "dueDate", dueDate);
    }

    @SuppressWarnings("UnusedReturnValue")
    public final static class Builder {

        private StartDateDateAndTime startDate;

        private DueDateDateAndTime dueDate;

        private Builder() {
          // force use of static builder() method
        }

        /**
         * The start date for the Article.
         */
        public Builder startDate(@Nullable StartDateDateAndTime startDate) {
            this.startDate = startDate;
            return this;
        }

        /**
         * The end date for the Article.
         */
        public Builder dueDate(@Nullable DueDateDateAndTime dueDate) {
            this.dueDate = dueDate;
            return this;
        }

        public ComplianceForArticle build() {
            return new ComplianceForArticle(
                startDate, dueDate);
        }

    }
}
