/* 
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */
package com.egain.sdk.models.components;

import com.egain.sdk.utils.Utils;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonProperty;
import jakarta.annotation.Nonnull;
import java.lang.Override;
import java.lang.String;
import java.util.Optional;


public class CreateSearchResultEventForConnectors {
    /**
     * A short language code. A list of codes can be found below:
     * 
     * <p>|Code|Description
     * |----|-----------
     * |en-US|English (United States)
     * |en-GB|English (United Kingdom)
     * |fr-FR|French (France)
     * |es-ES|Spanish (Spain)
     * |it-IT|Italian (Italy)
     * |de-DE|German (Germany)
     * |nl-NL|Dutch (Netherlands)
     * |pt-BR|Portuguese (Brazil)
     * |pt-PT|Portuguese (Portugal)
     * |da-DK|Danish (Denmark)
     * |sv-SE|Swedish (Sweden)
     * |ru-RU|Russian (Russia)
     * |fr-CA|French (Canada)
     * |zh-CN|Chinese (Simplified, China)
     * |ja-JP|Japanese (Japan)
     * |ko-KR|Korean (South Korea)
     * |nn-NO|Norwegian Nynorsk (Norway)
     */
    @JsonProperty("languageCode")
    private KbLanguageCode languageCode;

    /**
     * The string to use for the search.
     */
    @JsonProperty("q")
    private String q;


    @JsonProperty("numberOfSearchResults")
    private int numberOfSearchResults;

    @JsonCreator
    public CreateSearchResultEventForConnectors(
            @JsonProperty("languageCode") @Nonnull KbLanguageCode languageCode,
            @JsonProperty("q") @Nonnull String q,
            @JsonProperty("numberOfSearchResults") int numberOfSearchResults) {
        this.languageCode = Optional.ofNullable(languageCode)
            .orElseThrow(() -> new IllegalArgumentException("languageCode cannot be null"));
        this.q = Optional.ofNullable(q)
            .orElseThrow(() -> new IllegalArgumentException("q cannot be null"));
        this.numberOfSearchResults = numberOfSearchResults;
    }

    /**
     * A short language code. A list of codes can be found below:
     * 
     * <p>|Code|Description
     * |----|-----------
     * |en-US|English (United States)
     * |en-GB|English (United Kingdom)
     * |fr-FR|French (France)
     * |es-ES|Spanish (Spain)
     * |it-IT|Italian (Italy)
     * |de-DE|German (Germany)
     * |nl-NL|Dutch (Netherlands)
     * |pt-BR|Portuguese (Brazil)
     * |pt-PT|Portuguese (Portugal)
     * |da-DK|Danish (Denmark)
     * |sv-SE|Swedish (Sweden)
     * |ru-RU|Russian (Russia)
     * |fr-CA|French (Canada)
     * |zh-CN|Chinese (Simplified, China)
     * |ja-JP|Japanese (Japan)
     * |ko-KR|Korean (South Korea)
     * |nn-NO|Norwegian Nynorsk (Norway)
     */
    public KbLanguageCode languageCode() {
        return this.languageCode;
    }

    /**
     * The string to use for the search.
     */
    public String q() {
        return this.q;
    }

    public int numberOfSearchResults() {
        return this.numberOfSearchResults;
    }

    public static Builder builder() {
        return new Builder();
    }


    /**
     * A short language code. A list of codes can be found below:
     * 
     * <p>|Code|Description
     * |----|-----------
     * |en-US|English (United States)
     * |en-GB|English (United Kingdom)
     * |fr-FR|French (France)
     * |es-ES|Spanish (Spain)
     * |it-IT|Italian (Italy)
     * |de-DE|German (Germany)
     * |nl-NL|Dutch (Netherlands)
     * |pt-BR|Portuguese (Brazil)
     * |pt-PT|Portuguese (Portugal)
     * |da-DK|Danish (Denmark)
     * |sv-SE|Swedish (Sweden)
     * |ru-RU|Russian (Russia)
     * |fr-CA|French (Canada)
     * |zh-CN|Chinese (Simplified, China)
     * |ja-JP|Japanese (Japan)
     * |ko-KR|Korean (South Korea)
     * |nn-NO|Norwegian Nynorsk (Norway)
     */
    public CreateSearchResultEventForConnectors withLanguageCode(@Nonnull KbLanguageCode languageCode) {
        this.languageCode = Utils.checkNotNull(languageCode, "languageCode");
        return this;
    }


    /**
     * The string to use for the search.
     */
    public CreateSearchResultEventForConnectors withQ(@Nonnull String q) {
        this.q = Utils.checkNotNull(q, "q");
        return this;
    }


    public CreateSearchResultEventForConnectors withNumberOfSearchResults(int numberOfSearchResults) {
        this.numberOfSearchResults = numberOfSearchResults;
        return this;
    }


    @Override
    public boolean equals(java.lang.Object o) {
        if (this == o) {
            return true;
        }
        if (o == null || getClass() != o.getClass()) {
            return false;
        }
        CreateSearchResultEventForConnectors other = (CreateSearchResultEventForConnectors) o;
        return 
            Utils.enhancedDeepEquals(this.languageCode, other.languageCode) &&
            Utils.enhancedDeepEquals(this.q, other.q) &&
            Utils.enhancedDeepEquals(this.numberOfSearchResults, other.numberOfSearchResults);
    }
    
    @Override
    public int hashCode() {
        return Utils.enhancedHash(
            languageCode, q, numberOfSearchResults);
    }
    
    @Override
    public String toString() {
        return Utils.toString(CreateSearchResultEventForConnectors.class,
                "languageCode", languageCode,
                "q", q,
                "numberOfSearchResults", numberOfSearchResults);
    }

    @SuppressWarnings("UnusedReturnValue")
    public final static class Builder {

        private KbLanguageCode languageCode;

        private String q;

        private int numberOfSearchResults;

        private Builder() {
          // force use of static builder() method
        }

        /**
         * A short language code. A list of codes can be found below:
         * 
         * <p>|Code|Description
         * |----|-----------
         * |en-US|English (United States)
         * |en-GB|English (United Kingdom)
         * |fr-FR|French (France)
         * |es-ES|Spanish (Spain)
         * |it-IT|Italian (Italy)
         * |de-DE|German (Germany)
         * |nl-NL|Dutch (Netherlands)
         * |pt-BR|Portuguese (Brazil)
         * |pt-PT|Portuguese (Portugal)
         * |da-DK|Danish (Denmark)
         * |sv-SE|Swedish (Sweden)
         * |ru-RU|Russian (Russia)
         * |fr-CA|French (Canada)
         * |zh-CN|Chinese (Simplified, China)
         * |ja-JP|Japanese (Japan)
         * |ko-KR|Korean (South Korea)
         * |nn-NO|Norwegian Nynorsk (Norway)
         */
        public Builder languageCode(@Nonnull KbLanguageCode languageCode) {
            this.languageCode = Utils.checkNotNull(languageCode, "languageCode");
            return this;
        }

        /**
         * The string to use for the search.
         */
        public Builder q(@Nonnull String q) {
            this.q = Utils.checkNotNull(q, "q");
            return this;
        }

        public Builder numberOfSearchResults(int numberOfSearchResults) {
            this.numberOfSearchResults = numberOfSearchResults;
            return this;
        }

        public CreateSearchResultEventForConnectors build() {
            return new CreateSearchResultEventForConnectors(
                languageCode, q, numberOfSearchResults);
        }

    }
}
