/* 
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */
package com.egain.sdk.models.components;

import com.egain.sdk.utils.Utils;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonInclude.Include;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import jakarta.annotation.Nonnull;
import jakarta.annotation.Nullable;
import java.lang.Override;
import java.lang.String;
import java.util.List;
import java.util.Optional;

/**
 * CreateSuggestion
 * 
 * <p>This schema contains information about a Suggestion.
 */
public class CreateSuggestion {
    /**
     * The name of the Suggestion.
     */
    @JsonProperty("name")
    private String name;

    /**
     * The description of the Suggestion.
     */
    @JsonInclude(Include.NON_ABSENT)
    @JsonProperty("description")
    private String description;

    /**
     * The content of the Suggestion.
     */
    @JsonProperty("content")
    private String content;

    /**
     * The Article that the Suggestion was created for.
     */
    @JsonInclude(Include.NON_ABSENT)
    @JsonProperty("feedbackArticle")
    private RelatedArticleForCreateUpdateDeleteSuggestion feedbackArticle;

    /**
     * Details of Attachments for the Suggestion.
     */
    @JsonInclude(Include.NON_ABSENT)
    @JsonProperty("attachments")
    private CreateSuggestionAttachments attachments;

    /**
     * The knowledge base language in which the Suggestion is created.
     */
    @JsonProperty("language")
    private CreateSuggestionLanguage language;

    /**
     * The Custom Attributes of the Suggestion.
     */
    @JsonInclude(Include.NON_ABSENT)
    @JsonProperty("customAttributes")
    private List<CustomAttribute> customAttributes;

    @JsonCreator
    public CreateSuggestion(
            @JsonProperty("name") @Nonnull String name,
            @JsonProperty("description") @Nullable String description,
            @JsonProperty("content") @Nonnull String content,
            @JsonProperty("feedbackArticle") @Nullable RelatedArticleForCreateUpdateDeleteSuggestion feedbackArticle,
            @JsonProperty("attachments") @Nullable CreateSuggestionAttachments attachments,
            @JsonProperty("language") @Nonnull CreateSuggestionLanguage language,
            @JsonProperty("customAttributes") @Nullable List<CustomAttribute> customAttributes) {
        this.name = Optional.ofNullable(name)
            .orElseThrow(() -> new IllegalArgumentException("name cannot be null"));
        this.description = description;
        this.content = Optional.ofNullable(content)
            .orElseThrow(() -> new IllegalArgumentException("content cannot be null"));
        this.feedbackArticle = feedbackArticle;
        this.attachments = attachments;
        this.language = Optional.ofNullable(language)
            .orElseThrow(() -> new IllegalArgumentException("language cannot be null"));
        this.customAttributes = customAttributes;
    }
    
    public CreateSuggestion(
            @Nonnull String name,
            @Nonnull String content,
            @Nonnull CreateSuggestionLanguage language) {
        this(name, null, content,
            null, null, language,
            null);
    }

    /**
     * The name of the Suggestion.
     */
    public String name() {
        return this.name;
    }

    /**
     * The description of the Suggestion.
     */
    public Optional<String> description() {
        return Optional.ofNullable(this.description);
    }

    /**
     * The content of the Suggestion.
     */
    public String content() {
        return this.content;
    }

    /**
     * The Article that the Suggestion was created for.
     */
    public Optional<RelatedArticleForCreateUpdateDeleteSuggestion> feedbackArticle() {
        return Optional.ofNullable(this.feedbackArticle);
    }

    /**
     * Details of Attachments for the Suggestion.
     */
    public Optional<CreateSuggestionAttachments> attachments() {
        return Optional.ofNullable(this.attachments);
    }

    /**
     * The knowledge base language in which the Suggestion is created.
     */
    public CreateSuggestionLanguage language() {
        return this.language;
    }

    /**
     * The Custom Attributes of the Suggestion.
     */
    public Optional<List<CustomAttribute>> customAttributes() {
        return Optional.ofNullable(this.customAttributes);
    }

    public static Builder builder() {
        return new Builder();
    }


    /**
     * The name of the Suggestion.
     */
    public CreateSuggestion withName(@Nonnull String name) {
        this.name = Utils.checkNotNull(name, "name");
        return this;
    }


    /**
     * The description of the Suggestion.
     */
    public CreateSuggestion withDescription(@Nullable String description) {
        this.description = description;
        return this;
    }


    /**
     * The content of the Suggestion.
     */
    public CreateSuggestion withContent(@Nonnull String content) {
        this.content = Utils.checkNotNull(content, "content");
        return this;
    }


    /**
     * The Article that the Suggestion was created for.
     */
    public CreateSuggestion withFeedbackArticle(@Nullable RelatedArticleForCreateUpdateDeleteSuggestion feedbackArticle) {
        this.feedbackArticle = feedbackArticle;
        return this;
    }


    /**
     * Details of Attachments for the Suggestion.
     */
    public CreateSuggestion withAttachments(@Nullable CreateSuggestionAttachments attachments) {
        this.attachments = attachments;
        return this;
    }


    /**
     * The knowledge base language in which the Suggestion is created.
     */
    public CreateSuggestion withLanguage(@Nonnull CreateSuggestionLanguage language) {
        this.language = Utils.checkNotNull(language, "language");
        return this;
    }


    /**
     * The Custom Attributes of the Suggestion.
     */
    public CreateSuggestion withCustomAttributes(@Nullable List<CustomAttribute> customAttributes) {
        this.customAttributes = customAttributes;
        return this;
    }


    @Override
    public boolean equals(java.lang.Object o) {
        if (this == o) {
            return true;
        }
        if (o == null || getClass() != o.getClass()) {
            return false;
        }
        CreateSuggestion other = (CreateSuggestion) o;
        return 
            Utils.enhancedDeepEquals(this.name, other.name) &&
            Utils.enhancedDeepEquals(this.description, other.description) &&
            Utils.enhancedDeepEquals(this.content, other.content) &&
            Utils.enhancedDeepEquals(this.feedbackArticle, other.feedbackArticle) &&
            Utils.enhancedDeepEquals(this.attachments, other.attachments) &&
            Utils.enhancedDeepEquals(this.language, other.language) &&
            Utils.enhancedDeepEquals(this.customAttributes, other.customAttributes);
    }
    
    @Override
    public int hashCode() {
        return Utils.enhancedHash(
            name, description, content,
            feedbackArticle, attachments, language,
            customAttributes);
    }
    
    @Override
    public String toString() {
        return Utils.toString(CreateSuggestion.class,
                "name", name,
                "description", description,
                "content", content,
                "feedbackArticle", feedbackArticle,
                "attachments", attachments,
                "language", language,
                "customAttributes", customAttributes);
    }

    @SuppressWarnings("UnusedReturnValue")
    public final static class Builder {

        private String name;

        private String description;

        private String content;

        private RelatedArticleForCreateUpdateDeleteSuggestion feedbackArticle;

        private CreateSuggestionAttachments attachments;

        private CreateSuggestionLanguage language;

        private List<CustomAttribute> customAttributes;

        private Builder() {
          // force use of static builder() method
        }

        /**
         * The name of the Suggestion.
         */
        public Builder name(@Nonnull String name) {
            this.name = Utils.checkNotNull(name, "name");
            return this;
        }

        /**
         * The description of the Suggestion.
         */
        public Builder description(@Nullable String description) {
            this.description = description;
            return this;
        }

        /**
         * The content of the Suggestion.
         */
        public Builder content(@Nonnull String content) {
            this.content = Utils.checkNotNull(content, "content");
            return this;
        }

        /**
         * The Article that the Suggestion was created for.
         */
        public Builder feedbackArticle(@Nullable RelatedArticleForCreateUpdateDeleteSuggestion feedbackArticle) {
            this.feedbackArticle = feedbackArticle;
            return this;
        }

        /**
         * Details of Attachments for the Suggestion.
         */
        public Builder attachments(@Nullable CreateSuggestionAttachments attachments) {
            this.attachments = attachments;
            return this;
        }

        /**
         * The knowledge base language in which the Suggestion is created.
         */
        public Builder language(@Nonnull CreateSuggestionLanguage language) {
            this.language = Utils.checkNotNull(language, "language");
            return this;
        }

        /**
         * The Custom Attributes of the Suggestion.
         */
        public Builder customAttributes(@Nullable List<CustomAttribute> customAttributes) {
            this.customAttributes = customAttributes;
            return this;
        }

        public CreateSuggestion build() {
            return new CreateSuggestion(
                name, description, content,
                feedbackArticle, attachments, language,
                customAttributes);
        }

    }
}
