/* 
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */
package com.egain.sdk.models.components;

import com.egain.sdk.utils.Utils;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonInclude.Include;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import jakarta.annotation.Nullable;
import java.lang.Override;
import java.lang.String;
import java.util.Optional;

/**
 * CreateComment
 * 
 * <p>This schema contains the definition for comment creation.
 */
public class CreateComment {
    /**
     * Content of the Comment
     */
    @JsonInclude(Include.NON_ABSENT)
    @JsonProperty("content")
    private String content;

    @JsonCreator
    public CreateComment(
            @JsonProperty("content") @Nullable String content) {
        this.content = content;
    }
    
    public CreateComment() {
        this(null);
    }

    /**
     * Content of the Comment
     */
    public Optional<String> content() {
        return Optional.ofNullable(this.content);
    }

    public static Builder builder() {
        return new Builder();
    }


    /**
     * Content of the Comment
     */
    public CreateComment withContent(@Nullable String content) {
        this.content = content;
        return this;
    }


    @Override
    public boolean equals(java.lang.Object o) {
        if (this == o) {
            return true;
        }
        if (o == null || getClass() != o.getClass()) {
            return false;
        }
        CreateComment other = (CreateComment) o;
        return 
            Utils.enhancedDeepEquals(this.content, other.content);
    }
    
    @Override
    public int hashCode() {
        return Utils.enhancedHash(
            content);
    }
    
    @Override
    public String toString() {
        return Utils.toString(CreateComment.class,
                "content", content);
    }

    @SuppressWarnings("UnusedReturnValue")
    public final static class Builder {

        private String content;

        private Builder() {
          // force use of static builder() method
        }

        /**
         * Content of the Comment
         */
        public Builder content(@Nullable String content) {
            this.content = content;
            return this;
        }

        public CreateComment build() {
            return new CreateComment(
                content);
        }

    }
}
