/* 
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */
package com.egain.sdk.models.components;

import com.egain.sdk.utils.Utils;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonInclude.Include;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import jakarta.annotation.Nullable;
import java.lang.Integer;
import java.lang.Override;
import java.lang.String;
import java.util.Optional;


public class CreateBookmark {
    /**
     * The ID of the article or topic associated with this bookmark. A case ID or an article ID is composed
     * of a 2-4 letter prefix, followed by a dash and 15 digits.<br><br>This attribute must be provided if
     * <code>resourceType</code> is set to "1 - Article" or "2 - Topic".
     */
    @JsonInclude(Include.NON_ABSENT)
    @JsonProperty("resourceId")
    private String resourceId;

    /**
     * The ID of the user associated with the bookmark.
     */
    @JsonInclude(Include.NON_ABSENT)
    @JsonProperty("userId")
    private String userId;

    /**
     * The type of the user associated with the bookmark.
     */
    @JsonInclude(Include.NON_ABSENT)
    @JsonProperty("userType")
    private UserType userType;

    /**
     * The name of the bookmark.
     */
    @JsonInclude(Include.NON_ABSENT)
    @JsonProperty("bookmarkName")
    private String bookmarkName;

    /**
     * Determines the type of resource:
     * <li>1 - Article</li>
     * <li>2 - Topic</li>
     * <li>3 - External Content</li>
     */
    @JsonInclude(Include.NON_ABSENT)
    @JsonProperty("resourceType")
    private Integer resourceType;

    /**
     * The name of the resource associated with the bookmark.<br><br>This attribute is only available for
     * article and topic bookmarks.
     */
    @JsonInclude(Include.NON_ABSENT)
    @JsonProperty("resourceName")
    private String resourceName;

    /**
     * The ID of the external content.<br><br>This attribute must be provided if <code>resourceType</code>
     * is set to "3 - External Content".
     */
    @JsonInclude(Include.NON_ABSENT)
    @JsonProperty("externalContentId")
    private String externalContentId;

    @JsonCreator
    public CreateBookmark(
            @JsonProperty("resourceId") @Nullable String resourceId,
            @JsonProperty("userId") @Nullable String userId,
            @JsonProperty("userType") @Nullable UserType userType,
            @JsonProperty("bookmarkName") @Nullable String bookmarkName,
            @JsonProperty("resourceType") @Nullable Integer resourceType,
            @JsonProperty("resourceName") @Nullable String resourceName,
            @JsonProperty("externalContentId") @Nullable String externalContentId) {
        this.resourceId = resourceId;
        this.userId = userId;
        this.userType = userType;
        this.bookmarkName = bookmarkName;
        this.resourceType = resourceType;
        this.resourceName = resourceName;
        this.externalContentId = externalContentId;
    }
    
    public CreateBookmark() {
        this(null, null, null,
            null, null, null,
            null);
    }

    /**
     * The ID of the article or topic associated with this bookmark. A case ID or an article ID is composed
     * of a 2-4 letter prefix, followed by a dash and 15 digits.<br><br>This attribute must be provided if
     * <code>resourceType</code> is set to "1 - Article" or "2 - Topic".
     */
    public Optional<String> resourceId() {
        return Optional.ofNullable(this.resourceId);
    }

    /**
     * The ID of the user associated with the bookmark.
     */
    public Optional<String> userId() {
        return Optional.ofNullable(this.userId);
    }

    /**
     * The type of the user associated with the bookmark.
     */
    public Optional<UserType> userType() {
        return Optional.ofNullable(this.userType);
    }

    /**
     * The name of the bookmark.
     */
    public Optional<String> bookmarkName() {
        return Optional.ofNullable(this.bookmarkName);
    }

    /**
     * Determines the type of resource:
     * <li>1 - Article</li>
     * <li>2 - Topic</li>
     * <li>3 - External Content</li>
     */
    public Optional<Integer> resourceType() {
        return Optional.ofNullable(this.resourceType);
    }

    /**
     * The name of the resource associated with the bookmark.<br><br>This attribute is only available for
     * article and topic bookmarks.
     */
    public Optional<String> resourceName() {
        return Optional.ofNullable(this.resourceName);
    }

    /**
     * The ID of the external content.<br><br>This attribute must be provided if <code>resourceType</code>
     * is set to "3 - External Content".
     */
    public Optional<String> externalContentId() {
        return Optional.ofNullable(this.externalContentId);
    }

    public static Builder builder() {
        return new Builder();
    }


    /**
     * The ID of the article or topic associated with this bookmark. A case ID or an article ID is composed
     * of a 2-4 letter prefix, followed by a dash and 15 digits.<br><br>This attribute must be provided if
     * <code>resourceType</code> is set to "1 - Article" or "2 - Topic".
     */
    public CreateBookmark withResourceId(@Nullable String resourceId) {
        this.resourceId = resourceId;
        return this;
    }


    /**
     * The ID of the user associated with the bookmark.
     */
    public CreateBookmark withUserId(@Nullable String userId) {
        this.userId = userId;
        return this;
    }


    /**
     * The type of the user associated with the bookmark.
     */
    public CreateBookmark withUserType(@Nullable UserType userType) {
        this.userType = userType;
        return this;
    }


    /**
     * The name of the bookmark.
     */
    public CreateBookmark withBookmarkName(@Nullable String bookmarkName) {
        this.bookmarkName = bookmarkName;
        return this;
    }


    /**
     * Determines the type of resource:
     * <li>1 - Article</li>
     * <li>2 - Topic</li>
     * <li>3 - External Content</li>
     */
    public CreateBookmark withResourceType(@Nullable Integer resourceType) {
        this.resourceType = resourceType;
        return this;
    }


    /**
     * The name of the resource associated with the bookmark.<br><br>This attribute is only available for
     * article and topic bookmarks.
     */
    public CreateBookmark withResourceName(@Nullable String resourceName) {
        this.resourceName = resourceName;
        return this;
    }


    /**
     * The ID of the external content.<br><br>This attribute must be provided if <code>resourceType</code>
     * is set to "3 - External Content".
     */
    public CreateBookmark withExternalContentId(@Nullable String externalContentId) {
        this.externalContentId = externalContentId;
        return this;
    }


    @Override
    public boolean equals(java.lang.Object o) {
        if (this == o) {
            return true;
        }
        if (o == null || getClass() != o.getClass()) {
            return false;
        }
        CreateBookmark other = (CreateBookmark) o;
        return 
            Utils.enhancedDeepEquals(this.resourceId, other.resourceId) &&
            Utils.enhancedDeepEquals(this.userId, other.userId) &&
            Utils.enhancedDeepEquals(this.userType, other.userType) &&
            Utils.enhancedDeepEquals(this.bookmarkName, other.bookmarkName) &&
            Utils.enhancedDeepEquals(this.resourceType, other.resourceType) &&
            Utils.enhancedDeepEquals(this.resourceName, other.resourceName) &&
            Utils.enhancedDeepEquals(this.externalContentId, other.externalContentId);
    }
    
    @Override
    public int hashCode() {
        return Utils.enhancedHash(
            resourceId, userId, userType,
            bookmarkName, resourceType, resourceName,
            externalContentId);
    }
    
    @Override
    public String toString() {
        return Utils.toString(CreateBookmark.class,
                "resourceId", resourceId,
                "userId", userId,
                "userType", userType,
                "bookmarkName", bookmarkName,
                "resourceType", resourceType,
                "resourceName", resourceName,
                "externalContentId", externalContentId);
    }

    @SuppressWarnings("UnusedReturnValue")
    public final static class Builder {

        private String resourceId;

        private String userId;

        private UserType userType;

        private String bookmarkName;

        private Integer resourceType;

        private String resourceName;

        private String externalContentId;

        private Builder() {
          // force use of static builder() method
        }

        /**
         * The ID of the article or topic associated with this bookmark. A case ID or an article ID is composed
         * of a 2-4 letter prefix, followed by a dash and 15 digits.<br><br>This attribute must be provided if
         * <code>resourceType</code> is set to "1 - Article" or "2 - Topic".
         */
        public Builder resourceId(@Nullable String resourceId) {
            this.resourceId = resourceId;
            return this;
        }

        /**
         * The ID of the user associated with the bookmark.
         */
        public Builder userId(@Nullable String userId) {
            this.userId = userId;
            return this;
        }

        /**
         * The type of the user associated with the bookmark.
         */
        public Builder userType(@Nullable UserType userType) {
            this.userType = userType;
            return this;
        }

        /**
         * The name of the bookmark.
         */
        public Builder bookmarkName(@Nullable String bookmarkName) {
            this.bookmarkName = bookmarkName;
            return this;
        }

        /**
         * Determines the type of resource:
         * <li>1 - Article</li>
         * <li>2 - Topic</li>
         * <li>3 - External Content</li>
         */
        public Builder resourceType(@Nullable Integer resourceType) {
            this.resourceType = resourceType;
            return this;
        }

        /**
         * The name of the resource associated with the bookmark.<br><br>This attribute is only available for
         * article and topic bookmarks.
         */
        public Builder resourceName(@Nullable String resourceName) {
            this.resourceName = resourceName;
            return this;
        }

        /**
         * The ID of the external content.<br><br>This attribute must be provided if <code>resourceType</code>
         * is set to "3 - External Content".
         */
        public Builder externalContentId(@Nullable String externalContentId) {
            this.externalContentId = externalContentId;
            return this;
        }

        public CreateBookmark build() {
            return new CreateBookmark(
                resourceId, userId, userType,
                bookmarkName, resourceType, resourceName,
                externalContentId);
        }

    }
}
