/* 
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */
package com.egain.sdk.models.components;

import com.fasterxml.jackson.annotation.JsonValue;
import java.lang.String;
import java.util.Objects;
import java.util.Optional;

/**
 * DestinationType
 * 
 * <p>Type of data destination
 */
public enum DestinationType {
    AWSS3_BUCKET("AWS S3 bucket"),
    SHARED_FILE_PATH("Shared file path");

    @JsonValue
    private final String value;

    DestinationType(String value) {
        this.value = value;
    }
    
    public String value() {
        return value;
    }
    
    public static Optional<DestinationType> fromValue(String value) {
        for (DestinationType o: DestinationType.values()) {
            if (Objects.deepEquals(o.value, value)) {
                return Optional.of(o);
            }
        }
        return Optional.empty();
    }
}

