/* 
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */
package com.egain.sdk.models.components;

import com.egain.sdk.utils.Utils;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonInclude.Include;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import jakarta.annotation.Nullable;
import java.lang.Object;
import java.lang.Override;
import java.lang.String;
import java.util.Optional;


public class DisplayField {
    /**
     * The ID of the Display Field.<br>The ID is composed of a 2-4 letter prefix, followed by a dash and
     * 4-15 digits.
     */
    @JsonInclude(Include.NON_ABSENT)
    @JsonProperty("id")
    private String id;

    /**
     * content in bytes. 2 MB max
     */
    @JsonInclude(Include.NON_ABSENT)
    @JsonProperty("content")
    private String content;

    /**
     * name of the field
     */
    @JsonInclude(Include.NON_ABSENT)
    @JsonProperty("fieldName")
    private Object fieldName;

    @JsonCreator
    public DisplayField(
            @JsonProperty("id") @Nullable String id,
            @JsonProperty("content") @Nullable String content,
            @JsonProperty("fieldName") @Nullable Object fieldName) {
        this.id = id;
        this.content = content;
        this.fieldName = fieldName;
    }
    
    public DisplayField() {
        this(null, null, null);
    }

    /**
     * The ID of the Display Field.<br>The ID is composed of a 2-4 letter prefix, followed by a dash and
     * 4-15 digits.
     */
    public Optional<String> id() {
        return Optional.ofNullable(this.id);
    }

    /**
     * content in bytes. 2 MB max
     */
    public Optional<String> content() {
        return Optional.ofNullable(this.content);
    }

    /**
     * name of the field
     */
    public Optional<Object> fieldName() {
        return Optional.ofNullable(this.fieldName);
    }

    public static Builder builder() {
        return new Builder();
    }


    /**
     * The ID of the Display Field.<br>The ID is composed of a 2-4 letter prefix, followed by a dash and
     * 4-15 digits.
     */
    public DisplayField withId(@Nullable String id) {
        this.id = id;
        return this;
    }


    /**
     * content in bytes. 2 MB max
     */
    public DisplayField withContent(@Nullable String content) {
        this.content = content;
        return this;
    }


    /**
     * name of the field
     */
    public DisplayField withFieldName(@Nullable Object fieldName) {
        this.fieldName = fieldName;
        return this;
    }


    @Override
    public boolean equals(java.lang.Object o) {
        if (this == o) {
            return true;
        }
        if (o == null || getClass() != o.getClass()) {
            return false;
        }
        DisplayField other = (DisplayField) o;
        return 
            Utils.enhancedDeepEquals(this.id, other.id) &&
            Utils.enhancedDeepEquals(this.content, other.content) &&
            Utils.enhancedDeepEquals(this.fieldName, other.fieldName);
    }
    
    @Override
    public int hashCode() {
        return Utils.enhancedHash(
            id, content, fieldName);
    }
    
    @Override
    public String toString() {
        return Utils.toString(DisplayField.class,
                "id", id,
                "content", content,
                "fieldName", fieldName);
    }

    @SuppressWarnings("UnusedReturnValue")
    public final static class Builder {

        private String id;

        private String content;

        private Object fieldName;

        private Builder() {
          // force use of static builder() method
        }

        /**
         * The ID of the Display Field.<br>The ID is composed of a 2-4 letter prefix, followed by a dash and
         * 4-15 digits.
         */
        public Builder id(@Nullable String id) {
            this.id = id;
            return this;
        }

        /**
         * content in bytes. 2 MB max
         */
        public Builder content(@Nullable String content) {
            this.content = content;
            return this;
        }

        /**
         * name of the field
         */
        public Builder fieldName(@Nullable Object fieldName) {
            this.fieldName = fieldName;
            return this;
        }

        public DisplayField build() {
            return new DisplayField(
                id, content, fieldName);
        }

    }
}
