/* 
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */
package com.egain.sdk.models.components;

import com.egain.sdk.utils.Utils;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonProperty;
import jakarta.annotation.Nonnull;
import java.lang.Override;
import java.lang.String;
import java.time.OffsetDateTime;
import java.util.Optional;

/**
 * DueDateDateAndTime
 * 
 * <p>The end date for the Article.
 */
public class DueDateDateAndTime {
    /**
     * The date in the format <code>YYYY-MM-DDTHH:MM:SS</code>.
     */
    @JsonProperty("date")
    private OffsetDateTime date;

    @JsonCreator
    public DueDateDateAndTime(
            @JsonProperty("date") @Nonnull OffsetDateTime date) {
        this.date = Optional.ofNullable(date)
            .orElseThrow(() -> new IllegalArgumentException("date cannot be null"));
    }

    /**
     * The date in the format <code>YYYY-MM-DDTHH:MM:SS</code>.
     */
    public OffsetDateTime date() {
        return this.date;
    }

    public static Builder builder() {
        return new Builder();
    }


    /**
     * The date in the format <code>YYYY-MM-DDTHH:MM:SS</code>.
     */
    public DueDateDateAndTime withDate(@Nonnull OffsetDateTime date) {
        this.date = Utils.checkNotNull(date, "date");
        return this;
    }


    @Override
    public boolean equals(java.lang.Object o) {
        if (this == o) {
            return true;
        }
        if (o == null || getClass() != o.getClass()) {
            return false;
        }
        DueDateDateAndTime other = (DueDateDateAndTime) o;
        return 
            Utils.enhancedDeepEquals(this.date, other.date);
    }
    
    @Override
    public int hashCode() {
        return Utils.enhancedHash(
            date);
    }
    
    @Override
    public String toString() {
        return Utils.toString(DueDateDateAndTime.class,
                "date", date);
    }

    @SuppressWarnings("UnusedReturnValue")
    public final static class Builder {

        private OffsetDateTime date;

        private Builder() {
          // force use of static builder() method
        }

        /**
         * The date in the format <code>YYYY-MM-DDTHH:MM:SS</code>.
         */
        public Builder date(@Nonnull OffsetDateTime date) {
            this.date = Utils.checkNotNull(date, "date");
            return this;
        }

        public DueDateDateAndTime build() {
            return new DueDateDateAndTime(
                date);
        }

    }
}
