/* 
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */
package com.egain.sdk.models.components;

import com.egain.sdk.utils.Utils;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonInclude.Include;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import jakarta.annotation.Nullable;
import java.lang.Override;
import java.lang.String;
import java.util.Optional;


public class FileObject {
    /**
     * ID of Hook File
     */
    @JsonInclude(Include.NON_ABSENT)
    @JsonProperty("fileID")
    private String fileID;

    /**
     * The date on which the resource was last modified.
     */
    @JsonInclude(Include.NON_ABSENT)
    @JsonProperty("createdDate")
    private String createdDate;


    @JsonInclude(Include.NON_ABSENT)
    @JsonProperty("createdBy")
    private CreatedBy createdBy;

    /**
     * The date on which the resource was last modified.
     */
    @JsonInclude(Include.NON_ABSENT)
    @JsonProperty("modifiedDate")
    private String modifiedDate;


    @JsonInclude(Include.NON_ABSENT)
    @JsonProperty("modifiedBy")
    private ModifiedBy modifiedBy;


    @JsonInclude(Include.NON_ABSENT)
    @JsonProperty("version")
    private Version version;


    @JsonInclude(Include.NON_ABSENT)
    @JsonProperty("file")
    private File file;

    @JsonCreator
    public FileObject(
            @JsonProperty("fileID") @Nullable String fileID,
            @JsonProperty("createdDate") @Nullable String createdDate,
            @JsonProperty("createdBy") @Nullable CreatedBy createdBy,
            @JsonProperty("modifiedDate") @Nullable String modifiedDate,
            @JsonProperty("modifiedBy") @Nullable ModifiedBy modifiedBy,
            @JsonProperty("version") @Nullable Version version,
            @JsonProperty("file") @Nullable File file) {
        this.fileID = fileID;
        this.createdDate = createdDate;
        this.createdBy = createdBy;
        this.modifiedDate = modifiedDate;
        this.modifiedBy = modifiedBy;
        this.version = version;
        this.file = file;
    }
    
    public FileObject() {
        this(null, null, null,
            null, null, null,
            null);
    }

    /**
     * ID of Hook File
     */
    public Optional<String> fileID() {
        return Optional.ofNullable(this.fileID);
    }

    /**
     * The date on which the resource was last modified.
     */
    public Optional<String> createdDate() {
        return Optional.ofNullable(this.createdDate);
    }

    public Optional<CreatedBy> createdBy() {
        return Optional.ofNullable(this.createdBy);
    }

    /**
     * The date on which the resource was last modified.
     */
    public Optional<String> modifiedDate() {
        return Optional.ofNullable(this.modifiedDate);
    }

    public Optional<ModifiedBy> modifiedBy() {
        return Optional.ofNullable(this.modifiedBy);
    }

    public Optional<Version> version() {
        return Optional.ofNullable(this.version);
    }

    public Optional<File> file() {
        return Optional.ofNullable(this.file);
    }

    public static Builder builder() {
        return new Builder();
    }


    /**
     * ID of Hook File
     */
    public FileObject withFileID(@Nullable String fileID) {
        this.fileID = fileID;
        return this;
    }


    /**
     * The date on which the resource was last modified.
     */
    public FileObject withCreatedDate(@Nullable String createdDate) {
        this.createdDate = createdDate;
        return this;
    }


    public FileObject withCreatedBy(@Nullable CreatedBy createdBy) {
        this.createdBy = createdBy;
        return this;
    }


    /**
     * The date on which the resource was last modified.
     */
    public FileObject withModifiedDate(@Nullable String modifiedDate) {
        this.modifiedDate = modifiedDate;
        return this;
    }


    public FileObject withModifiedBy(@Nullable ModifiedBy modifiedBy) {
        this.modifiedBy = modifiedBy;
        return this;
    }


    public FileObject withVersion(@Nullable Version version) {
        this.version = version;
        return this;
    }


    public FileObject withFile(@Nullable File file) {
        this.file = file;
        return this;
    }


    @Override
    public boolean equals(java.lang.Object o) {
        if (this == o) {
            return true;
        }
        if (o == null || getClass() != o.getClass()) {
            return false;
        }
        FileObject other = (FileObject) o;
        return 
            Utils.enhancedDeepEquals(this.fileID, other.fileID) &&
            Utils.enhancedDeepEquals(this.createdDate, other.createdDate) &&
            Utils.enhancedDeepEquals(this.createdBy, other.createdBy) &&
            Utils.enhancedDeepEquals(this.modifiedDate, other.modifiedDate) &&
            Utils.enhancedDeepEquals(this.modifiedBy, other.modifiedBy) &&
            Utils.enhancedDeepEquals(this.version, other.version) &&
            Utils.enhancedDeepEquals(this.file, other.file);
    }
    
    @Override
    public int hashCode() {
        return Utils.enhancedHash(
            fileID, createdDate, createdBy,
            modifiedDate, modifiedBy, version,
            file);
    }
    
    @Override
    public String toString() {
        return Utils.toString(FileObject.class,
                "fileID", fileID,
                "createdDate", createdDate,
                "createdBy", createdBy,
                "modifiedDate", modifiedDate,
                "modifiedBy", modifiedBy,
                "version", version,
                "file", file);
    }

    @SuppressWarnings("UnusedReturnValue")
    public final static class Builder {

        private String fileID;

        private String createdDate;

        private CreatedBy createdBy;

        private String modifiedDate;

        private ModifiedBy modifiedBy;

        private Version version;

        private File file;

        private Builder() {
          // force use of static builder() method
        }

        /**
         * ID of Hook File
         */
        public Builder fileID(@Nullable String fileID) {
            this.fileID = fileID;
            return this;
        }

        /**
         * The date on which the resource was last modified.
         */
        public Builder createdDate(@Nullable String createdDate) {
            this.createdDate = createdDate;
            return this;
        }

        public Builder createdBy(@Nullable CreatedBy createdBy) {
            this.createdBy = createdBy;
            return this;
        }

        /**
         * The date on which the resource was last modified.
         */
        public Builder modifiedDate(@Nullable String modifiedDate) {
            this.modifiedDate = modifiedDate;
            return this;
        }

        public Builder modifiedBy(@Nullable ModifiedBy modifiedBy) {
            this.modifiedBy = modifiedBy;
            return this;
        }

        public Builder version(@Nullable Version version) {
            this.version = version;
            return this;
        }

        public Builder file(@Nullable File file) {
            this.file = file;
            return this;
        }

        public FileObject build() {
            return new FileObject(
                fileID, createdDate, createdBy,
                modifiedDate, modifiedBy, version,
                file);
        }

    }
}
