/* 
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */
package com.egain.sdk.models.components;

import com.egain.sdk.utils.Utils;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonInclude.Include;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import jakarta.annotation.Nonnull;
import jakarta.annotation.Nullable;
import java.lang.Boolean;
import java.lang.Override;
import java.lang.String;
import java.util.List;
import java.util.Optional;


public class GHSearchRequest {
    /**
     * The numerical ID of the Casebase.
     */
    @JsonProperty("casebaseId")
    private String casebaseId;

    /**
     * Pre-answered Questions in Guided Help search
     */
    @JsonInclude(Include.NON_ABSENT)
    @JsonProperty("questions")
    private List<StartQuestionAndAnswer> questions;

    /**
     * The ID of the guided help profile.<br>
     * 1 will always be the **system profile**.
     */
    @JsonInclude(Include.NON_ABSENT)
    @JsonProperty("profileId")
    private String profileId;

    /**
     * Session variables used to give Guided Help additional context.
     */
    @JsonInclude(Include.NON_ABSENT)
    @JsonProperty("sessionVariable")
    private List<SessionContextVariable> sessionVariable;

    /**
     * Restart the current Guided Help search with the existing context along with session variable
     * context.
     */
    @JsonInclude(Include.NON_ABSENT)
    @JsonProperty("startOver")
    private Boolean startOver;

    /**
     * Use current live release snapshot of the Casebase otherwise use the authoring release.
     */
    @JsonInclude(Include.NON_ABSENT)
    @JsonProperty("useLiveRelease")
    private Boolean useLiveRelease;

    /**
     * Numeric ID of the guided help session article used for starting search.
     */
    @JsonInclude(Include.NON_ABSENT)
    @JsonProperty("ghsArticleId")
    private String ghsArticleId;

    @JsonCreator
    public GHSearchRequest(
            @JsonProperty("casebaseId") @Nonnull String casebaseId,
            @JsonProperty("questions") @Nullable List<StartQuestionAndAnswer> questions,
            @JsonProperty("profileId") @Nullable String profileId,
            @JsonProperty("sessionVariable") @Nullable List<SessionContextVariable> sessionVariable,
            @JsonProperty("startOver") @Nullable Boolean startOver,
            @JsonProperty("useLiveRelease") @Nullable Boolean useLiveRelease,
            @JsonProperty("ghsArticleId") @Nullable String ghsArticleId) {
        this.casebaseId = Optional.ofNullable(casebaseId)
            .orElseThrow(() -> new IllegalArgumentException("casebaseId cannot be null"));
        this.questions = questions;
        this.profileId = profileId;
        this.sessionVariable = sessionVariable;
        this.startOver = startOver;
        this.useLiveRelease = useLiveRelease;
        this.ghsArticleId = ghsArticleId;
    }
    
    public GHSearchRequest(
            @Nonnull String casebaseId) {
        this(casebaseId, null, null,
            null, null, null,
            null);
    }

    /**
     * The numerical ID of the Casebase.
     */
    public String casebaseId() {
        return this.casebaseId;
    }

    /**
     * Pre-answered Questions in Guided Help search
     */
    public Optional<List<StartQuestionAndAnswer>> questions() {
        return Optional.ofNullable(this.questions);
    }

    /**
     * The ID of the guided help profile.<br>
     * 1 will always be the **system profile**.
     */
    public Optional<String> profileId() {
        return Optional.ofNullable(this.profileId);
    }

    /**
     * Session variables used to give Guided Help additional context.
     */
    public Optional<List<SessionContextVariable>> sessionVariable() {
        return Optional.ofNullable(this.sessionVariable);
    }

    /**
     * Restart the current Guided Help search with the existing context along with session variable
     * context.
     */
    public Optional<Boolean> startOver() {
        return Optional.ofNullable(this.startOver);
    }

    /**
     * Use current live release snapshot of the Casebase otherwise use the authoring release.
     */
    public Optional<Boolean> useLiveRelease() {
        return Optional.ofNullable(this.useLiveRelease);
    }

    /**
     * Numeric ID of the guided help session article used for starting search.
     */
    public Optional<String> ghsArticleId() {
        return Optional.ofNullable(this.ghsArticleId);
    }

    public static Builder builder() {
        return new Builder();
    }


    /**
     * The numerical ID of the Casebase.
     */
    public GHSearchRequest withCasebaseId(@Nonnull String casebaseId) {
        this.casebaseId = Utils.checkNotNull(casebaseId, "casebaseId");
        return this;
    }


    /**
     * Pre-answered Questions in Guided Help search
     */
    public GHSearchRequest withQuestions(@Nullable List<StartQuestionAndAnswer> questions) {
        this.questions = questions;
        return this;
    }


    /**
     * The ID of the guided help profile.<br>
     * 1 will always be the **system profile**.
     */
    public GHSearchRequest withProfileId(@Nullable String profileId) {
        this.profileId = profileId;
        return this;
    }


    /**
     * Session variables used to give Guided Help additional context.
     */
    public GHSearchRequest withSessionVariable(@Nullable List<SessionContextVariable> sessionVariable) {
        this.sessionVariable = sessionVariable;
        return this;
    }


    /**
     * Restart the current Guided Help search with the existing context along with session variable
     * context.
     */
    public GHSearchRequest withStartOver(@Nullable Boolean startOver) {
        this.startOver = startOver;
        return this;
    }


    /**
     * Use current live release snapshot of the Casebase otherwise use the authoring release.
     */
    public GHSearchRequest withUseLiveRelease(@Nullable Boolean useLiveRelease) {
        this.useLiveRelease = useLiveRelease;
        return this;
    }


    /**
     * Numeric ID of the guided help session article used for starting search.
     */
    public GHSearchRequest withGhsArticleId(@Nullable String ghsArticleId) {
        this.ghsArticleId = ghsArticleId;
        return this;
    }


    @Override
    public boolean equals(java.lang.Object o) {
        if (this == o) {
            return true;
        }
        if (o == null || getClass() != o.getClass()) {
            return false;
        }
        GHSearchRequest other = (GHSearchRequest) o;
        return 
            Utils.enhancedDeepEquals(this.casebaseId, other.casebaseId) &&
            Utils.enhancedDeepEquals(this.questions, other.questions) &&
            Utils.enhancedDeepEquals(this.profileId, other.profileId) &&
            Utils.enhancedDeepEquals(this.sessionVariable, other.sessionVariable) &&
            Utils.enhancedDeepEquals(this.startOver, other.startOver) &&
            Utils.enhancedDeepEquals(this.useLiveRelease, other.useLiveRelease) &&
            Utils.enhancedDeepEquals(this.ghsArticleId, other.ghsArticleId);
    }
    
    @Override
    public int hashCode() {
        return Utils.enhancedHash(
            casebaseId, questions, profileId,
            sessionVariable, startOver, useLiveRelease,
            ghsArticleId);
    }
    
    @Override
    public String toString() {
        return Utils.toString(GHSearchRequest.class,
                "casebaseId", casebaseId,
                "questions", questions,
                "profileId", profileId,
                "sessionVariable", sessionVariable,
                "startOver", startOver,
                "useLiveRelease", useLiveRelease,
                "ghsArticleId", ghsArticleId);
    }

    @SuppressWarnings("UnusedReturnValue")
    public final static class Builder {

        private String casebaseId;

        private List<StartQuestionAndAnswer> questions;

        private String profileId;

        private List<SessionContextVariable> sessionVariable;

        private Boolean startOver;

        private Boolean useLiveRelease;

        private String ghsArticleId;

        private Builder() {
          // force use of static builder() method
        }

        /**
         * The numerical ID of the Casebase.
         */
        public Builder casebaseId(@Nonnull String casebaseId) {
            this.casebaseId = Utils.checkNotNull(casebaseId, "casebaseId");
            return this;
        }

        /**
         * Pre-answered Questions in Guided Help search
         */
        public Builder questions(@Nullable List<StartQuestionAndAnswer> questions) {
            this.questions = questions;
            return this;
        }

        /**
         * The ID of the guided help profile.<br>
         * 1 will always be the **system profile**.
         */
        public Builder profileId(@Nullable String profileId) {
            this.profileId = profileId;
            return this;
        }

        /**
         * Session variables used to give Guided Help additional context.
         */
        public Builder sessionVariable(@Nullable List<SessionContextVariable> sessionVariable) {
            this.sessionVariable = sessionVariable;
            return this;
        }

        /**
         * Restart the current Guided Help search with the existing context along with session variable
         * context.
         */
        public Builder startOver(@Nullable Boolean startOver) {
            this.startOver = startOver;
            return this;
        }

        /**
         * Use current live release snapshot of the Casebase otherwise use the authoring release.
         */
        public Builder useLiveRelease(@Nullable Boolean useLiveRelease) {
            this.useLiveRelease = useLiveRelease;
            return this;
        }

        /**
         * Numeric ID of the guided help session article used for starting search.
         */
        public Builder ghsArticleId(@Nullable String ghsArticleId) {
            this.ghsArticleId = ghsArticleId;
            return this;
        }

        public GHSearchRequest build() {
            return new GHSearchRequest(
                casebaseId, questions, profileId,
                sessionVariable, startOver, useLiveRelease,
                ghsArticleId);
        }

    }
}
