/* 
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */
package com.egain.sdk.models.components;

import com.fasterxml.jackson.annotation.JsonValue;
import java.lang.String;
import java.util.Objects;
import java.util.Optional;

/**
 * KbLanguageCode
 * 
 * <p>A short language code. A list of codes can be found below:
 * 
 * <p>|Code|Description
 * |----|-----------
 * |en-US|English (United States)
 * |en-GB|English (United Kingdom)
 * |fr-FR|French (France)
 * |es-ES|Spanish (Spain)
 * |it-IT|Italian (Italy)
 * |de-DE|German (Germany)
 * |nl-NL|Dutch (Netherlands)
 * |pt-BR|Portuguese (Brazil)
 * |pt-PT|Portuguese (Portugal)
 * |da-DK|Danish (Denmark)
 * |sv-SE|Swedish (Sweden)
 * |ru-RU|Russian (Russia)
 * |fr-CA|French (Canada)
 * |zh-CN|Chinese (Simplified, China)
 * |ja-JP|Japanese (Japan)
 * |ko-KR|Korean (South Korea)
 * |nn-NO|Norwegian Nynorsk (Norway)
 */
public enum KbLanguageCode {
    EN_US("en-US"),
    EN_GB("en-GB"),
    FRFR("fr-FR"),
    ESES("es-ES"),
    ITIT("it-IT"),
    DEDE("de-DE"),
    NLNL("nl-NL"),
    PT_BR("pt-BR"),
    PTPT("pt-PT"),
    DA_DK("da-DK"),
    SV_SE("sv-SE"),
    RURU("ru-RU"),
    FR_CA("fr-CA"),
    ZH_CN("zh-CN"),
    JA_JP("ja-JP"),
    KO_KR("ko-KR"),
    NN_NO("nn-NO");

    @JsonValue
    private final String value;

    KbLanguageCode(String value) {
        this.value = value;
    }
    
    public String value() {
        return value;
    }
    
    public static Optional<KbLanguageCode> fromValue(String value) {
        for (KbLanguageCode o: KbLanguageCode.values()) {
            if (Objects.deepEquals(o.value, value)) {
                return Optional.of(o);
            }
        }
        return Optional.empty();
    }
}

