/* 
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */
package com.egain.sdk.models.components;

import com.egain.sdk.utils.Utils;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonInclude.Include;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import jakarta.annotation.Nullable;
import java.lang.Override;
import java.lang.String;
import java.util.Optional;

/**
 * Link
 * 
 * <p>Defines the relationship between this resource and another object.
 */
public class Link {
    /**
     * Defines the relationship between a linked resource and the current object.<br><br>For example:
     * *self*, *prev*, *next* or an object name such as *'user'*, *'folder'* etc.
     */
    @JsonInclude(Include.NON_ABSENT)
    @JsonProperty("rel")
    private String rel;

    /**
     * The URL that specifies the link's destination.
     */
    @JsonInclude(Include.NON_ABSENT)
    @JsonProperty("href")
    private String href;

    @JsonCreator
    public Link(
            @JsonProperty("rel") @Nullable String rel,
            @JsonProperty("href") @Nullable String href) {
        this.rel = rel;
        this.href = href;
    }
    
    public Link() {
        this(null, null);
    }

    /**
     * Defines the relationship between a linked resource and the current object.<br><br>For example:
     * *self*, *prev*, *next* or an object name such as *'user'*, *'folder'* etc.
     */
    public Optional<String> rel() {
        return Optional.ofNullable(this.rel);
    }

    /**
     * The URL that specifies the link's destination.
     */
    public Optional<String> href() {
        return Optional.ofNullable(this.href);
    }

    public static Builder builder() {
        return new Builder();
    }


    /**
     * Defines the relationship between a linked resource and the current object.<br><br>For example:
     * *self*, *prev*, *next* or an object name such as *'user'*, *'folder'* etc.
     */
    public Link withRel(@Nullable String rel) {
        this.rel = rel;
        return this;
    }


    /**
     * The URL that specifies the link's destination.
     */
    public Link withHref(@Nullable String href) {
        this.href = href;
        return this;
    }


    @Override
    public boolean equals(java.lang.Object o) {
        if (this == o) {
            return true;
        }
        if (o == null || getClass() != o.getClass()) {
            return false;
        }
        Link other = (Link) o;
        return 
            Utils.enhancedDeepEquals(this.rel, other.rel) &&
            Utils.enhancedDeepEquals(this.href, other.href);
    }
    
    @Override
    public int hashCode() {
        return Utils.enhancedHash(
            rel, href);
    }
    
    @Override
    public String toString() {
        return Utils.toString(Link.class,
                "rel", rel,
                "href", href);
    }

    @SuppressWarnings("UnusedReturnValue")
    public final static class Builder {

        private String rel;

        private String href;

        private Builder() {
          // force use of static builder() method
        }

        /**
         * Defines the relationship between a linked resource and the current object.<br><br>For example:
         * *self*, *prev*, *next* or an object name such as *'user'*, *'folder'* etc.
         */
        public Builder rel(@Nullable String rel) {
            this.rel = rel;
            return this;
        }

        /**
         * The URL that specifies the link's destination.
         */
        public Builder href(@Nullable String href) {
            this.href = href;
            return this;
        }

        public Link build() {
            return new Link(
                rel, href);
        }

    }
}
