/* 
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */
package com.egain.sdk.models.components;

import com.fasterxml.jackson.annotation.JsonValue;
import java.lang.String;
import java.util.Objects;
import java.util.Optional;

public enum MandatoryLanguageQueryParameter {
    EN_US("en-US"),
    FRFR("fr-FR"),
    EN_GB("en-GB"),
    ESES("es-ES"),
    ITIT("it-IT"),
    NLNL("nl-NL"),
    DADA("da-DA"),
    SV_SE("sv-SE"),
    PTPT("pt-PT"),
    FIFI("fi-FI"),
    NO_NB("no-NB"),
    NO_NN("no-NN"),
    JAJA("ja-JA"),
    DEDE("de-DE"),
    PT_BR("pt-BR"),
    ZH_CN("zh-CN"),
    ZH_TW("zh-TW"),
    KOKO("ko-KO"),
    RURU("ru-RU"),
    ELEL("el-EL"),
    TRTR("tr-TR"),
    PLPL("pl-PL"),
    CSCS("cs-CS"),
    SKSK("sk-SK"),
    HUHU("hu-HU"),
    SRSR("sr-SR"),
    AR_SA("ar-SA"),
    HRHR("hr-HR"),
    RORO("ro-RO"),
    THTH("th-TH");

    @JsonValue
    private final String value;

    MandatoryLanguageQueryParameter(String value) {
        this.value = value;
    }
    
    public String value() {
        return value;
    }
    
    public static Optional<MandatoryLanguageQueryParameter> fromValue(String value) {
        for (MandatoryLanguageQueryParameter o: MandatoryLanguageQueryParameter.values()) {
            if (Objects.deepEquals(o.value, value)) {
                return Optional.of(o);
            }
        }
        return Optional.empty();
    }
}

