/* 
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */
package com.egain.sdk.models.components;

import com.fasterxml.jackson.annotation.JsonValue;
import java.lang.String;
import java.util.Objects;
import java.util.Optional;

/**
 * OptionalArticleAttributes
 * 
 * <p>The fields of the article to be returned.
 */
public enum OptionalArticleAttributes {
    ARTICLE_MACRO("articleMacro"),
    AVAILABILITY_DATE("availabilityDate"),
    AVERAGE_RATING("averageRating"),
    CONTENT_TEXT("contentText"),
    ORDER_NUMBER("orderNumber"),
    SUGGESTION_TYPE("suggestionType"),
    TIMES_RATED("timesRated"),
    AVAILABLE_EDITIONS("availableEditions"),
    ARTICLE_TYPE_ATTRIBUTES("articleTypeAttributes"),
    MILESTONE("milestone"),
    ALL("all");

    @JsonValue
    private final String value;

    OptionalArticleAttributes(String value) {
        this.value = value;
    }
    
    public String value() {
        return value;
    }
    
    public static Optional<OptionalArticleAttributes> fromValue(String value) {
        for (OptionalArticleAttributes o: OptionalArticleAttributes.values()) {
            if (Objects.deepEquals(o.value, value)) {
                return Optional.of(o);
            }
        }
        return Optional.empty();
    }
}

