/* 
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */
package com.egain.sdk.models.components;

import com.fasterxml.jackson.annotation.JsonValue;
import java.lang.String;
import java.util.Objects;
import java.util.Optional;

/**
 * QuestionFormat
 * 
 * <p>format of the question
 */
public enum QuestionFormat {
    RADIO_BUTTON("radioButton"),
    DROPDOWN("dropdown"),
    CHECKBOX("checkbox"),
    MUTLI_SELECT("mutliSelect"),
    NUMBER("number"),
    SINGLE_LINE_TEXT_FIELD("singleLineTextField"),
    MULTI_LINE_TEXT_FIELD("multiLineTextField");

    @JsonValue
    private final String value;

    QuestionFormat(String value) {
        this.value = value;
    }
    
    public String value() {
        return value;
    }
    
    public static Optional<QuestionFormat> fromValue(String value) {
        for (QuestionFormat o: QuestionFormat.values()) {
            if (Objects.deepEquals(o.value, value)) {
                return Optional.of(o);
            }
        }
        return Optional.empty();
    }
}

