/* 
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */
package com.egain.sdk.models.components;

import com.egain.sdk.utils.Utils;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonInclude.Include;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import jakarta.annotation.Nullable;
import java.lang.Override;
import java.lang.String;
import java.util.Optional;

/**
 * RelatedArticleForCreateUpdateDeleteSuggestion
 * 
 * <p>The Article that the Suggestion was created for.
 */
public class RelatedArticleForCreateUpdateDeleteSuggestion {
    /**
     * The ID of a Related Article.<br><br>An Article ID is composed of a 2-4 letter prefix, followed by a
     * dash and 4-15 digits.
     */
    @JsonInclude(Include.NON_ABSENT)
    @JsonProperty("id")
    private String id;

    @JsonCreator
    public RelatedArticleForCreateUpdateDeleteSuggestion(
            @JsonProperty("id") @Nullable String id) {
        this.id = id;
    }
    
    public RelatedArticleForCreateUpdateDeleteSuggestion() {
        this(null);
    }

    /**
     * The ID of a Related Article.<br><br>An Article ID is composed of a 2-4 letter prefix, followed by a
     * dash and 4-15 digits.
     */
    public Optional<String> id() {
        return Optional.ofNullable(this.id);
    }

    public static Builder builder() {
        return new Builder();
    }


    /**
     * The ID of a Related Article.<br><br>An Article ID is composed of a 2-4 letter prefix, followed by a
     * dash and 4-15 digits.
     */
    public RelatedArticleForCreateUpdateDeleteSuggestion withId(@Nullable String id) {
        this.id = id;
        return this;
    }


    @Override
    public boolean equals(java.lang.Object o) {
        if (this == o) {
            return true;
        }
        if (o == null || getClass() != o.getClass()) {
            return false;
        }
        RelatedArticleForCreateUpdateDeleteSuggestion other = (RelatedArticleForCreateUpdateDeleteSuggestion) o;
        return 
            Utils.enhancedDeepEquals(this.id, other.id);
    }
    
    @Override
    public int hashCode() {
        return Utils.enhancedHash(
            id);
    }
    
    @Override
    public String toString() {
        return Utils.toString(RelatedArticleForCreateUpdateDeleteSuggestion.class,
                "id", id);
    }

    @SuppressWarnings("UnusedReturnValue")
    public final static class Builder {

        private String id;

        private Builder() {
          // force use of static builder() method
        }

        /**
         * The ID of a Related Article.<br><br>An Article ID is composed of a 2-4 letter prefix, followed by a
         * dash and 4-15 digits.
         */
        public Builder id(@Nullable String id) {
            this.id = id;
            return this;
        }

        public RelatedArticleForCreateUpdateDeleteSuggestion build() {
            return new RelatedArticleForCreateUpdateDeleteSuggestion(
                id);
        }

    }
}
