/* 
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */
package com.egain.sdk.models.components;

import com.egain.sdk.utils.Utils;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonInclude.Include;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import jakarta.annotation.Nonnull;
import jakarta.annotation.Nullable;
import java.lang.Override;
import java.lang.String;
import java.util.Optional;


public class SchemasWSErrorCommonDetail {

    @JsonProperty("key")
    private String key;


    @JsonInclude(Include.NON_ABSENT)
    @JsonProperty("value")
    private String value;

    @JsonCreator
    public SchemasWSErrorCommonDetail(
            @JsonProperty("key") @Nonnull String key,
            @JsonProperty("value") @Nullable String value) {
        this.key = Optional.ofNullable(key)
            .orElseThrow(() -> new IllegalArgumentException("key cannot be null"));
        this.value = value;
    }
    
    public SchemasWSErrorCommonDetail(
            @Nonnull String key) {
        this(key, null);
    }

    public String key() {
        return this.key;
    }

    public Optional<String> value() {
        return Optional.ofNullable(this.value);
    }

    public static Builder builder() {
        return new Builder();
    }


    public SchemasWSErrorCommonDetail withKey(@Nonnull String key) {
        this.key = Utils.checkNotNull(key, "key");
        return this;
    }


    public SchemasWSErrorCommonDetail withValue(@Nullable String value) {
        this.value = value;
        return this;
    }


    @Override
    public boolean equals(java.lang.Object o) {
        if (this == o) {
            return true;
        }
        if (o == null || getClass() != o.getClass()) {
            return false;
        }
        SchemasWSErrorCommonDetail other = (SchemasWSErrorCommonDetail) o;
        return 
            Utils.enhancedDeepEquals(this.key, other.key) &&
            Utils.enhancedDeepEquals(this.value, other.value);
    }
    
    @Override
    public int hashCode() {
        return Utils.enhancedHash(
            key, value);
    }
    
    @Override
    public String toString() {
        return Utils.toString(SchemasWSErrorCommonDetail.class,
                "key", key,
                "value", value);
    }

    @SuppressWarnings("UnusedReturnValue")
    public final static class Builder {

        private String key;

        private String value;

        private Builder() {
          // force use of static builder() method
        }

        public Builder key(@Nonnull String key) {
            this.key = Utils.checkNotNull(key, "key");
            return this;
        }

        public Builder value(@Nullable String value) {
            this.value = value;
            return this;
        }

        public SchemasWSErrorCommonDetail build() {
            return new SchemasWSErrorCommonDetail(
                key, value);
        }

    }
}
