/* 
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */
package com.egain.sdk.models.components;

import com.egain.sdk.utils.Utils;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonInclude.Include;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import jakarta.annotation.Nullable;
import java.lang.Override;
import java.lang.String;
import java.util.Optional;


public class SchemasCustomAttribute {
    /**
     * The custom attribute's name.
     */
    @JsonInclude(Include.NON_ABSENT)
    @JsonProperty("name")
    private String name;

    /**
     * The custom attribute's value.
     */
    @JsonInclude(Include.NON_ABSENT)
    @JsonProperty("value")
    private String value;

    /**
     * The custom attribute's type.
     */
    @JsonInclude(Include.NON_ABSENT)
    @JsonProperty("type")
    private SchemasCustomAttributeType type;

    @JsonCreator
    public SchemasCustomAttribute(
            @JsonProperty("name") @Nullable String name,
            @JsonProperty("value") @Nullable String value,
            @JsonProperty("type") @Nullable SchemasCustomAttributeType type) {
        this.name = name;
        this.value = value;
        this.type = type;
    }
    
    public SchemasCustomAttribute() {
        this(null, null, null);
    }

    /**
     * The custom attribute's name.
     */
    public Optional<String> name() {
        return Optional.ofNullable(this.name);
    }

    /**
     * The custom attribute's value.
     */
    public Optional<String> value() {
        return Optional.ofNullable(this.value);
    }

    /**
     * The custom attribute's type.
     */
    public Optional<SchemasCustomAttributeType> type() {
        return Optional.ofNullable(this.type);
    }

    public static Builder builder() {
        return new Builder();
    }


    /**
     * The custom attribute's name.
     */
    public SchemasCustomAttribute withName(@Nullable String name) {
        this.name = name;
        return this;
    }


    /**
     * The custom attribute's value.
     */
    public SchemasCustomAttribute withValue(@Nullable String value) {
        this.value = value;
        return this;
    }


    /**
     * The custom attribute's type.
     */
    public SchemasCustomAttribute withType(@Nullable SchemasCustomAttributeType type) {
        this.type = type;
        return this;
    }


    @Override
    public boolean equals(java.lang.Object o) {
        if (this == o) {
            return true;
        }
        if (o == null || getClass() != o.getClass()) {
            return false;
        }
        SchemasCustomAttribute other = (SchemasCustomAttribute) o;
        return 
            Utils.enhancedDeepEquals(this.name, other.name) &&
            Utils.enhancedDeepEquals(this.value, other.value) &&
            Utils.enhancedDeepEquals(this.type, other.type);
    }
    
    @Override
    public int hashCode() {
        return Utils.enhancedHash(
            name, value, type);
    }
    
    @Override
    public String toString() {
        return Utils.toString(SchemasCustomAttribute.class,
                "name", name,
                "value", value,
                "type", type);
    }

    @SuppressWarnings("UnusedReturnValue")
    public final static class Builder {

        private String name;

        private String value;

        private SchemasCustomAttributeType type;

        private Builder() {
          // force use of static builder() method
        }

        /**
         * The custom attribute's name.
         */
        public Builder name(@Nullable String name) {
            this.name = name;
            return this;
        }

        /**
         * The custom attribute's value.
         */
        public Builder value(@Nullable String value) {
            this.value = value;
            return this;
        }

        /**
         * The custom attribute's type.
         */
        public Builder type(@Nullable SchemasCustomAttributeType type) {
            this.type = type;
            return this;
        }

        public SchemasCustomAttribute build() {
            return new SchemasCustomAttribute(
                name, value, type);
        }

    }
}
