/* 
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */
package com.egain.sdk.models.components;

import com.fasterxml.jackson.annotation.JsonValue;
import java.lang.String;
import java.util.Objects;
import java.util.Optional;

/**
 * StaticReplacementType
 * 
 * <p>Identifies this replacement as a **static value**. At execution, the specified `value` will replace
 * the variable `name` in the prompt template.
 */
public enum StaticReplacementType {
    STATIC("static");

    @JsonValue
    private final String value;

    StaticReplacementType(String value) {
        this.value = value;
    }
    
    public String value() {
        return value;
    }
    
    public static Optional<StaticReplacementType> fromValue(String value) {
        for (StaticReplacementType o: StaticReplacementType.values()) {
            if (Objects.deepEquals(o.value, value)) {
                return Optional.of(o);
            }
        }
        return Optional.empty();
    }
}

