/* 
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */
package com.egain.sdk.models.components;

import com.fasterxml.jackson.annotation.JsonValue;
import java.lang.String;
import java.util.Objects;
import java.util.Optional;

/**
 * SuggestionCode
 * 
 * <p>The language that describes the details of the resource. Resources available in different languages
 * may differ from each other.
 */
public enum SuggestionCode {
    EN_US("en-US"),
    EN_GB("en-GB"),
    FRFR("fr-FR"),
    ESES("es-ES"),
    ITIT("it-IT"),
    DEDE("de-DE"),
    NLNL("nl-NL"),
    PT_BR("pt-BR"),
    PTPT("pt-PT"),
    DA_DK("da-DK"),
    SV_SE("sv-SE"),
    RURU("ru-RU"),
    ZH_CN("zh-CN"),
    JA_JP("ja-JP"),
    KO_KR("ko-KR"),
    DE_AT("de-AT"),
    THTH("th-TH"),
    VI_VN("vi-VN"),
    IDID("id-ID"),
    MS_MY("ms-MY"),
    FIL_PH("fil-PH"),
    FR_CA("fr-CA"),
    HI_IN("hi-IN"),
    UK_UA("uk-UA"),
    BGBG("bg-BG"),
    SKSK("sk-SK"),
    SL_SI("sl-SI");

    @JsonValue
    private final String value;

    SuggestionCode(String value) {
        this.value = value;
    }
    
    public String value() {
        return value;
    }
    
    public static Optional<SuggestionCode> fromValue(String value) {
        for (SuggestionCode o: SuggestionCode.values()) {
            if (Objects.deepEquals(o.value, value)) {
                return Optional.of(o);
            }
        }
        return Optional.empty();
    }
}

