/* 
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */
package com.egain.sdk.models.components;

import com.egain.sdk.utils.Utils;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonInclude.Include;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import jakarta.annotation.Nonnull;
import jakarta.annotation.Nullable;
import java.lang.Override;
import java.lang.String;
import java.util.Optional;

/**
 * SuggestionLanguage
 * 
 * <p>The knowledge base language in which the Suggestion was created.
 */
public class SuggestionLanguage {
    /**
     * The language that describes the details of the resource. Resources available in different languages
     * may differ from each other.
     */
    @JsonProperty("code")
    private SuggestionCode code;

    /**
     * The name of the language.
     */
    @JsonInclude(Include.NON_ABSENT)
    @JsonProperty("label")
    private Label label;

    @JsonCreator
    public SuggestionLanguage(
            @JsonProperty("code") @Nonnull SuggestionCode code,
            @JsonProperty("label") @Nullable Label label) {
        this.code = Optional.ofNullable(code)
            .orElseThrow(() -> new IllegalArgumentException("code cannot be null"));
        this.label = label;
    }
    
    public SuggestionLanguage(
            @Nonnull SuggestionCode code) {
        this(code, null);
    }

    /**
     * The language that describes the details of the resource. Resources available in different languages
     * may differ from each other.
     */
    public SuggestionCode code() {
        return this.code;
    }

    /**
     * The name of the language.
     */
    public Optional<Label> label() {
        return Optional.ofNullable(this.label);
    }

    public static Builder builder() {
        return new Builder();
    }


    /**
     * The language that describes the details of the resource. Resources available in different languages
     * may differ from each other.
     */
    public SuggestionLanguage withCode(@Nonnull SuggestionCode code) {
        this.code = Utils.checkNotNull(code, "code");
        return this;
    }


    /**
     * The name of the language.
     */
    public SuggestionLanguage withLabel(@Nullable Label label) {
        this.label = label;
        return this;
    }


    @Override
    public boolean equals(java.lang.Object o) {
        if (this == o) {
            return true;
        }
        if (o == null || getClass() != o.getClass()) {
            return false;
        }
        SuggestionLanguage other = (SuggestionLanguage) o;
        return 
            Utils.enhancedDeepEquals(this.code, other.code) &&
            Utils.enhancedDeepEquals(this.label, other.label);
    }
    
    @Override
    public int hashCode() {
        return Utils.enhancedHash(
            code, label);
    }
    
    @Override
    public String toString() {
        return Utils.toString(SuggestionLanguage.class,
                "code", code,
                "label", label);
    }

    @SuppressWarnings("UnusedReturnValue")
    public final static class Builder {

        private SuggestionCode code;

        private Label label;

        private Builder() {
          // force use of static builder() method
        }

        /**
         * The language that describes the details of the resource. Resources available in different languages
         * may differ from each other.
         */
        public Builder code(@Nonnull SuggestionCode code) {
            this.code = Utils.checkNotNull(code, "code");
            return this;
        }

        /**
         * The name of the language.
         */
        public Builder label(@Nullable Label label) {
            this.label = label;
            return this;
        }

        public SuggestionLanguage build() {
            return new SuggestionLanguage(
                code, label);
        }

    }
}
