/* 
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */
package com.egain.sdk.models.components;

import com.egain.sdk.utils.Utils;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonInclude.Include;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import jakarta.annotation.Nullable;
import java.lang.Override;
import java.lang.String;
import java.util.Optional;

/**
 * TagCategory
 * 
 * <p>A tag category is a grouping of tags and tag groups.
 */
public class TagCategory {
    /**
     * The name of the tag category.
     */
    @JsonInclude(Include.NON_ABSENT)
    @JsonProperty("name")
    private String name;

    /**
     * The ID of the tag category. A tag category ID is composed of a 4-letter prefix, followed by a dash
     * and 4-15 digits.
     */
    @JsonInclude(Include.NON_ABSENT)
    @JsonProperty("id")
    private String id;


    @JsonInclude(Include.NON_ABSENT)
    @JsonProperty("tags")
    private Tags tags;


    @JsonInclude(Include.NON_ABSENT)
    @JsonProperty("tagGroups")
    private TagGroups tagGroups;

    @JsonCreator
    public TagCategory(
            @JsonProperty("name") @Nullable String name,
            @JsonProperty("id") @Nullable String id,
            @JsonProperty("tags") @Nullable Tags tags,
            @JsonProperty("tagGroups") @Nullable TagGroups tagGroups) {
        this.name = name;
        this.id = id;
        this.tags = tags;
        this.tagGroups = tagGroups;
    }
    
    public TagCategory() {
        this(null, null, null,
            null);
    }

    /**
     * The name of the tag category.
     */
    public Optional<String> name() {
        return Optional.ofNullable(this.name);
    }

    /**
     * The ID of the tag category. A tag category ID is composed of a 4-letter prefix, followed by a dash
     * and 4-15 digits.
     */
    public Optional<String> id() {
        return Optional.ofNullable(this.id);
    }

    public Optional<Tags> tags() {
        return Optional.ofNullable(this.tags);
    }

    public Optional<TagGroups> tagGroups() {
        return Optional.ofNullable(this.tagGroups);
    }

    public static Builder builder() {
        return new Builder();
    }


    /**
     * The name of the tag category.
     */
    public TagCategory withName(@Nullable String name) {
        this.name = name;
        return this;
    }


    /**
     * The ID of the tag category. A tag category ID is composed of a 4-letter prefix, followed by a dash
     * and 4-15 digits.
     */
    public TagCategory withId(@Nullable String id) {
        this.id = id;
        return this;
    }


    public TagCategory withTags(@Nullable Tags tags) {
        this.tags = tags;
        return this;
    }


    public TagCategory withTagGroups(@Nullable TagGroups tagGroups) {
        this.tagGroups = tagGroups;
        return this;
    }


    @Override
    public boolean equals(java.lang.Object o) {
        if (this == o) {
            return true;
        }
        if (o == null || getClass() != o.getClass()) {
            return false;
        }
        TagCategory other = (TagCategory) o;
        return 
            Utils.enhancedDeepEquals(this.name, other.name) &&
            Utils.enhancedDeepEquals(this.id, other.id) &&
            Utils.enhancedDeepEquals(this.tags, other.tags) &&
            Utils.enhancedDeepEquals(this.tagGroups, other.tagGroups);
    }
    
    @Override
    public int hashCode() {
        return Utils.enhancedHash(
            name, id, tags,
            tagGroups);
    }
    
    @Override
    public String toString() {
        return Utils.toString(TagCategory.class,
                "name", name,
                "id", id,
                "tags", tags,
                "tagGroups", tagGroups);
    }

    @SuppressWarnings("UnusedReturnValue")
    public final static class Builder {

        private String name;

        private String id;

        private Tags tags;

        private TagGroups tagGroups;

        private Builder() {
          // force use of static builder() method
        }

        /**
         * The name of the tag category.
         */
        public Builder name(@Nullable String name) {
            this.name = name;
            return this;
        }

        /**
         * The ID of the tag category. A tag category ID is composed of a 4-letter prefix, followed by a dash
         * and 4-15 digits.
         */
        public Builder id(@Nullable String id) {
            this.id = id;
            return this;
        }

        public Builder tags(@Nullable Tags tags) {
            this.tags = tags;
            return this;
        }

        public Builder tagGroups(@Nullable TagGroups tagGroups) {
            this.tagGroups = tagGroups;
            return this;
        }

        public TagCategory build() {
            return new TagCategory(
                name, id, tags,
                tagGroups);
        }

    }
}
