/* 
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */
package com.egain.sdk.models.components;

import com.egain.sdk.utils.Utils;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonInclude.Include;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import jakarta.annotation.Nullable;
import java.lang.Override;
import java.lang.String;
import java.util.List;
import java.util.Optional;

/**
 * TopicBreadcrumbsList
 * 
 * <p>This schema contains an array of topic breadcrumbs, allowing clients to distinguish between multiple
 * distinct hierarchical topic paths.
 */
public class TopicBreadcrumbsList {
    /**
     * An array of TopicBreadcrumb instances representing individual paths.
     */
    @JsonInclude(Include.NON_ABSENT)
    @JsonProperty("topicBreadcrumb")
    private List<TopicBreadcrumb> topicBreadcrumb;

    @JsonCreator
    public TopicBreadcrumbsList(
            @JsonProperty("topicBreadcrumb") @Nullable List<TopicBreadcrumb> topicBreadcrumb) {
        this.topicBreadcrumb = topicBreadcrumb;
    }
    
    public TopicBreadcrumbsList() {
        this(null);
    }

    /**
     * An array of TopicBreadcrumb instances representing individual paths.
     */
    public Optional<List<TopicBreadcrumb>> topicBreadcrumb() {
        return Optional.ofNullable(this.topicBreadcrumb);
    }

    public static Builder builder() {
        return new Builder();
    }


    /**
     * An array of TopicBreadcrumb instances representing individual paths.
     */
    public TopicBreadcrumbsList withTopicBreadcrumb(@Nullable List<TopicBreadcrumb> topicBreadcrumb) {
        this.topicBreadcrumb = topicBreadcrumb;
        return this;
    }


    @Override
    public boolean equals(java.lang.Object o) {
        if (this == o) {
            return true;
        }
        if (o == null || getClass() != o.getClass()) {
            return false;
        }
        TopicBreadcrumbsList other = (TopicBreadcrumbsList) o;
        return 
            Utils.enhancedDeepEquals(this.topicBreadcrumb, other.topicBreadcrumb);
    }
    
    @Override
    public int hashCode() {
        return Utils.enhancedHash(
            topicBreadcrumb);
    }
    
    @Override
    public String toString() {
        return Utils.toString(TopicBreadcrumbsList.class,
                "topicBreadcrumb", topicBreadcrumb);
    }

    @SuppressWarnings("UnusedReturnValue")
    public final static class Builder {

        private List<TopicBreadcrumb> topicBreadcrumb;

        private Builder() {
          // force use of static builder() method
        }

        /**
         * An array of TopicBreadcrumb instances representing individual paths.
         */
        public Builder topicBreadcrumb(@Nullable List<TopicBreadcrumb> topicBreadcrumb) {
            this.topicBreadcrumb = topicBreadcrumb;
            return this;
        }

        public TopicBreadcrumbsList build() {
            return new TopicBreadcrumbsList(
                topicBreadcrumb);
        }

    }
}
