/* 
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */
package com.egain.sdk.models.components;

import com.egain.sdk.utils.Utils;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonInclude.Include;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import jakarta.annotation.Nullable;
import java.lang.Override;
import java.lang.String;
import java.util.List;
import java.util.Optional;

/**
 * TopicBreadcrumb
 * 
 * <p>This schema contains one or more TopicSummary instances.
 */
public class TopicBreadcrumb {
    /**
     * An instance of TopicSummary.
     */
    @JsonInclude(Include.NON_ABSENT)
    @JsonProperty("topicSummary")
    private List<TopicSummary> topicSummary;

    @JsonCreator
    public TopicBreadcrumb(
            @JsonProperty("topicSummary") @Nullable List<TopicSummary> topicSummary) {
        this.topicSummary = topicSummary;
    }
    
    public TopicBreadcrumb() {
        this(null);
    }

    /**
     * An instance of TopicSummary.
     */
    public Optional<List<TopicSummary>> topicSummary() {
        return Optional.ofNullable(this.topicSummary);
    }

    public static Builder builder() {
        return new Builder();
    }


    /**
     * An instance of TopicSummary.
     */
    public TopicBreadcrumb withTopicSummary(@Nullable List<TopicSummary> topicSummary) {
        this.topicSummary = topicSummary;
        return this;
    }


    @Override
    public boolean equals(java.lang.Object o) {
        if (this == o) {
            return true;
        }
        if (o == null || getClass() != o.getClass()) {
            return false;
        }
        TopicBreadcrumb other = (TopicBreadcrumb) o;
        return 
            Utils.enhancedDeepEquals(this.topicSummary, other.topicSummary);
    }
    
    @Override
    public int hashCode() {
        return Utils.enhancedHash(
            topicSummary);
    }
    
    @Override
    public String toString() {
        return Utils.toString(TopicBreadcrumb.class,
                "topicSummary", topicSummary);
    }

    @SuppressWarnings("UnusedReturnValue")
    public final static class Builder {

        private List<TopicSummary> topicSummary;

        private Builder() {
          // force use of static builder() method
        }

        /**
         * An instance of TopicSummary.
         */
        public Builder topicSummary(@Nullable List<TopicSummary> topicSummary) {
            this.topicSummary = topicSummary;
            return this;
        }

        public TopicBreadcrumb build() {
            return new TopicBreadcrumb(
                topicSummary);
        }

    }
}
