/* 
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */
package com.egain.sdk.models.components;

import com.fasterxml.jackson.annotation.JsonValue;
import java.lang.String;
import java.util.Objects;
import java.util.Optional;

/**
 * UseFor
 * 
 * <p>Specifies which console the prompt applies to: 'knowledge', 'advisor', or 'custom' (for prompts used
 * outside any console).
 */
public enum UseFor {
    KNOWLEDGE("knowledge"),
    ADVISOR("advisor"),
    CUSTOM("custom");

    @JsonValue
    private final String value;

    UseFor(String value) {
        this.value = value;
    }
    
    public String value() {
        return value;
    }
    
    public static Optional<UseFor> fromValue(String value) {
        for (UseFor o: UseFor.values()) {
            if (Objects.deepEquals(o.value, value)) {
                return Optional.of(o);
            }
        }
        return Optional.empty();
    }
}

