/* 
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */
package com.egain.sdk.models.components;

import com.fasterxml.jackson.annotation.JsonValue;
import java.lang.String;
import java.util.Objects;
import java.util.Optional;

/**
 * UserType
 * 
 * <p>The type of the user associated with the bookmark.
 */
public enum UserType {
    CUSTOMER("customer"),
    AGENT("agent");

    @JsonValue
    private final String value;

    UserType(String value) {
        this.value = value;
    }
    
    public String value() {
        return value;
    }
    
    public static Optional<UserType> fromValue(String value) {
        for (UserType o: UserType.values()) {
            if (Objects.deepEquals(o.value, value)) {
                return Optional.of(o);
            }
        }
        return Optional.empty();
    }
}

