/* 
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */
package com.egain.sdk.models.components;

import com.egain.sdk.utils.Utils;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonInclude.Include;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import jakarta.annotation.Nonnull;
import jakarta.annotation.Nullable;
import java.lang.Override;
import java.lang.String;
import java.util.Optional;


public class ValidateImportContentDataSource {
    /**
     * Type of data source
     */
    @JsonProperty("type")
    private ValidateImportContentType type;

    /**
     * Path of the data source
     */
    @JsonProperty("path")
    private String path;

    /**
     * Region of the data source
     */
    @JsonInclude(Include.NON_ABSENT)
    @JsonProperty("region")
    private String region;


    @JsonInclude(Include.NON_ABSENT)
    @JsonProperty("credentials")
    private ValidateImportContentCredentials credentials;

    @JsonCreator
    public ValidateImportContentDataSource(
            @JsonProperty("type") @Nonnull ValidateImportContentType type,
            @JsonProperty("path") @Nonnull String path,
            @JsonProperty("region") @Nullable String region,
            @JsonProperty("credentials") @Nullable ValidateImportContentCredentials credentials) {
        this.type = Optional.ofNullable(type)
            .orElseThrow(() -> new IllegalArgumentException("type cannot be null"));
        this.path = Optional.ofNullable(path)
            .orElseThrow(() -> new IllegalArgumentException("path cannot be null"));
        this.region = region;
        this.credentials = credentials;
    }
    
    public ValidateImportContentDataSource(
            @Nonnull ValidateImportContentType type,
            @Nonnull String path) {
        this(type, path, null,
            null);
    }

    /**
     * Type of data source
     */
    public ValidateImportContentType type() {
        return this.type;
    }

    /**
     * Path of the data source
     */
    public String path() {
        return this.path;
    }

    /**
     * Region of the data source
     */
    public Optional<String> region() {
        return Optional.ofNullable(this.region);
    }

    public Optional<ValidateImportContentCredentials> credentials() {
        return Optional.ofNullable(this.credentials);
    }

    public static Builder builder() {
        return new Builder();
    }


    /**
     * Type of data source
     */
    public ValidateImportContentDataSource withType(@Nonnull ValidateImportContentType type) {
        this.type = Utils.checkNotNull(type, "type");
        return this;
    }


    /**
     * Path of the data source
     */
    public ValidateImportContentDataSource withPath(@Nonnull String path) {
        this.path = Utils.checkNotNull(path, "path");
        return this;
    }


    /**
     * Region of the data source
     */
    public ValidateImportContentDataSource withRegion(@Nullable String region) {
        this.region = region;
        return this;
    }


    public ValidateImportContentDataSource withCredentials(@Nullable ValidateImportContentCredentials credentials) {
        this.credentials = credentials;
        return this;
    }


    @Override
    public boolean equals(java.lang.Object o) {
        if (this == o) {
            return true;
        }
        if (o == null || getClass() != o.getClass()) {
            return false;
        }
        ValidateImportContentDataSource other = (ValidateImportContentDataSource) o;
        return 
            Utils.enhancedDeepEquals(this.type, other.type) &&
            Utils.enhancedDeepEquals(this.path, other.path) &&
            Utils.enhancedDeepEquals(this.region, other.region) &&
            Utils.enhancedDeepEquals(this.credentials, other.credentials);
    }
    
    @Override
    public int hashCode() {
        return Utils.enhancedHash(
            type, path, region,
            credentials);
    }
    
    @Override
    public String toString() {
        return Utils.toString(ValidateImportContentDataSource.class,
                "type", type,
                "path", path,
                "region", region,
                "credentials", credentials);
    }

    @SuppressWarnings("UnusedReturnValue")
    public final static class Builder {

        private ValidateImportContentType type;

        private String path;

        private String region;

        private ValidateImportContentCredentials credentials;

        private Builder() {
          // force use of static builder() method
        }

        /**
         * Type of data source
         */
        public Builder type(@Nonnull ValidateImportContentType type) {
            this.type = Utils.checkNotNull(type, "type");
            return this;
        }

        /**
         * Path of the data source
         */
        public Builder path(@Nonnull String path) {
            this.path = Utils.checkNotNull(path, "path");
            return this;
        }

        /**
         * Region of the data source
         */
        public Builder region(@Nullable String region) {
            this.region = region;
            return this;
        }

        public Builder credentials(@Nullable ValidateImportContentCredentials credentials) {
            this.credentials = credentials;
            return this;
        }

        public ValidateImportContentDataSource build() {
            return new ValidateImportContentDataSource(
                type, path, region,
                credentials);
        }

    }
}
