/* 
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */
package com.egain.sdk.models.components;

import com.egain.sdk.utils.Utils;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonProperty;
import jakarta.annotation.Nonnull;
import java.lang.Override;
import java.lang.String;
import java.util.Optional;


public class ValidateImportContent {

    @JsonProperty("dataSource")
    private ValidateImportContentDataSource dataSource;

    @JsonCreator
    public ValidateImportContent(
            @JsonProperty("dataSource") @Nonnull ValidateImportContentDataSource dataSource) {
        this.dataSource = Optional.ofNullable(dataSource)
            .orElseThrow(() -> new IllegalArgumentException("dataSource cannot be null"));
    }

    public ValidateImportContentDataSource dataSource() {
        return this.dataSource;
    }

    public static Builder builder() {
        return new Builder();
    }


    public ValidateImportContent withDataSource(@Nonnull ValidateImportContentDataSource dataSource) {
        this.dataSource = Utils.checkNotNull(dataSource, "dataSource");
        return this;
    }


    @Override
    public boolean equals(java.lang.Object o) {
        if (this == o) {
            return true;
        }
        if (o == null || getClass() != o.getClass()) {
            return false;
        }
        ValidateImportContent other = (ValidateImportContent) o;
        return 
            Utils.enhancedDeepEquals(this.dataSource, other.dataSource);
    }
    
    @Override
    public int hashCode() {
        return Utils.enhancedHash(
            dataSource);
    }
    
    @Override
    public String toString() {
        return Utils.toString(ValidateImportContent.class,
                "dataSource", dataSource);
    }

    @SuppressWarnings("UnusedReturnValue")
    public final static class Builder {

        private ValidateImportContentDataSource dataSource;

        private Builder() {
          // force use of static builder() method
        }

        public Builder dataSource(@Nonnull ValidateImportContentDataSource dataSource) {
            this.dataSource = Utils.checkNotNull(dataSource, "dataSource");
            return this;
        }

        public ValidateImportContent build() {
            return new ValidateImportContent(
                dataSource);
        }

    }
}
