/* 
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */
package com.egain.sdk.models.operations;

import com.egain.sdk.models.components.AcceptLanguage;
import com.egain.sdk.utils.SpeakeasyMetadata;
import com.egain.sdk.utils.Utils;
import com.fasterxml.jackson.annotation.JsonCreator;
import jakarta.annotation.Nonnull;
import java.lang.Override;
import java.lang.String;
import java.util.Optional;


public class ExportStatusRequest {
    /**
     * The Language locale accepted by the client (used for locale specific fields in resource
     * representation and in error responses).
     */
    @SpeakeasyMetadata("header:style=simple,explode=false,name=Accept-Language")
    private AcceptLanguage acceptLanguage;

    /**
     * **Example Usage:**
     * ```bash
     * GET /content/export/7A84B875-6F75-4C7B-B137-0632B62DB0BD/status
     * ```
     */
    @SpeakeasyMetadata("pathParam:style=simple,explode=false,name=jobID")
    private String jobID;

    @JsonCreator
    public ExportStatusRequest(
            @Nonnull AcceptLanguage acceptLanguage,
            @Nonnull String jobID) {
        this.acceptLanguage = Optional.ofNullable(acceptLanguage)
            .orElseThrow(() -> new IllegalArgumentException("acceptLanguage cannot be null"));
        this.jobID = Optional.ofNullable(jobID)
            .orElseThrow(() -> new IllegalArgumentException("jobID cannot be null"));
    }

    /**
     * The Language locale accepted by the client (used for locale specific fields in resource
     * representation and in error responses).
     */
    public AcceptLanguage acceptLanguage() {
        return this.acceptLanguage;
    }

    /**
     * **Example Usage:**
     * ```bash
     * GET /content/export/7A84B875-6F75-4C7B-B137-0632B62DB0BD/status
     * ```
     */
    public String jobID() {
        return this.jobID;
    }

    public static Builder builder() {
        return new Builder();
    }


    /**
     * The Language locale accepted by the client (used for locale specific fields in resource
     * representation and in error responses).
     */
    public ExportStatusRequest withAcceptLanguage(@Nonnull AcceptLanguage acceptLanguage) {
        this.acceptLanguage = Utils.checkNotNull(acceptLanguage, "acceptLanguage");
        return this;
    }


    /**
     * **Example Usage:**
     * ```bash
     * GET /content/export/7A84B875-6F75-4C7B-B137-0632B62DB0BD/status
     * ```
     */
    public ExportStatusRequest withJobID(@Nonnull String jobID) {
        this.jobID = Utils.checkNotNull(jobID, "jobID");
        return this;
    }


    @Override
    public boolean equals(java.lang.Object o) {
        if (this == o) {
            return true;
        }
        if (o == null || getClass() != o.getClass()) {
            return false;
        }
        ExportStatusRequest other = (ExportStatusRequest) o;
        return 
            Utils.enhancedDeepEquals(this.acceptLanguage, other.acceptLanguage) &&
            Utils.enhancedDeepEquals(this.jobID, other.jobID);
    }
    
    @Override
    public int hashCode() {
        return Utils.enhancedHash(
            acceptLanguage, jobID);
    }
    
    @Override
    public String toString() {
        return Utils.toString(ExportStatusRequest.class,
                "acceptLanguage", acceptLanguage,
                "jobID", jobID);
    }

    @SuppressWarnings("UnusedReturnValue")
    public final static class Builder {

        private AcceptLanguage acceptLanguage;

        private String jobID;

        private Builder() {
          // force use of static builder() method
        }

        /**
         * The Language locale accepted by the client (used for locale specific fields in resource
         * representation and in error responses).
         */
        public Builder acceptLanguage(@Nonnull AcceptLanguage acceptLanguage) {
            this.acceptLanguage = Utils.checkNotNull(acceptLanguage, "acceptLanguage");
            return this;
        }

        /**
         * **Example Usage:**
         * ```bash
         * GET /content/export/7A84B875-6F75-4C7B-B137-0632B62DB0BD/status
         * ```
         */
        public Builder jobID(@Nonnull String jobID) {
            this.jobID = Utils.checkNotNull(jobID, "jobID");
            return this;
        }

        public ExportStatusRequest build() {
            return new ExportStatusRequest(
                acceptLanguage, jobID);
        }

    }
}
