/* 
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */
package com.egain.sdk.models.operations;

import static com.egain.sdk.operations.Operations.RequestOperation;

import com.egain.sdk.SDKConfiguration;
import com.egain.sdk.operations.ExportStatus;
import com.egain.sdk.utils.Headers;
import com.egain.sdk.utils.Utils;
import jakarta.annotation.Nonnull;
import java.lang.String;

public class ExportStatusRequestBuilder {
    private final SDKConfiguration sdkConfiguration;
    private final Headers _headers = new Headers();
    private final ExportStatusRequest.Builder pojoBuilder;
    private ExportStatusRequest request;
    private boolean _setterCalled;

    public ExportStatusRequestBuilder(SDKConfiguration sdkConfiguration) {
        this.sdkConfiguration = sdkConfiguration;
        this.pojoBuilder = ExportStatusRequest.builder();
    }

    public ExportStatusRequestBuilder jobID(@Nonnull String jobID) {
        this.pojoBuilder.jobID(jobID);
        this._setterCalled = true;
        return this;
    }

    private ExportStatusRequest _buildRequest() {
        if (this._setterCalled) {
            this.request = this.pojoBuilder.build();
        }
        return this.request;
    }
    
    public ExportStatusRequestBuilder header(String name, String value) {
        Utils.checkNotNull(name, "name");
        Utils.checkNotNull(value, "value");
        this._headers.add(name, value);
        return this;
    }

    /**
    * Executes the request and returns the response.
    *
    * @return The response from the server.
    */
    public ExportStatusResponse call() {
        RequestOperation<ExportStatusRequest, ExportStatusResponse> operation
              = new ExportStatus.Sync(sdkConfiguration, _headers);
        return operation.handleResponse(operation.doRequest(this._buildRequest()));
    }
}
