/* 
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */
package com.egain.sdk.models.operations;

import com.egain.sdk.models.components.AcceptLanguage;
import com.egain.sdk.models.components.ArticleAdditionalAttributes;
import com.egain.sdk.models.components.LanguageQueryParameter;
import com.egain.sdk.models.components.WorkflowMilestone;
import com.egain.sdk.utils.LazySingletonValue;
import com.egain.sdk.utils.SpeakeasyMetadata;
import com.egain.sdk.utils.Utils;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.core.type.TypeReference;
import jakarta.annotation.Nonnull;
import jakarta.annotation.Nullable;
import java.lang.Override;
import java.lang.String;
import java.util.List;
import java.util.Optional;


public class GetArticleByIdRequest {
    /**
     * The Language locale accepted by the client (used for locale specific fields in resource
     * representation and in error responses).
     */
    @SpeakeasyMetadata("header:style=simple,explode=false,name=Accept-Language")
    private AcceptLanguage acceptLanguage;

    /**
     * The ID of the portal being accessed.<br><br>A portal ID is composed of a 2-4 letter prefix, followed
     * by a dash and 4-15 digits.
     */
    @SpeakeasyMetadata("pathParam:style=simple,explode=false,name=portalID")
    private String portalID;

    /**
     * The ID of the Article.<br><br>An Article ID is composed of a 2-4 letter prefix followed by a dash
     * and 4-15 digits.
     */
    @SpeakeasyMetadata("pathParam:style=simple,explode=false,name=articleID")
    private String articleID;

    /**
     * The language that describes the details of a resource. Resources available in different languages
     * may differ from each other.<li>If <code>lang</code> is not passed, then the portal's default
     * language is used.&lt;/li&gt;
     */
    @SpeakeasyMetadata("queryParam:style=form,explode=true,name=$lang")
    private LanguageQueryParameter language;

    /**
     * The attributes of an Article to be returned *in addition to* the default list of attributes, listed
     * below. Multiple additional attributes can be specified using a comma-separated list. Passing 'all'
     * will return all attributes.
     * 
     * <p>#### Default Attributes
     * These Article attributes are always returned:
     * 
     * <p>| Name | Description
     * | ---- | -----------
     * | id | The ID of the Article.
     * | name  | The name of the Article.
     * | additionalInfo | Additional information provided as Article metadata.
     * | articleType | The Article type and its attributes.
     * | articleKeywords | A comma-separated list of keywords associated with this Article.
     * | articleState | The current state of the Article. States include A (Authoring), S (Staging), and P
     * (Published).
     * | articleSummary | A brief summary of the Article, provided as metadata.
     * | createdBy | The ID, first name, middle name and last name of the user that created the Article.
     * | createdDate | The date that the Article was created.
     * | departmentId | ID of the department for which this Article belongs to.
     * | description | The Article's description.
     * | expirationDate | The date that the Article is set to expire.
     * | attachments | The Article's attachments
     * | imageURL | The URL of the image that is present in the Article version. It is used as the
     * thumbnail image for the Article.
     * | includeInGenAI | Indicates whether this Article is used for eGain's generative AI features.
     * | isSubscribed | Indicates whether the Article is subscribed for notifications.
     * | languageCode | The language code of the Article language.
     * | link | The link object, used to retrieve the details of the Article.
     * | modifiedBy | The ID, first name, middle name and last name of the user that last modified the
     * Article.
     * | modifiedDate | The date that the Article was last modified on.
     * | topicBreadcrumb | Contains a list of topics from the top-level topic to this Article. There may be
     * multiple paths.
     * | versionId | The ID of the Article version that is returned.
     */
    @SpeakeasyMetadata("queryParam:style=form,explode=false,name=articleAdditionalAttributes")
    private List<ArticleAdditionalAttributes> articleAdditionalAttributes;


    @SpeakeasyMetadata("queryParam:style=form,explode=true,name=$customAdditionalAttributes")
    private String customAdditionalAttributes;

    /**
     * Provides information about the method in which the Article is accessed and is used for self-service
     * analytics. Refer to the eGain User Guide regarding "Article View Contexts".
     * 
     * <p>| Name | Description
     * | ---- | -----------
     * | article_view | View an Article directly using its ID.
     * | article_view_more_related_Article  | View related articles of an Article using its ID.
     * | article_view_basic_search | View an Article via a basic search.
     * | article_view_adv_search | View an Article via an advanced search.
     * | article_view_guided_help | View an Article via a Guided Help solution.
     * | article_view_browse_topic | View an Article via browsing a topic.
     * | article_view_browse_tree | View an Article via browsing a topic tree.
     * | article_view_popular_articles | View an Article using the Popular Items list in the Self-Service
     * portal.
     * | article_view_useful_items | View Article using the Useful Items list in the Self-Service portal.
     * | article_view_widget | View an Article via a widget.
     * | article_view_announcement | View an Article from the announcement section in the Self-Service
     * portal.
     * | article_view_bookmarked | View a bookmarked Article.
     * | article_view_subscription_notification | View an Article from a subscription notification.
     * | article_view_guided_help_additional_info | View an Article via additional information from a
     * Guided Help search.
     * | view_articles_pending_compliance | View an Article via Read &amp; Sign in the Self-Service portal.
     * | type_ahead_Suggestion | View an Article from a type-ahead Suggestion in the Self-Service portal.
     * | semantic_Suggestion | View an Article from a semantic Suggestion in the Self-Service portal.
     * | instant_answer | View an Article via an Instant Answers solution.
     * | instant_answer_reference | View an Article that is used as a reference for an Instant Answers
     * solution.
     */
    @SpeakeasyMetadata("queryParam:style=form,explode=true,name=accessSource")
    private AccessSource accessSource;

    /**
     * The ID of a publish view for an Article. A publish view is a set of tags used to generate multiple
     * editions of the same Article for display on the self-service portal. Publish views are used in
     * conjunction with single sourcing to tailor the content of an Article to a specific audience by
     * granting access to an Article's version to users that possess the same tags.<br><br>A publish view
     * ID is composed of a 4-letter prefix, followed by a dash and 4-15 digits.
     */
    @SpeakeasyMetadata("queryParam:style=form,explode=true,name=publishViewId")
    private String publishViewId;

    /**
     * For agents with the View Author Portal or View Staging Portal actions, this determines which version
     * of the Article is returned.<li>'Authoring' returns the most recent version of an Article checked-in
     * by an author.</li><li>'Staging' returns the updated version currently being processed in a
     * workflow.</li><li>'Publish' returns the most recently published version.</li>
     */
    @SpeakeasyMetadata("queryParam:style=form,explode=true,name=workflowMilestone")
    private WorkflowMilestone workflowMilestone;

    @JsonCreator
    public GetArticleByIdRequest(
            @Nonnull AcceptLanguage acceptLanguage,
            @Nonnull String portalID,
            @Nonnull String articleID,
            @Nullable LanguageQueryParameter language,
            @Nullable List<ArticleAdditionalAttributes> articleAdditionalAttributes,
            @Nullable String customAdditionalAttributes,
            @Nullable AccessSource accessSource,
            @Nullable String publishViewId,
            @Nullable WorkflowMilestone workflowMilestone) {
        this.acceptLanguage = Optional.ofNullable(acceptLanguage)
            .orElseThrow(() -> new IllegalArgumentException("acceptLanguage cannot be null"));
        this.portalID = Optional.ofNullable(portalID)
            .orElseThrow(() -> new IllegalArgumentException("portalID cannot be null"));
        this.articleID = Optional.ofNullable(articleID)
            .orElseThrow(() -> new IllegalArgumentException("articleID cannot be null"));
        this.language = language;
        this.articleAdditionalAttributes = articleAdditionalAttributes;
        this.customAdditionalAttributes = customAdditionalAttributes;
        this.accessSource = Optional.ofNullable(accessSource)
            .orElse(Builder._SINGLETON_VALUE_AccessSource.value());
        this.publishViewId = publishViewId;
        this.workflowMilestone = workflowMilestone;
    }
    
    public GetArticleByIdRequest(
            @Nonnull AcceptLanguage acceptLanguage,
            @Nonnull String portalID,
            @Nonnull String articleID) {
        this(acceptLanguage, portalID, articleID,
            null, null, null,
            null, null, null);
    }

    /**
     * The Language locale accepted by the client (used for locale specific fields in resource
     * representation and in error responses).
     */
    public AcceptLanguage acceptLanguage() {
        return this.acceptLanguage;
    }

    /**
     * The ID of the portal being accessed.<br><br>A portal ID is composed of a 2-4 letter prefix, followed
     * by a dash and 4-15 digits.
     */
    public String portalID() {
        return this.portalID;
    }

    /**
     * The ID of the Article.<br><br>An Article ID is composed of a 2-4 letter prefix followed by a dash
     * and 4-15 digits.
     */
    public String articleID() {
        return this.articleID;
    }

    /**
     * The language that describes the details of a resource. Resources available in different languages
     * may differ from each other.<li>If <code>lang</code> is not passed, then the portal's default
     * language is used.&lt;/li&gt;
     */
    public Optional<LanguageQueryParameter> language() {
        return Optional.ofNullable(this.language);
    }

    /**
     * The attributes of an Article to be returned *in addition to* the default list of attributes, listed
     * below. Multiple additional attributes can be specified using a comma-separated list. Passing 'all'
     * will return all attributes.
     * 
     * <p>#### Default Attributes
     * These Article attributes are always returned:
     * 
     * <p>| Name | Description
     * | ---- | -----------
     * | id | The ID of the Article.
     * | name  | The name of the Article.
     * | additionalInfo | Additional information provided as Article metadata.
     * | articleType | The Article type and its attributes.
     * | articleKeywords | A comma-separated list of keywords associated with this Article.
     * | articleState | The current state of the Article. States include A (Authoring), S (Staging), and P
     * (Published).
     * | articleSummary | A brief summary of the Article, provided as metadata.
     * | createdBy | The ID, first name, middle name and last name of the user that created the Article.
     * | createdDate | The date that the Article was created.
     * | departmentId | ID of the department for which this Article belongs to.
     * | description | The Article's description.
     * | expirationDate | The date that the Article is set to expire.
     * | attachments | The Article's attachments
     * | imageURL | The URL of the image that is present in the Article version. It is used as the
     * thumbnail image for the Article.
     * | includeInGenAI | Indicates whether this Article is used for eGain's generative AI features.
     * | isSubscribed | Indicates whether the Article is subscribed for notifications.
     * | languageCode | The language code of the Article language.
     * | link | The link object, used to retrieve the details of the Article.
     * | modifiedBy | The ID, first name, middle name and last name of the user that last modified the
     * Article.
     * | modifiedDate | The date that the Article was last modified on.
     * | topicBreadcrumb | Contains a list of topics from the top-level topic to this Article. There may be
     * multiple paths.
     * | versionId | The ID of the Article version that is returned.
     */
    public Optional<List<ArticleAdditionalAttributes>> articleAdditionalAttributes() {
        return Optional.ofNullable(this.articleAdditionalAttributes);
    }

    public Optional<String> customAdditionalAttributes() {
        return Optional.ofNullable(this.customAdditionalAttributes);
    }

    /**
     * Provides information about the method in which the Article is accessed and is used for self-service
     * analytics. Refer to the eGain User Guide regarding "Article View Contexts".
     * 
     * <p>| Name | Description
     * | ---- | -----------
     * | article_view | View an Article directly using its ID.
     * | article_view_more_related_Article  | View related articles of an Article using its ID.
     * | article_view_basic_search | View an Article via a basic search.
     * | article_view_adv_search | View an Article via an advanced search.
     * | article_view_guided_help | View an Article via a Guided Help solution.
     * | article_view_browse_topic | View an Article via browsing a topic.
     * | article_view_browse_tree | View an Article via browsing a topic tree.
     * | article_view_popular_articles | View an Article using the Popular Items list in the Self-Service
     * portal.
     * | article_view_useful_items | View Article using the Useful Items list in the Self-Service portal.
     * | article_view_widget | View an Article via a widget.
     * | article_view_announcement | View an Article from the announcement section in the Self-Service
     * portal.
     * | article_view_bookmarked | View a bookmarked Article.
     * | article_view_subscription_notification | View an Article from a subscription notification.
     * | article_view_guided_help_additional_info | View an Article via additional information from a
     * Guided Help search.
     * | view_articles_pending_compliance | View an Article via Read &amp; Sign in the Self-Service portal.
     * | type_ahead_Suggestion | View an Article from a type-ahead Suggestion in the Self-Service portal.
     * | semantic_Suggestion | View an Article from a semantic Suggestion in the Self-Service portal.
     * | instant_answer | View an Article via an Instant Answers solution.
     * | instant_answer_reference | View an Article that is used as a reference for an Instant Answers
     * solution.
     */
    public Optional<AccessSource> accessSource() {
        return Optional.ofNullable(this.accessSource);
    }

    /**
     * The ID of a publish view for an Article. A publish view is a set of tags used to generate multiple
     * editions of the same Article for display on the self-service portal. Publish views are used in
     * conjunction with single sourcing to tailor the content of an Article to a specific audience by
     * granting access to an Article's version to users that possess the same tags.<br><br>A publish view
     * ID is composed of a 4-letter prefix, followed by a dash and 4-15 digits.
     */
    public Optional<String> publishViewId() {
        return Optional.ofNullable(this.publishViewId);
    }

    /**
     * For agents with the View Author Portal or View Staging Portal actions, this determines which version
     * of the Article is returned.<li>'Authoring' returns the most recent version of an Article checked-in
     * by an author.</li><li>'Staging' returns the updated version currently being processed in a
     * workflow.</li><li>'Publish' returns the most recently published version.</li>
     */
    public Optional<WorkflowMilestone> workflowMilestone() {
        return Optional.ofNullable(this.workflowMilestone);
    }

    public static Builder builder() {
        return new Builder();
    }


    /**
     * The Language locale accepted by the client (used for locale specific fields in resource
     * representation and in error responses).
     */
    public GetArticleByIdRequest withAcceptLanguage(@Nonnull AcceptLanguage acceptLanguage) {
        this.acceptLanguage = Utils.checkNotNull(acceptLanguage, "acceptLanguage");
        return this;
    }


    /**
     * The ID of the portal being accessed.<br><br>A portal ID is composed of a 2-4 letter prefix, followed
     * by a dash and 4-15 digits.
     */
    public GetArticleByIdRequest withPortalID(@Nonnull String portalID) {
        this.portalID = Utils.checkNotNull(portalID, "portalID");
        return this;
    }


    /**
     * The ID of the Article.<br><br>An Article ID is composed of a 2-4 letter prefix followed by a dash
     * and 4-15 digits.
     */
    public GetArticleByIdRequest withArticleID(@Nonnull String articleID) {
        this.articleID = Utils.checkNotNull(articleID, "articleID");
        return this;
    }


    /**
     * The language that describes the details of a resource. Resources available in different languages
     * may differ from each other.<li>If <code>lang</code> is not passed, then the portal's default
     * language is used.&lt;/li&gt;
     */
    public GetArticleByIdRequest withLanguage(@Nullable LanguageQueryParameter language) {
        this.language = language;
        return this;
    }


    /**
     * The attributes of an Article to be returned *in addition to* the default list of attributes, listed
     * below. Multiple additional attributes can be specified using a comma-separated list. Passing 'all'
     * will return all attributes.
     * 
     * <p>#### Default Attributes
     * These Article attributes are always returned:
     * 
     * <p>| Name | Description
     * | ---- | -----------
     * | id | The ID of the Article.
     * | name  | The name of the Article.
     * | additionalInfo | Additional information provided as Article metadata.
     * | articleType | The Article type and its attributes.
     * | articleKeywords | A comma-separated list of keywords associated with this Article.
     * | articleState | The current state of the Article. States include A (Authoring), S (Staging), and P
     * (Published).
     * | articleSummary | A brief summary of the Article, provided as metadata.
     * | createdBy | The ID, first name, middle name and last name of the user that created the Article.
     * | createdDate | The date that the Article was created.
     * | departmentId | ID of the department for which this Article belongs to.
     * | description | The Article's description.
     * | expirationDate | The date that the Article is set to expire.
     * | attachments | The Article's attachments
     * | imageURL | The URL of the image that is present in the Article version. It is used as the
     * thumbnail image for the Article.
     * | includeInGenAI | Indicates whether this Article is used for eGain's generative AI features.
     * | isSubscribed | Indicates whether the Article is subscribed for notifications.
     * | languageCode | The language code of the Article language.
     * | link | The link object, used to retrieve the details of the Article.
     * | modifiedBy | The ID, first name, middle name and last name of the user that last modified the
     * Article.
     * | modifiedDate | The date that the Article was last modified on.
     * | topicBreadcrumb | Contains a list of topics from the top-level topic to this Article. There may be
     * multiple paths.
     * | versionId | The ID of the Article version that is returned.
     */
    public GetArticleByIdRequest withArticleAdditionalAttributes(@Nullable List<ArticleAdditionalAttributes> articleAdditionalAttributes) {
        this.articleAdditionalAttributes = articleAdditionalAttributes;
        return this;
    }


    public GetArticleByIdRequest withCustomAdditionalAttributes(@Nullable String customAdditionalAttributes) {
        this.customAdditionalAttributes = customAdditionalAttributes;
        return this;
    }


    /**
     * Provides information about the method in which the Article is accessed and is used for self-service
     * analytics. Refer to the eGain User Guide regarding "Article View Contexts".
     * 
     * <p>| Name | Description
     * | ---- | -----------
     * | article_view | View an Article directly using its ID.
     * | article_view_more_related_Article  | View related articles of an Article using its ID.
     * | article_view_basic_search | View an Article via a basic search.
     * | article_view_adv_search | View an Article via an advanced search.
     * | article_view_guided_help | View an Article via a Guided Help solution.
     * | article_view_browse_topic | View an Article via browsing a topic.
     * | article_view_browse_tree | View an Article via browsing a topic tree.
     * | article_view_popular_articles | View an Article using the Popular Items list in the Self-Service
     * portal.
     * | article_view_useful_items | View Article using the Useful Items list in the Self-Service portal.
     * | article_view_widget | View an Article via a widget.
     * | article_view_announcement | View an Article from the announcement section in the Self-Service
     * portal.
     * | article_view_bookmarked | View a bookmarked Article.
     * | article_view_subscription_notification | View an Article from a subscription notification.
     * | article_view_guided_help_additional_info | View an Article via additional information from a
     * Guided Help search.
     * | view_articles_pending_compliance | View an Article via Read &amp; Sign in the Self-Service portal.
     * | type_ahead_Suggestion | View an Article from a type-ahead Suggestion in the Self-Service portal.
     * | semantic_Suggestion | View an Article from a semantic Suggestion in the Self-Service portal.
     * | instant_answer | View an Article via an Instant Answers solution.
     * | instant_answer_reference | View an Article that is used as a reference for an Instant Answers
     * solution.
     */
    public GetArticleByIdRequest withAccessSource(@Nullable AccessSource accessSource) {
        this.accessSource = accessSource;
        return this;
    }


    /**
     * The ID of a publish view for an Article. A publish view is a set of tags used to generate multiple
     * editions of the same Article for display on the self-service portal. Publish views are used in
     * conjunction with single sourcing to tailor the content of an Article to a specific audience by
     * granting access to an Article's version to users that possess the same tags.<br><br>A publish view
     * ID is composed of a 4-letter prefix, followed by a dash and 4-15 digits.
     */
    public GetArticleByIdRequest withPublishViewId(@Nullable String publishViewId) {
        this.publishViewId = publishViewId;
        return this;
    }


    /**
     * For agents with the View Author Portal or View Staging Portal actions, this determines which version
     * of the Article is returned.<li>'Authoring' returns the most recent version of an Article checked-in
     * by an author.</li><li>'Staging' returns the updated version currently being processed in a
     * workflow.</li><li>'Publish' returns the most recently published version.</li>
     */
    public GetArticleByIdRequest withWorkflowMilestone(@Nullable WorkflowMilestone workflowMilestone) {
        this.workflowMilestone = workflowMilestone;
        return this;
    }


    @Override
    public boolean equals(java.lang.Object o) {
        if (this == o) {
            return true;
        }
        if (o == null || getClass() != o.getClass()) {
            return false;
        }
        GetArticleByIdRequest other = (GetArticleByIdRequest) o;
        return 
            Utils.enhancedDeepEquals(this.acceptLanguage, other.acceptLanguage) &&
            Utils.enhancedDeepEquals(this.portalID, other.portalID) &&
            Utils.enhancedDeepEquals(this.articleID, other.articleID) &&
            Utils.enhancedDeepEquals(this.language, other.language) &&
            Utils.enhancedDeepEquals(this.articleAdditionalAttributes, other.articleAdditionalAttributes) &&
            Utils.enhancedDeepEquals(this.customAdditionalAttributes, other.customAdditionalAttributes) &&
            Utils.enhancedDeepEquals(this.accessSource, other.accessSource) &&
            Utils.enhancedDeepEquals(this.publishViewId, other.publishViewId) &&
            Utils.enhancedDeepEquals(this.workflowMilestone, other.workflowMilestone);
    }
    
    @Override
    public int hashCode() {
        return Utils.enhancedHash(
            acceptLanguage, portalID, articleID,
            language, articleAdditionalAttributes, customAdditionalAttributes,
            accessSource, publishViewId, workflowMilestone);
    }
    
    @Override
    public String toString() {
        return Utils.toString(GetArticleByIdRequest.class,
                "acceptLanguage", acceptLanguage,
                "portalID", portalID,
                "articleID", articleID,
                "language", language,
                "articleAdditionalAttributes", articleAdditionalAttributes,
                "customAdditionalAttributes", customAdditionalAttributes,
                "accessSource", accessSource,
                "publishViewId", publishViewId,
                "workflowMilestone", workflowMilestone);
    }

    @SuppressWarnings("UnusedReturnValue")
    public final static class Builder {

        private AcceptLanguage acceptLanguage;

        private String portalID;

        private String articleID;

        private LanguageQueryParameter language;

        private List<ArticleAdditionalAttributes> articleAdditionalAttributes;

        private String customAdditionalAttributes;

        private AccessSource accessSource;

        private String publishViewId;

        private WorkflowMilestone workflowMilestone;

        private Builder() {
          // force use of static builder() method
        }

        /**
         * The Language locale accepted by the client (used for locale specific fields in resource
         * representation and in error responses).
         */
        public Builder acceptLanguage(@Nonnull AcceptLanguage acceptLanguage) {
            this.acceptLanguage = Utils.checkNotNull(acceptLanguage, "acceptLanguage");
            return this;
        }

        /**
         * The ID of the portal being accessed.<br><br>A portal ID is composed of a 2-4 letter prefix, followed
         * by a dash and 4-15 digits.
         */
        public Builder portalID(@Nonnull String portalID) {
            this.portalID = Utils.checkNotNull(portalID, "portalID");
            return this;
        }

        /**
         * The ID of the Article.<br><br>An Article ID is composed of a 2-4 letter prefix followed by a dash
         * and 4-15 digits.
         */
        public Builder articleID(@Nonnull String articleID) {
            this.articleID = Utils.checkNotNull(articleID, "articleID");
            return this;
        }

        /**
         * The language that describes the details of a resource. Resources available in different languages
         * may differ from each other.<li>If <code>lang</code> is not passed, then the portal's default
         * language is used.&lt;/li&gt;
         */
        public Builder language(@Nullable LanguageQueryParameter language) {
            this.language = language;
            return this;
        }

        /**
         * The attributes of an Article to be returned *in addition to* the default list of attributes, listed
         * below. Multiple additional attributes can be specified using a comma-separated list. Passing 'all'
         * will return all attributes.
         * 
         * <p>#### Default Attributes
         * These Article attributes are always returned:
         * 
         * <p>| Name | Description
         * | ---- | -----------
         * | id | The ID of the Article.
         * | name  | The name of the Article.
         * | additionalInfo | Additional information provided as Article metadata.
         * | articleType | The Article type and its attributes.
         * | articleKeywords | A comma-separated list of keywords associated with this Article.
         * | articleState | The current state of the Article. States include A (Authoring), S (Staging), and P
         * (Published).
         * | articleSummary | A brief summary of the Article, provided as metadata.
         * | createdBy | The ID, first name, middle name and last name of the user that created the Article.
         * | createdDate | The date that the Article was created.
         * | departmentId | ID of the department for which this Article belongs to.
         * | description | The Article's description.
         * | expirationDate | The date that the Article is set to expire.
         * | attachments | The Article's attachments
         * | imageURL | The URL of the image that is present in the Article version. It is used as the
         * thumbnail image for the Article.
         * | includeInGenAI | Indicates whether this Article is used for eGain's generative AI features.
         * | isSubscribed | Indicates whether the Article is subscribed for notifications.
         * | languageCode | The language code of the Article language.
         * | link | The link object, used to retrieve the details of the Article.
         * | modifiedBy | The ID, first name, middle name and last name of the user that last modified the
         * Article.
         * | modifiedDate | The date that the Article was last modified on.
         * | topicBreadcrumb | Contains a list of topics from the top-level topic to this Article. There may be
         * multiple paths.
         * | versionId | The ID of the Article version that is returned.
         */
        public Builder articleAdditionalAttributes(@Nullable List<ArticleAdditionalAttributes> articleAdditionalAttributes) {
            this.articleAdditionalAttributes = articleAdditionalAttributes;
            return this;
        }

        public Builder customAdditionalAttributes(@Nullable String customAdditionalAttributes) {
            this.customAdditionalAttributes = customAdditionalAttributes;
            return this;
        }

        /**
         * Provides information about the method in which the Article is accessed and is used for self-service
         * analytics. Refer to the eGain User Guide regarding "Article View Contexts".
         * 
         * <p>| Name | Description
         * | ---- | -----------
         * | article_view | View an Article directly using its ID.
         * | article_view_more_related_Article  | View related articles of an Article using its ID.
         * | article_view_basic_search | View an Article via a basic search.
         * | article_view_adv_search | View an Article via an advanced search.
         * | article_view_guided_help | View an Article via a Guided Help solution.
         * | article_view_browse_topic | View an Article via browsing a topic.
         * | article_view_browse_tree | View an Article via browsing a topic tree.
         * | article_view_popular_articles | View an Article using the Popular Items list in the Self-Service
         * portal.
         * | article_view_useful_items | View Article using the Useful Items list in the Self-Service portal.
         * | article_view_widget | View an Article via a widget.
         * | article_view_announcement | View an Article from the announcement section in the Self-Service
         * portal.
         * | article_view_bookmarked | View a bookmarked Article.
         * | article_view_subscription_notification | View an Article from a subscription notification.
         * | article_view_guided_help_additional_info | View an Article via additional information from a
         * Guided Help search.
         * | view_articles_pending_compliance | View an Article via Read &amp; Sign in the Self-Service portal.
         * | type_ahead_Suggestion | View an Article from a type-ahead Suggestion in the Self-Service portal.
         * | semantic_Suggestion | View an Article from a semantic Suggestion in the Self-Service portal.
         * | instant_answer | View an Article via an Instant Answers solution.
         * | instant_answer_reference | View an Article that is used as a reference for an Instant Answers
         * solution.
         */
        public Builder accessSource(@Nullable AccessSource accessSource) {
            this.accessSource = accessSource;
            return this;
        }

        /**
         * The ID of a publish view for an Article. A publish view is a set of tags used to generate multiple
         * editions of the same Article for display on the self-service portal. Publish views are used in
         * conjunction with single sourcing to tailor the content of an Article to a specific audience by
         * granting access to an Article's version to users that possess the same tags.<br><br>A publish view
         * ID is composed of a 4-letter prefix, followed by a dash and 4-15 digits.
         */
        public Builder publishViewId(@Nullable String publishViewId) {
            this.publishViewId = publishViewId;
            return this;
        }

        /**
         * For agents with the View Author Portal or View Staging Portal actions, this determines which version
         * of the Article is returned.<li>'Authoring' returns the most recent version of an Article checked-in
         * by an author.</li><li>'Staging' returns the updated version currently being processed in a
         * workflow.</li><li>'Publish' returns the most recently published version.</li>
         */
        public Builder workflowMilestone(@Nullable WorkflowMilestone workflowMilestone) {
            this.workflowMilestone = workflowMilestone;
            return this;
        }

        public GetArticleByIdRequest build() {
            return new GetArticleByIdRequest(
                acceptLanguage, portalID, articleID,
                language, articleAdditionalAttributes, customAdditionalAttributes,
                accessSource, publishViewId, workflowMilestone);
        }


        private static final LazySingletonValue<AccessSource> _SINGLETON_VALUE_AccessSource =
                new LazySingletonValue<>(
                        "accessSource",
                        "\"article_view\"",
                        new TypeReference<AccessSource>() {});
    }
}
