/* 
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */
package com.egain.sdk.models.operations;

import static com.egain.sdk.operations.Operations.RequestOperation;

import com.egain.sdk.SDKConfiguration;
import com.egain.sdk.models.components.AcceptLanguage;
import com.egain.sdk.operations.GetArticlePermissionsById;
import com.egain.sdk.utils.Headers;
import com.egain.sdk.utils.Utils;
import jakarta.annotation.Nonnull;
import java.lang.String;

public class GetArticlePermissionsByIdRequestBuilder {
    private final SDKConfiguration sdkConfiguration;
    private final Headers _headers = new Headers();
    private final GetArticlePermissionsByIdRequest.Builder pojoBuilder;
    private GetArticlePermissionsByIdRequest request;
    private boolean _setterCalled;

    public GetArticlePermissionsByIdRequestBuilder(SDKConfiguration sdkConfiguration) {
        this.sdkConfiguration = sdkConfiguration;
        this.pojoBuilder = GetArticlePermissionsByIdRequest.builder();
    }

    public GetArticlePermissionsByIdRequestBuilder acceptLanguage(@Nonnull AcceptLanguage acceptLanguage) {
        this.pojoBuilder.acceptLanguage(acceptLanguage);
        this._setterCalled = true;
        return this;
    }

    public GetArticlePermissionsByIdRequestBuilder portalID(@Nonnull String portalID) {
        this.pojoBuilder.portalID(portalID);
        this._setterCalled = true;
        return this;
    }

    public GetArticlePermissionsByIdRequestBuilder articleID(@Nonnull String articleID) {
        this.pojoBuilder.articleID(articleID);
        this._setterCalled = true;
        return this;
    }

    private GetArticlePermissionsByIdRequest _buildRequest() {
        if (this._setterCalled) {
            this.request = this.pojoBuilder.build();
        }
        return this.request;
    }
    
    public GetArticlePermissionsByIdRequestBuilder header(String name, String value) {
        Utils.checkNotNull(name, "name");
        Utils.checkNotNull(value, "value");
        this._headers.add(name, value);
        return this;
    }

    /**
    * Executes the request and returns the response.
    *
    * @return The response from the server.
    */
    public GetArticlePermissionsByIdResponse call() {
        RequestOperation<GetArticlePermissionsByIdRequest, GetArticlePermissionsByIdResponse> operation
              = new GetArticlePermissionsById.Sync(sdkConfiguration, _headers);
        return operation.handleResponse(operation.doRequest(this._buildRequest()));
    }
}
