/* 
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */
package com.egain.sdk.models.operations;

import com.egain.sdk.models.components.AcceptLanguage;
import com.egain.sdk.models.components.LanguageQueryParameter;
import com.egain.sdk.utils.LazySingletonValue;
import com.egain.sdk.utils.SpeakeasyMetadata;
import com.egain.sdk.utils.Utils;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.core.type.TypeReference;
import jakarta.annotation.Nonnull;
import jakarta.annotation.Nullable;
import java.lang.Boolean;
import java.lang.Long;
import java.lang.Override;
import java.lang.String;
import java.util.Optional;


public class GetAllQuickPicksRequest {
    /**
     * The Language locale accepted by the client (used for locale specific fields in resource
     * representation and in error responses).
     */
    @SpeakeasyMetadata("header:style=simple,explode=false,name=Accept-Language")
    private AcceptLanguage acceptLanguage;

    /**
     * The numerical ID of the Casebase Release for which details is to be fetched.
     */
    @SpeakeasyMetadata("queryParam:style=form,explode=true,name=casebaseReleaseID")
    private String casebaseReleaseID;

    /**
     * The ID of the portal being accessed.<br><br>A portal ID is composed of a 2-4 letter prefix, followed
     * by a dash and 4-15 digits.
     */
    @SpeakeasyMetadata("pathParam:style=simple,explode=false,name=portalID")
    private String portalID;

    /**
     * The language that describes the details of a resource. Resources available in different languages
     * may differ from each other.<li>If <code>lang</code> is not passed, then the portal's default
     * language is used.&lt;/li&gt;
     */
    @SpeakeasyMetadata("queryParam:style=form,explode=true,name=$lang")
    private LanguageQueryParameter language;

    /**
     * Pagination parameter that specifies the page number of results to be returned. Used in conjunction
     * with $pagesize.
     */
    @SpeakeasyMetadata("queryParam:style=form,explode=true,name=$pagenum")
    private Long pagenum;

    /**
     * Pagination parameter that specifies the number of results per page. Used in conjunction with
     * $pagenum.
     */
    @SpeakeasyMetadata("queryParam:style=form,explode=true,name=$pagesize")
    private Long pagesize;

    /**
     * To be passed retrieve quickpick associated with interaction.
     */
    @SpeakeasyMetadata("queryParam:style=form,explode=true,name=getLastSavedQuickPickForInteraction")
    private Boolean getLastSavedQuickPickForInteraction;

    @JsonCreator
    public GetAllQuickPicksRequest(
            @Nonnull AcceptLanguage acceptLanguage,
            @Nonnull String casebaseReleaseID,
            @Nonnull String portalID,
            @Nullable LanguageQueryParameter language,
            @Nullable Long pagenum,
            @Nullable Long pagesize,
            @Nullable Boolean getLastSavedQuickPickForInteraction) {
        this.acceptLanguage = Optional.ofNullable(acceptLanguage)
            .orElseThrow(() -> new IllegalArgumentException("acceptLanguage cannot be null"));
        this.casebaseReleaseID = Optional.ofNullable(casebaseReleaseID)
            .orElseThrow(() -> new IllegalArgumentException("casebaseReleaseID cannot be null"));
        this.portalID = Optional.ofNullable(portalID)
            .orElseThrow(() -> new IllegalArgumentException("portalID cannot be null"));
        this.language = language;
        this.pagenum = Optional.ofNullable(pagenum)
            .orElse(Builder._SINGLETON_VALUE_Pagenum.value());
        this.pagesize = Optional.ofNullable(pagesize)
            .orElse(Builder._SINGLETON_VALUE_Pagesize.value());
        this.getLastSavedQuickPickForInteraction = getLastSavedQuickPickForInteraction;
    }
    
    public GetAllQuickPicksRequest(
            @Nonnull AcceptLanguage acceptLanguage,
            @Nonnull String casebaseReleaseID,
            @Nonnull String portalID) {
        this(acceptLanguage, casebaseReleaseID, portalID,
            null, null, null,
            null);
    }

    /**
     * The Language locale accepted by the client (used for locale specific fields in resource
     * representation and in error responses).
     */
    public AcceptLanguage acceptLanguage() {
        return this.acceptLanguage;
    }

    /**
     * The numerical ID of the Casebase Release for which details is to be fetched.
     */
    public String casebaseReleaseID() {
        return this.casebaseReleaseID;
    }

    /**
     * The ID of the portal being accessed.<br><br>A portal ID is composed of a 2-4 letter prefix, followed
     * by a dash and 4-15 digits.
     */
    public String portalID() {
        return this.portalID;
    }

    /**
     * The language that describes the details of a resource. Resources available in different languages
     * may differ from each other.<li>If <code>lang</code> is not passed, then the portal's default
     * language is used.&lt;/li&gt;
     */
    public Optional<LanguageQueryParameter> language() {
        return Optional.ofNullable(this.language);
    }

    /**
     * Pagination parameter that specifies the page number of results to be returned. Used in conjunction
     * with $pagesize.
     */
    public Optional<Long> pagenum() {
        return Optional.ofNullable(this.pagenum);
    }

    /**
     * Pagination parameter that specifies the number of results per page. Used in conjunction with
     * $pagenum.
     */
    public Optional<Long> pagesize() {
        return Optional.ofNullable(this.pagesize);
    }

    /**
     * To be passed retrieve quickpick associated with interaction.
     */
    public Optional<Boolean> getLastSavedQuickPickForInteraction() {
        return Optional.ofNullable(this.getLastSavedQuickPickForInteraction);
    }

    public static Builder builder() {
        return new Builder();
    }


    /**
     * The Language locale accepted by the client (used for locale specific fields in resource
     * representation and in error responses).
     */
    public GetAllQuickPicksRequest withAcceptLanguage(@Nonnull AcceptLanguage acceptLanguage) {
        this.acceptLanguage = Utils.checkNotNull(acceptLanguage, "acceptLanguage");
        return this;
    }


    /**
     * The numerical ID of the Casebase Release for which details is to be fetched.
     */
    public GetAllQuickPicksRequest withCasebaseReleaseID(@Nonnull String casebaseReleaseID) {
        this.casebaseReleaseID = Utils.checkNotNull(casebaseReleaseID, "casebaseReleaseID");
        return this;
    }


    /**
     * The ID of the portal being accessed.<br><br>A portal ID is composed of a 2-4 letter prefix, followed
     * by a dash and 4-15 digits.
     */
    public GetAllQuickPicksRequest withPortalID(@Nonnull String portalID) {
        this.portalID = Utils.checkNotNull(portalID, "portalID");
        return this;
    }


    /**
     * The language that describes the details of a resource. Resources available in different languages
     * may differ from each other.<li>If <code>lang</code> is not passed, then the portal's default
     * language is used.&lt;/li&gt;
     */
    public GetAllQuickPicksRequest withLanguage(@Nullable LanguageQueryParameter language) {
        this.language = language;
        return this;
    }


    /**
     * Pagination parameter that specifies the page number of results to be returned. Used in conjunction
     * with $pagesize.
     */
    public GetAllQuickPicksRequest withPagenum(@Nullable Long pagenum) {
        this.pagenum = pagenum;
        return this;
    }


    /**
     * Pagination parameter that specifies the number of results per page. Used in conjunction with
     * $pagenum.
     */
    public GetAllQuickPicksRequest withPagesize(@Nullable Long pagesize) {
        this.pagesize = pagesize;
        return this;
    }


    /**
     * To be passed retrieve quickpick associated with interaction.
     */
    public GetAllQuickPicksRequest withGetLastSavedQuickPickForInteraction(@Nullable Boolean getLastSavedQuickPickForInteraction) {
        this.getLastSavedQuickPickForInteraction = getLastSavedQuickPickForInteraction;
        return this;
    }


    @Override
    public boolean equals(java.lang.Object o) {
        if (this == o) {
            return true;
        }
        if (o == null || getClass() != o.getClass()) {
            return false;
        }
        GetAllQuickPicksRequest other = (GetAllQuickPicksRequest) o;
        return 
            Utils.enhancedDeepEquals(this.acceptLanguage, other.acceptLanguage) &&
            Utils.enhancedDeepEquals(this.casebaseReleaseID, other.casebaseReleaseID) &&
            Utils.enhancedDeepEquals(this.portalID, other.portalID) &&
            Utils.enhancedDeepEquals(this.language, other.language) &&
            Utils.enhancedDeepEquals(this.pagenum, other.pagenum) &&
            Utils.enhancedDeepEquals(this.pagesize, other.pagesize) &&
            Utils.enhancedDeepEquals(this.getLastSavedQuickPickForInteraction, other.getLastSavedQuickPickForInteraction);
    }
    
    @Override
    public int hashCode() {
        return Utils.enhancedHash(
            acceptLanguage, casebaseReleaseID, portalID,
            language, pagenum, pagesize,
            getLastSavedQuickPickForInteraction);
    }
    
    @Override
    public String toString() {
        return Utils.toString(GetAllQuickPicksRequest.class,
                "acceptLanguage", acceptLanguage,
                "casebaseReleaseID", casebaseReleaseID,
                "portalID", portalID,
                "language", language,
                "pagenum", pagenum,
                "pagesize", pagesize,
                "getLastSavedQuickPickForInteraction", getLastSavedQuickPickForInteraction);
    }

    @SuppressWarnings("UnusedReturnValue")
    public final static class Builder {

        private AcceptLanguage acceptLanguage;

        private String casebaseReleaseID;

        private String portalID;

        private LanguageQueryParameter language;

        private Long pagenum;

        private Long pagesize;

        private Boolean getLastSavedQuickPickForInteraction;

        private Builder() {
          // force use of static builder() method
        }

        /**
         * The Language locale accepted by the client (used for locale specific fields in resource
         * representation and in error responses).
         */
        public Builder acceptLanguage(@Nonnull AcceptLanguage acceptLanguage) {
            this.acceptLanguage = Utils.checkNotNull(acceptLanguage, "acceptLanguage");
            return this;
        }

        /**
         * The numerical ID of the Casebase Release for which details is to be fetched.
         */
        public Builder casebaseReleaseID(@Nonnull String casebaseReleaseID) {
            this.casebaseReleaseID = Utils.checkNotNull(casebaseReleaseID, "casebaseReleaseID");
            return this;
        }

        /**
         * The ID of the portal being accessed.<br><br>A portal ID is composed of a 2-4 letter prefix, followed
         * by a dash and 4-15 digits.
         */
        public Builder portalID(@Nonnull String portalID) {
            this.portalID = Utils.checkNotNull(portalID, "portalID");
            return this;
        }

        /**
         * The language that describes the details of a resource. Resources available in different languages
         * may differ from each other.<li>If <code>lang</code> is not passed, then the portal's default
         * language is used.&lt;/li&gt;
         */
        public Builder language(@Nullable LanguageQueryParameter language) {
            this.language = language;
            return this;
        }

        /**
         * Pagination parameter that specifies the page number of results to be returned. Used in conjunction
         * with $pagesize.
         */
        public Builder pagenum(@Nullable Long pagenum) {
            this.pagenum = pagenum;
            return this;
        }

        /**
         * Pagination parameter that specifies the number of results per page. Used in conjunction with
         * $pagenum.
         */
        public Builder pagesize(@Nullable Long pagesize) {
            this.pagesize = pagesize;
            return this;
        }

        /**
         * To be passed retrieve quickpick associated with interaction.
         */
        public Builder getLastSavedQuickPickForInteraction(@Nullable Boolean getLastSavedQuickPickForInteraction) {
            this.getLastSavedQuickPickForInteraction = getLastSavedQuickPickForInteraction;
            return this;
        }

        public GetAllQuickPicksRequest build() {
            return new GetAllQuickPicksRequest(
                acceptLanguage, casebaseReleaseID, portalID,
                language, pagenum, pagesize,
                getLastSavedQuickPickForInteraction);
        }


        private static final LazySingletonValue<Long> _SINGLETON_VALUE_Pagenum =
                new LazySingletonValue<>(
                        "pagenum",
                        "1",
                        new TypeReference<Long>() {});

        private static final LazySingletonValue<Long> _SINGLETON_VALUE_Pagesize =
                new LazySingletonValue<>(
                        "pagesize",
                        "10",
                        new TypeReference<Long>() {});
    }
}
