/* 
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */
package com.egain.sdk.models.operations;

import static com.egain.sdk.operations.Operations.RequestOperation;

import com.egain.sdk.SDKConfiguration;
import com.egain.sdk.operations.Getchildtopics;
import com.egain.sdk.utils.Headers;
import com.egain.sdk.utils.Utils;
import jakarta.annotation.Nonnull;

public class GetchildtopicsRequestBuilder {
    private final SDKConfiguration sdkConfiguration;
    private final Headers _headers = new Headers();
    private GetchildtopicsRequest request;

    public GetchildtopicsRequestBuilder(SDKConfiguration sdkConfiguration) {
        this.sdkConfiguration = sdkConfiguration;
    }

    public GetchildtopicsRequestBuilder request(@Nonnull GetchildtopicsRequest request) {
        this.request = Utils.checkNotNull(request, "request");
        return this;
    }

    private GetchildtopicsRequest _buildRequest() {
        return this.request;
    }
    
    public GetchildtopicsRequestBuilder header(String name, String value) {
        Utils.checkNotNull(name, "name");
        Utils.checkNotNull(value, "value");
        this._headers.add(name, value);
        return this;
    }

    /**
    * Executes the request and returns the response.
    *
    * @return The response from the server.
    */
    public GetchildtopicsResponse call() {
        RequestOperation<GetchildtopicsRequest, GetchildtopicsResponse> operation
              = new Getchildtopics.Sync(sdkConfiguration, _headers);
        return operation.handleResponse(operation.doRequest(this._buildRequest()));
    }
}
