/* 
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */
package com.egain.sdk.models.operations;

import com.egain.sdk.models.components.AcceptLanguage;
import com.egain.sdk.models.components.ArticleResultAdditionalAttributes;
import com.egain.sdk.models.components.LanguageQueryParameter;
import com.egain.sdk.utils.LazySingletonValue;
import com.egain.sdk.utils.SpeakeasyMetadata;
import com.egain.sdk.utils.Utils;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.core.type.TypeReference;
import jakarta.annotation.Nonnull;
import jakarta.annotation.Nullable;
import java.lang.Long;
import java.lang.Override;
import java.lang.String;
import java.util.List;
import java.util.Optional;


public class GetpopulararticlesRequest {
    /**
     * The Language locale accepted by the client (used for locale specific fields in resource
     * representation and in error responses).
     */
    @SpeakeasyMetadata("header:style=simple,explode=false,name=Accept-Language")
    private AcceptLanguage acceptLanguage;

    /**
     * The ID of the portal being accessed.<br><br>A portal ID is composed of a 2-4 letter prefix, followed
     * by a dash and 4-15 digits.
     */
    @SpeakeasyMetadata("pathParam:style=simple,explode=false,name=portalID")
    private String portalID;

    /**
     * The ID of the topic. It is used to restrict to a specific topic.
     */
    @SpeakeasyMetadata("queryParam:style=form,explode=true,name=$filter[topicId]")
    private String filterTopicId;

    /**
     * The language that describes the details of a resource. Resources available in different languages
     * may differ from each other.<li>If <code>lang</code> is not passed, then the portal's default
     * language is used.&lt;/li&gt;
     */
    @SpeakeasyMetadata("queryParam:style=form,explode=true,name=$lang")
    private LanguageQueryParameter language;

    /**
     * A comma separated list of Tag / Tag Group IDs. The query results will be filtered by the tags that
     * are specified.<br><br>Tag IDs and Tag Group IDs can be mixed together.
     */
    @SpeakeasyMetadata("queryParam:style=form,explode=true,name=$filter[tags]")
    private String filterTags;

    /**
     * Pagination parameter that specifies the page number of results to be returned. Used in conjunction
     * with $pagesize.
     */
    @SpeakeasyMetadata("queryParam:style=form,explode=true,name=$pagenum")
    private Long pagenum;

    /**
     * Pagination parameter that specifies the number of results per page. Used in conjunction with
     * $pagenum.
     */
    @SpeakeasyMetadata("queryParam:style=form,explode=true,name=$pagesize")
    private Long pagesize;

    /**
     * The attributes of an Article to be returned *in addition to* the default list of attributes, listed
     * below. Multiple additional attributes can be specified using a comma-separated list. Passing 'all'
     * will return all attributes.
     * 
     * <p>#### Default Attributes
     * These Article attributes are always returned:
     * 
     * <p>| Name | Description
     * | ---- | -----------
     * | id | The ID of the Article.
     * | name  | The name of the Article.
     * | articleType | The Article Type and its attributes.
     * | createdBy | The ID, first name, middle name and last name of the user that created the Article.
     * | createdDate | The date that the Article was created.
     * | hasAttachments | True: The Article has one or more attachments.<br>False: The Article does not
     * have any attachments.
     * | languageCode | The language code of the Article language.
     * | modifiedBy | The ID, first name, middle name and last name of the user that last modified the
     * Article.
     * | modifiedDate | The date that the Article was last modified on.
     * | link | The link object, used to retrieve the details of the Article.
     * | versionId | The ID of the Article version that is returned.
     */
    @SpeakeasyMetadata("queryParam:style=form,explode=false,name=articleResultAdditionalAttributes")
    private List<ArticleResultAdditionalAttributes> articleResultAdditionalAttributes;

    @JsonCreator
    public GetpopulararticlesRequest(
            @Nonnull AcceptLanguage acceptLanguage,
            @Nonnull String portalID,
            @Nullable String filterTopicId,
            @Nullable LanguageQueryParameter language,
            @Nullable String filterTags,
            @Nullable Long pagenum,
            @Nullable Long pagesize,
            @Nullable List<ArticleResultAdditionalAttributes> articleResultAdditionalAttributes) {
        this.acceptLanguage = Optional.ofNullable(acceptLanguage)
            .orElseThrow(() -> new IllegalArgumentException("acceptLanguage cannot be null"));
        this.portalID = Optional.ofNullable(portalID)
            .orElseThrow(() -> new IllegalArgumentException("portalID cannot be null"));
        this.filterTopicId = filterTopicId;
        this.language = language;
        this.filterTags = filterTags;
        this.pagenum = Optional.ofNullable(pagenum)
            .orElse(Builder._SINGLETON_VALUE_Pagenum.value());
        this.pagesize = Optional.ofNullable(pagesize)
            .orElse(Builder._SINGLETON_VALUE_Pagesize.value());
        this.articleResultAdditionalAttributes = articleResultAdditionalAttributes;
    }
    
    public GetpopulararticlesRequest(
            @Nonnull AcceptLanguage acceptLanguage,
            @Nonnull String portalID) {
        this(acceptLanguage, portalID, null,
            null, null, null,
            null, null);
    }

    /**
     * The Language locale accepted by the client (used for locale specific fields in resource
     * representation and in error responses).
     */
    public AcceptLanguage acceptLanguage() {
        return this.acceptLanguage;
    }

    /**
     * The ID of the portal being accessed.<br><br>A portal ID is composed of a 2-4 letter prefix, followed
     * by a dash and 4-15 digits.
     */
    public String portalID() {
        return this.portalID;
    }

    /**
     * The ID of the topic. It is used to restrict to a specific topic.
     */
    public Optional<String> filterTopicId() {
        return Optional.ofNullable(this.filterTopicId);
    }

    /**
     * The language that describes the details of a resource. Resources available in different languages
     * may differ from each other.<li>If <code>lang</code> is not passed, then the portal's default
     * language is used.&lt;/li&gt;
     */
    public Optional<LanguageQueryParameter> language() {
        return Optional.ofNullable(this.language);
    }

    /**
     * A comma separated list of Tag / Tag Group IDs. The query results will be filtered by the tags that
     * are specified.<br><br>Tag IDs and Tag Group IDs can be mixed together.
     */
    public Optional<String> filterTags() {
        return Optional.ofNullable(this.filterTags);
    }

    /**
     * Pagination parameter that specifies the page number of results to be returned. Used in conjunction
     * with $pagesize.
     */
    public Optional<Long> pagenum() {
        return Optional.ofNullable(this.pagenum);
    }

    /**
     * Pagination parameter that specifies the number of results per page. Used in conjunction with
     * $pagenum.
     */
    public Optional<Long> pagesize() {
        return Optional.ofNullable(this.pagesize);
    }

    /**
     * The attributes of an Article to be returned *in addition to* the default list of attributes, listed
     * below. Multiple additional attributes can be specified using a comma-separated list. Passing 'all'
     * will return all attributes.
     * 
     * <p>#### Default Attributes
     * These Article attributes are always returned:
     * 
     * <p>| Name | Description
     * | ---- | -----------
     * | id | The ID of the Article.
     * | name  | The name of the Article.
     * | articleType | The Article Type and its attributes.
     * | createdBy | The ID, first name, middle name and last name of the user that created the Article.
     * | createdDate | The date that the Article was created.
     * | hasAttachments | True: The Article has one or more attachments.<br>False: The Article does not
     * have any attachments.
     * | languageCode | The language code of the Article language.
     * | modifiedBy | The ID, first name, middle name and last name of the user that last modified the
     * Article.
     * | modifiedDate | The date that the Article was last modified on.
     * | link | The link object, used to retrieve the details of the Article.
     * | versionId | The ID of the Article version that is returned.
     */
    public Optional<List<ArticleResultAdditionalAttributes>> articleResultAdditionalAttributes() {
        return Optional.ofNullable(this.articleResultAdditionalAttributes);
    }

    public static Builder builder() {
        return new Builder();
    }


    /**
     * The Language locale accepted by the client (used for locale specific fields in resource
     * representation and in error responses).
     */
    public GetpopulararticlesRequest withAcceptLanguage(@Nonnull AcceptLanguage acceptLanguage) {
        this.acceptLanguage = Utils.checkNotNull(acceptLanguage, "acceptLanguage");
        return this;
    }


    /**
     * The ID of the portal being accessed.<br><br>A portal ID is composed of a 2-4 letter prefix, followed
     * by a dash and 4-15 digits.
     */
    public GetpopulararticlesRequest withPortalID(@Nonnull String portalID) {
        this.portalID = Utils.checkNotNull(portalID, "portalID");
        return this;
    }


    /**
     * The ID of the topic. It is used to restrict to a specific topic.
     */
    public GetpopulararticlesRequest withFilterTopicId(@Nullable String filterTopicId) {
        this.filterTopicId = filterTopicId;
        return this;
    }


    /**
     * The language that describes the details of a resource. Resources available in different languages
     * may differ from each other.<li>If <code>lang</code> is not passed, then the portal's default
     * language is used.&lt;/li&gt;
     */
    public GetpopulararticlesRequest withLanguage(@Nullable LanguageQueryParameter language) {
        this.language = language;
        return this;
    }


    /**
     * A comma separated list of Tag / Tag Group IDs. The query results will be filtered by the tags that
     * are specified.<br><br>Tag IDs and Tag Group IDs can be mixed together.
     */
    public GetpopulararticlesRequest withFilterTags(@Nullable String filterTags) {
        this.filterTags = filterTags;
        return this;
    }


    /**
     * Pagination parameter that specifies the page number of results to be returned. Used in conjunction
     * with $pagesize.
     */
    public GetpopulararticlesRequest withPagenum(@Nullable Long pagenum) {
        this.pagenum = pagenum;
        return this;
    }


    /**
     * Pagination parameter that specifies the number of results per page. Used in conjunction with
     * $pagenum.
     */
    public GetpopulararticlesRequest withPagesize(@Nullable Long pagesize) {
        this.pagesize = pagesize;
        return this;
    }


    /**
     * The attributes of an Article to be returned *in addition to* the default list of attributes, listed
     * below. Multiple additional attributes can be specified using a comma-separated list. Passing 'all'
     * will return all attributes.
     * 
     * <p>#### Default Attributes
     * These Article attributes are always returned:
     * 
     * <p>| Name | Description
     * | ---- | -----------
     * | id | The ID of the Article.
     * | name  | The name of the Article.
     * | articleType | The Article Type and its attributes.
     * | createdBy | The ID, first name, middle name and last name of the user that created the Article.
     * | createdDate | The date that the Article was created.
     * | hasAttachments | True: The Article has one or more attachments.<br>False: The Article does not
     * have any attachments.
     * | languageCode | The language code of the Article language.
     * | modifiedBy | The ID, first name, middle name and last name of the user that last modified the
     * Article.
     * | modifiedDate | The date that the Article was last modified on.
     * | link | The link object, used to retrieve the details of the Article.
     * | versionId | The ID of the Article version that is returned.
     */
    public GetpopulararticlesRequest withArticleResultAdditionalAttributes(@Nullable List<ArticleResultAdditionalAttributes> articleResultAdditionalAttributes) {
        this.articleResultAdditionalAttributes = articleResultAdditionalAttributes;
        return this;
    }


    @Override
    public boolean equals(java.lang.Object o) {
        if (this == o) {
            return true;
        }
        if (o == null || getClass() != o.getClass()) {
            return false;
        }
        GetpopulararticlesRequest other = (GetpopulararticlesRequest) o;
        return 
            Utils.enhancedDeepEquals(this.acceptLanguage, other.acceptLanguage) &&
            Utils.enhancedDeepEquals(this.portalID, other.portalID) &&
            Utils.enhancedDeepEquals(this.filterTopicId, other.filterTopicId) &&
            Utils.enhancedDeepEquals(this.language, other.language) &&
            Utils.enhancedDeepEquals(this.filterTags, other.filterTags) &&
            Utils.enhancedDeepEquals(this.pagenum, other.pagenum) &&
            Utils.enhancedDeepEquals(this.pagesize, other.pagesize) &&
            Utils.enhancedDeepEquals(this.articleResultAdditionalAttributes, other.articleResultAdditionalAttributes);
    }
    
    @Override
    public int hashCode() {
        return Utils.enhancedHash(
            acceptLanguage, portalID, filterTopicId,
            language, filterTags, pagenum,
            pagesize, articleResultAdditionalAttributes);
    }
    
    @Override
    public String toString() {
        return Utils.toString(GetpopulararticlesRequest.class,
                "acceptLanguage", acceptLanguage,
                "portalID", portalID,
                "filterTopicId", filterTopicId,
                "language", language,
                "filterTags", filterTags,
                "pagenum", pagenum,
                "pagesize", pagesize,
                "articleResultAdditionalAttributes", articleResultAdditionalAttributes);
    }

    @SuppressWarnings("UnusedReturnValue")
    public final static class Builder {

        private AcceptLanguage acceptLanguage;

        private String portalID;

        private String filterTopicId;

        private LanguageQueryParameter language;

        private String filterTags;

        private Long pagenum;

        private Long pagesize;

        private List<ArticleResultAdditionalAttributes> articleResultAdditionalAttributes;

        private Builder() {
          // force use of static builder() method
        }

        /**
         * The Language locale accepted by the client (used for locale specific fields in resource
         * representation and in error responses).
         */
        public Builder acceptLanguage(@Nonnull AcceptLanguage acceptLanguage) {
            this.acceptLanguage = Utils.checkNotNull(acceptLanguage, "acceptLanguage");
            return this;
        }

        /**
         * The ID of the portal being accessed.<br><br>A portal ID is composed of a 2-4 letter prefix, followed
         * by a dash and 4-15 digits.
         */
        public Builder portalID(@Nonnull String portalID) {
            this.portalID = Utils.checkNotNull(portalID, "portalID");
            return this;
        }

        /**
         * The ID of the topic. It is used to restrict to a specific topic.
         */
        public Builder filterTopicId(@Nullable String filterTopicId) {
            this.filterTopicId = filterTopicId;
            return this;
        }

        /**
         * The language that describes the details of a resource. Resources available in different languages
         * may differ from each other.<li>If <code>lang</code> is not passed, then the portal's default
         * language is used.&lt;/li&gt;
         */
        public Builder language(@Nullable LanguageQueryParameter language) {
            this.language = language;
            return this;
        }

        /**
         * A comma separated list of Tag / Tag Group IDs. The query results will be filtered by the tags that
         * are specified.<br><br>Tag IDs and Tag Group IDs can be mixed together.
         */
        public Builder filterTags(@Nullable String filterTags) {
            this.filterTags = filterTags;
            return this;
        }

        /**
         * Pagination parameter that specifies the page number of results to be returned. Used in conjunction
         * with $pagesize.
         */
        public Builder pagenum(@Nullable Long pagenum) {
            this.pagenum = pagenum;
            return this;
        }

        /**
         * Pagination parameter that specifies the number of results per page. Used in conjunction with
         * $pagenum.
         */
        public Builder pagesize(@Nullable Long pagesize) {
            this.pagesize = pagesize;
            return this;
        }

        /**
         * The attributes of an Article to be returned *in addition to* the default list of attributes, listed
         * below. Multiple additional attributes can be specified using a comma-separated list. Passing 'all'
         * will return all attributes.
         * 
         * <p>#### Default Attributes
         * These Article attributes are always returned:
         * 
         * <p>| Name | Description
         * | ---- | -----------
         * | id | The ID of the Article.
         * | name  | The name of the Article.
         * | articleType | The Article Type and its attributes.
         * | createdBy | The ID, first name, middle name and last name of the user that created the Article.
         * | createdDate | The date that the Article was created.
         * | hasAttachments | True: The Article has one or more attachments.<br>False: The Article does not
         * have any attachments.
         * | languageCode | The language code of the Article language.
         * | modifiedBy | The ID, first name, middle name and last name of the user that last modified the
         * Article.
         * | modifiedDate | The date that the Article was last modified on.
         * | link | The link object, used to retrieve the details of the Article.
         * | versionId | The ID of the Article version that is returned.
         */
        public Builder articleResultAdditionalAttributes(@Nullable List<ArticleResultAdditionalAttributes> articleResultAdditionalAttributes) {
            this.articleResultAdditionalAttributes = articleResultAdditionalAttributes;
            return this;
        }

        public GetpopulararticlesRequest build() {
            return new GetpopulararticlesRequest(
                acceptLanguage, portalID, filterTopicId,
                language, filterTags, pagenum,
                pagesize, articleResultAdditionalAttributes);
        }


        private static final LazySingletonValue<Long> _SINGLETON_VALUE_Pagenum =
                new LazySingletonValue<>(
                        "pagenum",
                        "1",
                        new TypeReference<Long>() {});

        private static final LazySingletonValue<Long> _SINGLETON_VALUE_Pagesize =
                new LazySingletonValue<>(
                        "pagesize",
                        "10",
                        new TypeReference<Long>() {});
    }
}
