/* 
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */
package com.egain.sdk.models.operations;

import com.egain.sdk.models.components.AcceptLanguage;
import com.egain.sdk.models.components.SuggestionAdditionalAttributes;
import com.egain.sdk.utils.SpeakeasyMetadata;
import com.egain.sdk.utils.Utils;
import com.fasterxml.jackson.annotation.JsonCreator;
import jakarta.annotation.Nonnull;
import jakarta.annotation.Nullable;
import java.lang.Override;
import java.lang.String;
import java.util.List;
import java.util.Optional;


public class GetSuggestionRequest {
    /**
     * The Language locale accepted by the client (used for locale specific fields in resource
     * representation and in error responses).
     */
    @SpeakeasyMetadata("header:style=simple,explode=false,name=Accept-Language")
    private AcceptLanguage acceptLanguage;

    /**
     * The ID of the portal being accessed.<br><br>A portal ID is composed of a 2-4 letter prefix, followed
     * by a dash and 4-15 digits.
     */
    @SpeakeasyMetadata("pathParam:style=simple,explode=false,name=portalID")
    private String portalID;

    /**
     * The ID of the Suggestion.<br><br>A Suggestion ID is composed of a 2-4 letter prefix, followed by a
     * dash and 4-15 digits.
     */
    @SpeakeasyMetadata("pathParam:style=simple,explode=false,name=suggestionID")
    private String suggestionID;

    /**
     * The attributes of a Suggestion to be returned *in addition to* the default list of attributes,
     * listed below. Multiple additional attributes can be specified using a comma-separated list. Passing
     * 'all' returns all attributes.
     * 
     * <p>#### Default Attributes
     * These Suggestion attributes are always returned:
     * 
     * <p>| Name | Description
     * | ---- | -----------
     * | id | The ID of the Suggestion.
     * | name  | The name of the Suggestion.
     * | status | The status of the Suggestion.
     * | description | The description of the Suggestion.
     * | language | Details about the language of the Suggestion.
     * | modifiedBy.id | The ID of the user that last modified the Suggestion.
     * | modifiedBy.firstName | The Suggestion's last modified user's first name.
     * | modifiedBy.middleName | The Suggestion's last modified user's middle name.
     * | modifiedBy.lastName | The Suggestion's last modified user's last name.
     * | modifiedDate | The Suggestion's last modified date &lt;u&gt;and&lt;/u&gt; information about the
     * user that last modified the Suggestion.
     * | link | The link object, used to retrieve the details of the Suggestion.
     * | hasComments | The Suggestion has one or more comments
     * | hasAttachments | The Suggestion has one or more attachments
     * | hasRelatedArticles | The Suggestion has related articles
     */
    @SpeakeasyMetadata("queryParam:style=form,explode=false,name=suggestionAdditionalAttributes")
    private List<SuggestionAdditionalAttributes> suggestionAdditionalAttributes;


    @SpeakeasyMetadata("queryParam:style=form,explode=true,name=$customAdditionalAttributes")
    private String customAdditionalAttributes;

    @JsonCreator
    public GetSuggestionRequest(
            @Nonnull AcceptLanguage acceptLanguage,
            @Nonnull String portalID,
            @Nonnull String suggestionID,
            @Nullable List<SuggestionAdditionalAttributes> suggestionAdditionalAttributes,
            @Nullable String customAdditionalAttributes) {
        this.acceptLanguage = Optional.ofNullable(acceptLanguage)
            .orElseThrow(() -> new IllegalArgumentException("acceptLanguage cannot be null"));
        this.portalID = Optional.ofNullable(portalID)
            .orElseThrow(() -> new IllegalArgumentException("portalID cannot be null"));
        this.suggestionID = Optional.ofNullable(suggestionID)
            .orElseThrow(() -> new IllegalArgumentException("suggestionID cannot be null"));
        this.suggestionAdditionalAttributes = suggestionAdditionalAttributes;
        this.customAdditionalAttributes = customAdditionalAttributes;
    }
    
    public GetSuggestionRequest(
            @Nonnull AcceptLanguage acceptLanguage,
            @Nonnull String portalID,
            @Nonnull String suggestionID) {
        this(acceptLanguage, portalID, suggestionID,
            null, null);
    }

    /**
     * The Language locale accepted by the client (used for locale specific fields in resource
     * representation and in error responses).
     */
    public AcceptLanguage acceptLanguage() {
        return this.acceptLanguage;
    }

    /**
     * The ID of the portal being accessed.<br><br>A portal ID is composed of a 2-4 letter prefix, followed
     * by a dash and 4-15 digits.
     */
    public String portalID() {
        return this.portalID;
    }

    /**
     * The ID of the Suggestion.<br><br>A Suggestion ID is composed of a 2-4 letter prefix, followed by a
     * dash and 4-15 digits.
     */
    public String suggestionID() {
        return this.suggestionID;
    }

    /**
     * The attributes of a Suggestion to be returned *in addition to* the default list of attributes,
     * listed below. Multiple additional attributes can be specified using a comma-separated list. Passing
     * 'all' returns all attributes.
     * 
     * <p>#### Default Attributes
     * These Suggestion attributes are always returned:
     * 
     * <p>| Name | Description
     * | ---- | -----------
     * | id | The ID of the Suggestion.
     * | name  | The name of the Suggestion.
     * | status | The status of the Suggestion.
     * | description | The description of the Suggestion.
     * | language | Details about the language of the Suggestion.
     * | modifiedBy.id | The ID of the user that last modified the Suggestion.
     * | modifiedBy.firstName | The Suggestion's last modified user's first name.
     * | modifiedBy.middleName | The Suggestion's last modified user's middle name.
     * | modifiedBy.lastName | The Suggestion's last modified user's last name.
     * | modifiedDate | The Suggestion's last modified date &lt;u&gt;and&lt;/u&gt; information about the
     * user that last modified the Suggestion.
     * | link | The link object, used to retrieve the details of the Suggestion.
     * | hasComments | The Suggestion has one or more comments
     * | hasAttachments | The Suggestion has one or more attachments
     * | hasRelatedArticles | The Suggestion has related articles
     */
    public Optional<List<SuggestionAdditionalAttributes>> suggestionAdditionalAttributes() {
        return Optional.ofNullable(this.suggestionAdditionalAttributes);
    }

    public Optional<String> customAdditionalAttributes() {
        return Optional.ofNullable(this.customAdditionalAttributes);
    }

    public static Builder builder() {
        return new Builder();
    }


    /**
     * The Language locale accepted by the client (used for locale specific fields in resource
     * representation and in error responses).
     */
    public GetSuggestionRequest withAcceptLanguage(@Nonnull AcceptLanguage acceptLanguage) {
        this.acceptLanguage = Utils.checkNotNull(acceptLanguage, "acceptLanguage");
        return this;
    }


    /**
     * The ID of the portal being accessed.<br><br>A portal ID is composed of a 2-4 letter prefix, followed
     * by a dash and 4-15 digits.
     */
    public GetSuggestionRequest withPortalID(@Nonnull String portalID) {
        this.portalID = Utils.checkNotNull(portalID, "portalID");
        return this;
    }


    /**
     * The ID of the Suggestion.<br><br>A Suggestion ID is composed of a 2-4 letter prefix, followed by a
     * dash and 4-15 digits.
     */
    public GetSuggestionRequest withSuggestionID(@Nonnull String suggestionID) {
        this.suggestionID = Utils.checkNotNull(suggestionID, "suggestionID");
        return this;
    }


    /**
     * The attributes of a Suggestion to be returned *in addition to* the default list of attributes,
     * listed below. Multiple additional attributes can be specified using a comma-separated list. Passing
     * 'all' returns all attributes.
     * 
     * <p>#### Default Attributes
     * These Suggestion attributes are always returned:
     * 
     * <p>| Name | Description
     * | ---- | -----------
     * | id | The ID of the Suggestion.
     * | name  | The name of the Suggestion.
     * | status | The status of the Suggestion.
     * | description | The description of the Suggestion.
     * | language | Details about the language of the Suggestion.
     * | modifiedBy.id | The ID of the user that last modified the Suggestion.
     * | modifiedBy.firstName | The Suggestion's last modified user's first name.
     * | modifiedBy.middleName | The Suggestion's last modified user's middle name.
     * | modifiedBy.lastName | The Suggestion's last modified user's last name.
     * | modifiedDate | The Suggestion's last modified date &lt;u&gt;and&lt;/u&gt; information about the
     * user that last modified the Suggestion.
     * | link | The link object, used to retrieve the details of the Suggestion.
     * | hasComments | The Suggestion has one or more comments
     * | hasAttachments | The Suggestion has one or more attachments
     * | hasRelatedArticles | The Suggestion has related articles
     */
    public GetSuggestionRequest withSuggestionAdditionalAttributes(@Nullable List<SuggestionAdditionalAttributes> suggestionAdditionalAttributes) {
        this.suggestionAdditionalAttributes = suggestionAdditionalAttributes;
        return this;
    }


    public GetSuggestionRequest withCustomAdditionalAttributes(@Nullable String customAdditionalAttributes) {
        this.customAdditionalAttributes = customAdditionalAttributes;
        return this;
    }


    @Override
    public boolean equals(java.lang.Object o) {
        if (this == o) {
            return true;
        }
        if (o == null || getClass() != o.getClass()) {
            return false;
        }
        GetSuggestionRequest other = (GetSuggestionRequest) o;
        return 
            Utils.enhancedDeepEquals(this.acceptLanguage, other.acceptLanguage) &&
            Utils.enhancedDeepEquals(this.portalID, other.portalID) &&
            Utils.enhancedDeepEquals(this.suggestionID, other.suggestionID) &&
            Utils.enhancedDeepEquals(this.suggestionAdditionalAttributes, other.suggestionAdditionalAttributes) &&
            Utils.enhancedDeepEquals(this.customAdditionalAttributes, other.customAdditionalAttributes);
    }
    
    @Override
    public int hashCode() {
        return Utils.enhancedHash(
            acceptLanguage, portalID, suggestionID,
            suggestionAdditionalAttributes, customAdditionalAttributes);
    }
    
    @Override
    public String toString() {
        return Utils.toString(GetSuggestionRequest.class,
                "acceptLanguage", acceptLanguage,
                "portalID", portalID,
                "suggestionID", suggestionID,
                "suggestionAdditionalAttributes", suggestionAdditionalAttributes,
                "customAdditionalAttributes", customAdditionalAttributes);
    }

    @SuppressWarnings("UnusedReturnValue")
    public final static class Builder {

        private AcceptLanguage acceptLanguage;

        private String portalID;

        private String suggestionID;

        private List<SuggestionAdditionalAttributes> suggestionAdditionalAttributes;

        private String customAdditionalAttributes;

        private Builder() {
          // force use of static builder() method
        }

        /**
         * The Language locale accepted by the client (used for locale specific fields in resource
         * representation and in error responses).
         */
        public Builder acceptLanguage(@Nonnull AcceptLanguage acceptLanguage) {
            this.acceptLanguage = Utils.checkNotNull(acceptLanguage, "acceptLanguage");
            return this;
        }

        /**
         * The ID of the portal being accessed.<br><br>A portal ID is composed of a 2-4 letter prefix, followed
         * by a dash and 4-15 digits.
         */
        public Builder portalID(@Nonnull String portalID) {
            this.portalID = Utils.checkNotNull(portalID, "portalID");
            return this;
        }

        /**
         * The ID of the Suggestion.<br><br>A Suggestion ID is composed of a 2-4 letter prefix, followed by a
         * dash and 4-15 digits.
         */
        public Builder suggestionID(@Nonnull String suggestionID) {
            this.suggestionID = Utils.checkNotNull(suggestionID, "suggestionID");
            return this;
        }

        /**
         * The attributes of a Suggestion to be returned *in addition to* the default list of attributes,
         * listed below. Multiple additional attributes can be specified using a comma-separated list. Passing
         * 'all' returns all attributes.
         * 
         * <p>#### Default Attributes
         * These Suggestion attributes are always returned:
         * 
         * <p>| Name | Description
         * | ---- | -----------
         * | id | The ID of the Suggestion.
         * | name  | The name of the Suggestion.
         * | status | The status of the Suggestion.
         * | description | The description of the Suggestion.
         * | language | Details about the language of the Suggestion.
         * | modifiedBy.id | The ID of the user that last modified the Suggestion.
         * | modifiedBy.firstName | The Suggestion's last modified user's first name.
         * | modifiedBy.middleName | The Suggestion's last modified user's middle name.
         * | modifiedBy.lastName | The Suggestion's last modified user's last name.
         * | modifiedDate | The Suggestion's last modified date &lt;u&gt;and&lt;/u&gt; information about the
         * user that last modified the Suggestion.
         * | link | The link object, used to retrieve the details of the Suggestion.
         * | hasComments | The Suggestion has one or more comments
         * | hasAttachments | The Suggestion has one or more attachments
         * | hasRelatedArticles | The Suggestion has related articles
         */
        public Builder suggestionAdditionalAttributes(@Nullable List<SuggestionAdditionalAttributes> suggestionAdditionalAttributes) {
            this.suggestionAdditionalAttributes = suggestionAdditionalAttributes;
            return this;
        }

        public Builder customAdditionalAttributes(@Nullable String customAdditionalAttributes) {
            this.customAdditionalAttributes = customAdditionalAttributes;
            return this;
        }

        public GetSuggestionRequest build() {
            return new GetSuggestionRequest(
                acceptLanguage, portalID, suggestionID,
                suggestionAdditionalAttributes, customAdditionalAttributes);
        }

    }
}
