/* 
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */
package com.egain.sdk.models.operations;

import com.egain.sdk.models.components.AcceptLanguage;
import com.egain.sdk.utils.SpeakeasyMetadata;
import com.egain.sdk.utils.Utils;
import com.fasterxml.jackson.annotation.JsonCreator;
import jakarta.annotation.Nonnull;
import java.lang.Override;
import java.lang.String;
import java.util.Optional;


public class GetSuggestionCommentsRequest {
    /**
     * The Language locale accepted by the client (used for locale specific fields in resource
     * representation and in error responses).
     */
    @SpeakeasyMetadata("header:style=simple,explode=false,name=Accept-Language")
    private AcceptLanguage acceptLanguage;

    /**
     * The ID of the portal being accessed.<br><br>A portal ID is composed of a 2-4 letter prefix, followed
     * by a dash and 4-15 digits.
     */
    @SpeakeasyMetadata("pathParam:style=simple,explode=false,name=portalID")
    private String portalID;

    /**
     * The ID of the Suggestion.<br><br>A Suggestion ID is composed of a 2-4 letter prefix, followed by a
     * dash and 4-15 digits.
     */
    @SpeakeasyMetadata("pathParam:style=simple,explode=false,name=suggestionID")
    private String suggestionID;

    @JsonCreator
    public GetSuggestionCommentsRequest(
            @Nonnull AcceptLanguage acceptLanguage,
            @Nonnull String portalID,
            @Nonnull String suggestionID) {
        this.acceptLanguage = Optional.ofNullable(acceptLanguage)
            .orElseThrow(() -> new IllegalArgumentException("acceptLanguage cannot be null"));
        this.portalID = Optional.ofNullable(portalID)
            .orElseThrow(() -> new IllegalArgumentException("portalID cannot be null"));
        this.suggestionID = Optional.ofNullable(suggestionID)
            .orElseThrow(() -> new IllegalArgumentException("suggestionID cannot be null"));
    }

    /**
     * The Language locale accepted by the client (used for locale specific fields in resource
     * representation and in error responses).
     */
    public AcceptLanguage acceptLanguage() {
        return this.acceptLanguage;
    }

    /**
     * The ID of the portal being accessed.<br><br>A portal ID is composed of a 2-4 letter prefix, followed
     * by a dash and 4-15 digits.
     */
    public String portalID() {
        return this.portalID;
    }

    /**
     * The ID of the Suggestion.<br><br>A Suggestion ID is composed of a 2-4 letter prefix, followed by a
     * dash and 4-15 digits.
     */
    public String suggestionID() {
        return this.suggestionID;
    }

    public static Builder builder() {
        return new Builder();
    }


    /**
     * The Language locale accepted by the client (used for locale specific fields in resource
     * representation and in error responses).
     */
    public GetSuggestionCommentsRequest withAcceptLanguage(@Nonnull AcceptLanguage acceptLanguage) {
        this.acceptLanguage = Utils.checkNotNull(acceptLanguage, "acceptLanguage");
        return this;
    }


    /**
     * The ID of the portal being accessed.<br><br>A portal ID is composed of a 2-4 letter prefix, followed
     * by a dash and 4-15 digits.
     */
    public GetSuggestionCommentsRequest withPortalID(@Nonnull String portalID) {
        this.portalID = Utils.checkNotNull(portalID, "portalID");
        return this;
    }


    /**
     * The ID of the Suggestion.<br><br>A Suggestion ID is composed of a 2-4 letter prefix, followed by a
     * dash and 4-15 digits.
     */
    public GetSuggestionCommentsRequest withSuggestionID(@Nonnull String suggestionID) {
        this.suggestionID = Utils.checkNotNull(suggestionID, "suggestionID");
        return this;
    }


    @Override
    public boolean equals(java.lang.Object o) {
        if (this == o) {
            return true;
        }
        if (o == null || getClass() != o.getClass()) {
            return false;
        }
        GetSuggestionCommentsRequest other = (GetSuggestionCommentsRequest) o;
        return 
            Utils.enhancedDeepEquals(this.acceptLanguage, other.acceptLanguage) &&
            Utils.enhancedDeepEquals(this.portalID, other.portalID) &&
            Utils.enhancedDeepEquals(this.suggestionID, other.suggestionID);
    }
    
    @Override
    public int hashCode() {
        return Utils.enhancedHash(
            acceptLanguage, portalID, suggestionID);
    }
    
    @Override
    public String toString() {
        return Utils.toString(GetSuggestionCommentsRequest.class,
                "acceptLanguage", acceptLanguage,
                "portalID", portalID,
                "suggestionID", suggestionID);
    }

    @SuppressWarnings("UnusedReturnValue")
    public final static class Builder {

        private AcceptLanguage acceptLanguage;

        private String portalID;

        private String suggestionID;

        private Builder() {
          // force use of static builder() method
        }

        /**
         * The Language locale accepted by the client (used for locale specific fields in resource
         * representation and in error responses).
         */
        public Builder acceptLanguage(@Nonnull AcceptLanguage acceptLanguage) {
            this.acceptLanguage = Utils.checkNotNull(acceptLanguage, "acceptLanguage");
            return this;
        }

        /**
         * The ID of the portal being accessed.<br><br>A portal ID is composed of a 2-4 letter prefix, followed
         * by a dash and 4-15 digits.
         */
        public Builder portalID(@Nonnull String portalID) {
            this.portalID = Utils.checkNotNull(portalID, "portalID");
            return this;
        }

        /**
         * The ID of the Suggestion.<br><br>A Suggestion ID is composed of a 2-4 letter prefix, followed by a
         * dash and 4-15 digits.
         */
        public Builder suggestionID(@Nonnull String suggestionID) {
            this.suggestionID = Utils.checkNotNull(suggestionID, "suggestionID");
            return this;
        }

        public GetSuggestionCommentsRequest build() {
            return new GetSuggestionCommentsRequest(
                acceptLanguage, portalID, suggestionID);
        }

    }
}
