/* 
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */
package com.egain.sdk.models.operations;

import com.egain.sdk.models.components.AcceptLanguage;
import com.egain.sdk.models.components.MandatoryLanguageQueryParameter;
import com.egain.sdk.utils.SpeakeasyMetadata;
import com.egain.sdk.utils.Utils;
import com.fasterxml.jackson.annotation.JsonCreator;
import jakarta.annotation.Nonnull;
import java.lang.Override;
import java.lang.String;
import java.util.Optional;


public class GetTopicBreadcrumbForArticleRequest {
    /**
     * The Language locale accepted by the client (used for locale specific fields in resource
     * representation and in error responses).
     */
    @SpeakeasyMetadata("header:style=simple,explode=false,name=Accept-Language")
    private AcceptLanguage acceptLanguage;

    /**
     * The ID of the portal being accessed.<br><br>A portal ID is composed of a 2-4 letter prefix, followed
     * by a dash and 4-15 digits.
     */
    @SpeakeasyMetadata("pathParam:style=simple,explode=false,name=portalID")
    private String portalID;

    /**
     * The ID of the Article.<br><br>An Article ID is composed of a 2-4 letter prefix followed by a dash
     * and 4-15 digits.
     */
    @SpeakeasyMetadata("pathParam:style=simple,explode=false,name=articleID")
    private String articleID;

    /**
     * The language used for fetching the details of a resource. Resources available in different languages
     * may differ from each other.
     */
    @SpeakeasyMetadata("queryParam:style=form,explode=true,name=$lang")
    private MandatoryLanguageQueryParameter language;

    @JsonCreator
    public GetTopicBreadcrumbForArticleRequest(
            @Nonnull AcceptLanguage acceptLanguage,
            @Nonnull String portalID,
            @Nonnull String articleID,
            @Nonnull MandatoryLanguageQueryParameter language) {
        this.acceptLanguage = Optional.ofNullable(acceptLanguage)
            .orElseThrow(() -> new IllegalArgumentException("acceptLanguage cannot be null"));
        this.portalID = Optional.ofNullable(portalID)
            .orElseThrow(() -> new IllegalArgumentException("portalID cannot be null"));
        this.articleID = Optional.ofNullable(articleID)
            .orElseThrow(() -> new IllegalArgumentException("articleID cannot be null"));
        this.language = Optional.ofNullable(language)
            .orElseThrow(() -> new IllegalArgumentException("language cannot be null"));
    }

    /**
     * The Language locale accepted by the client (used for locale specific fields in resource
     * representation and in error responses).
     */
    public AcceptLanguage acceptLanguage() {
        return this.acceptLanguage;
    }

    /**
     * The ID of the portal being accessed.<br><br>A portal ID is composed of a 2-4 letter prefix, followed
     * by a dash and 4-15 digits.
     */
    public String portalID() {
        return this.portalID;
    }

    /**
     * The ID of the Article.<br><br>An Article ID is composed of a 2-4 letter prefix followed by a dash
     * and 4-15 digits.
     */
    public String articleID() {
        return this.articleID;
    }

    /**
     * The language used for fetching the details of a resource. Resources available in different languages
     * may differ from each other.
     */
    public MandatoryLanguageQueryParameter language() {
        return this.language;
    }

    public static Builder builder() {
        return new Builder();
    }


    /**
     * The Language locale accepted by the client (used for locale specific fields in resource
     * representation and in error responses).
     */
    public GetTopicBreadcrumbForArticleRequest withAcceptLanguage(@Nonnull AcceptLanguage acceptLanguage) {
        this.acceptLanguage = Utils.checkNotNull(acceptLanguage, "acceptLanguage");
        return this;
    }


    /**
     * The ID of the portal being accessed.<br><br>A portal ID is composed of a 2-4 letter prefix, followed
     * by a dash and 4-15 digits.
     */
    public GetTopicBreadcrumbForArticleRequest withPortalID(@Nonnull String portalID) {
        this.portalID = Utils.checkNotNull(portalID, "portalID");
        return this;
    }


    /**
     * The ID of the Article.<br><br>An Article ID is composed of a 2-4 letter prefix followed by a dash
     * and 4-15 digits.
     */
    public GetTopicBreadcrumbForArticleRequest withArticleID(@Nonnull String articleID) {
        this.articleID = Utils.checkNotNull(articleID, "articleID");
        return this;
    }


    /**
     * The language used for fetching the details of a resource. Resources available in different languages
     * may differ from each other.
     */
    public GetTopicBreadcrumbForArticleRequest withLanguage(@Nonnull MandatoryLanguageQueryParameter language) {
        this.language = Utils.checkNotNull(language, "language");
        return this;
    }


    @Override
    public boolean equals(java.lang.Object o) {
        if (this == o) {
            return true;
        }
        if (o == null || getClass() != o.getClass()) {
            return false;
        }
        GetTopicBreadcrumbForArticleRequest other = (GetTopicBreadcrumbForArticleRequest) o;
        return 
            Utils.enhancedDeepEquals(this.acceptLanguage, other.acceptLanguage) &&
            Utils.enhancedDeepEquals(this.portalID, other.portalID) &&
            Utils.enhancedDeepEquals(this.articleID, other.articleID) &&
            Utils.enhancedDeepEquals(this.language, other.language);
    }
    
    @Override
    public int hashCode() {
        return Utils.enhancedHash(
            acceptLanguage, portalID, articleID,
            language);
    }
    
    @Override
    public String toString() {
        return Utils.toString(GetTopicBreadcrumbForArticleRequest.class,
                "acceptLanguage", acceptLanguage,
                "portalID", portalID,
                "articleID", articleID,
                "language", language);
    }

    @SuppressWarnings("UnusedReturnValue")
    public final static class Builder {

        private AcceptLanguage acceptLanguage;

        private String portalID;

        private String articleID;

        private MandatoryLanguageQueryParameter language;

        private Builder() {
          // force use of static builder() method
        }

        /**
         * The Language locale accepted by the client (used for locale specific fields in resource
         * representation and in error responses).
         */
        public Builder acceptLanguage(@Nonnull AcceptLanguage acceptLanguage) {
            this.acceptLanguage = Utils.checkNotNull(acceptLanguage, "acceptLanguage");
            return this;
        }

        /**
         * The ID of the portal being accessed.<br><br>A portal ID is composed of a 2-4 letter prefix, followed
         * by a dash and 4-15 digits.
         */
        public Builder portalID(@Nonnull String portalID) {
            this.portalID = Utils.checkNotNull(portalID, "portalID");
            return this;
        }

        /**
         * The ID of the Article.<br><br>An Article ID is composed of a 2-4 letter prefix followed by a dash
         * and 4-15 digits.
         */
        public Builder articleID(@Nonnull String articleID) {
            this.articleID = Utils.checkNotNull(articleID, "articleID");
            return this;
        }

        /**
         * The language used for fetching the details of a resource. Resources available in different languages
         * may differ from each other.
         */
        public Builder language(@Nonnull MandatoryLanguageQueryParameter language) {
            this.language = Utils.checkNotNull(language, "language");
            return this;
        }

        public GetTopicBreadcrumbForArticleRequest build() {
            return new GetTopicBreadcrumbForArticleRequest(
                acceptLanguage, portalID, articleID,
                language);
        }

    }
}
