/* 
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */
package com.egain.sdk.models.operations;

import com.egain.sdk.utils.SpeakeasyMetadata;
import com.egain.sdk.utils.Utils;
import com.fasterxml.jackson.annotation.JsonCreator;
import java.lang.Override;
import java.lang.String;


public class GetValidationHookVersionRequest {
    /**
     * Integer ID of the Hook resource.
     */
    @SpeakeasyMetadata("pathParam:style=simple,explode=false,name=hookID")
    private long hookID;

    /**
     * The sequential version number of the hook (e.g., 1, 2, 3).
     */
    @SpeakeasyMetadata("pathParam:style=simple,explode=false,name=versionID")
    private long versionID;

    @JsonCreator
    public GetValidationHookVersionRequest(
            long hookID,
            long versionID) {
        this.hookID = hookID;
        this.versionID = versionID;
    }

    /**
     * Integer ID of the Hook resource.
     */
    public long hookID() {
        return this.hookID;
    }

    /**
     * The sequential version number of the hook (e.g., 1, 2, 3).
     */
    public long versionID() {
        return this.versionID;
    }

    public static Builder builder() {
        return new Builder();
    }


    /**
     * Integer ID of the Hook resource.
     */
    public GetValidationHookVersionRequest withHookID(long hookID) {
        this.hookID = hookID;
        return this;
    }


    /**
     * The sequential version number of the hook (e.g., 1, 2, 3).
     */
    public GetValidationHookVersionRequest withVersionID(long versionID) {
        this.versionID = versionID;
        return this;
    }


    @Override
    public boolean equals(java.lang.Object o) {
        if (this == o) {
            return true;
        }
        if (o == null || getClass() != o.getClass()) {
            return false;
        }
        GetValidationHookVersionRequest other = (GetValidationHookVersionRequest) o;
        return 
            Utils.enhancedDeepEquals(this.hookID, other.hookID) &&
            Utils.enhancedDeepEquals(this.versionID, other.versionID);
    }
    
    @Override
    public int hashCode() {
        return Utils.enhancedHash(
            hookID, versionID);
    }
    
    @Override
    public String toString() {
        return Utils.toString(GetValidationHookVersionRequest.class,
                "hookID", hookID,
                "versionID", versionID);
    }

    @SuppressWarnings("UnusedReturnValue")
    public final static class Builder {

        private long hookID;

        private long versionID;

        private Builder() {
          // force use of static builder() method
        }

        /**
         * Integer ID of the Hook resource.
         */
        public Builder hookID(long hookID) {
            this.hookID = hookID;
            return this;
        }

        /**
         * The sequential version number of the hook (e.g., 1, 2, 3).
         */
        public Builder versionID(long versionID) {
            this.versionID = versionID;
            return this;
        }

        public GetValidationHookVersionRequest build() {
            return new GetValidationHookVersionRequest(
                hookID, versionID);
        }

    }
}
