/* 
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */
package com.egain.sdk.models.operations;

import com.egain.sdk.models.components.RequiredLanguageCode;
import com.egain.sdk.models.components.RetrieveRequest;
import com.egain.sdk.utils.SpeakeasyMetadata;
import com.egain.sdk.utils.Utils;
import com.fasterxml.jackson.annotation.JsonCreator;
import jakarta.annotation.Nonnull;
import jakarta.annotation.Nullable;
import java.lang.Override;
import java.lang.String;
import java.util.List;
import java.util.Map;
import java.util.Optional;


public class RetrieveChunksRequest {
    /**
     * The search query string.
     */
    @SpeakeasyMetadata("queryParam:style=form,explode=true,name=q")
    private String q;

    /**
     * The ID of the portal being accessed.<br><br>A portal ID is composed of a 2-4 letter prefix, followed
     * by a dash and 4-15 digits.
     */
    @SpeakeasyMetadata("pathParam:style=simple,explode=false,name=portalID")
    private String portalID;


    @SpeakeasyMetadata("queryParam:style=form,explode=true,name=$filter[userProfileID]")
    private String filterUserProfileID;

    /**
     * The language that describes the details of a resource. Resources available in different languages
     * may differ from each other.
     */
    @SpeakeasyMetadata("queryParam:style=form,explode=true,name=$lang")
    private RequiredLanguageCode language;

    /**
     * An object where each key is a **Category Tag ID** (numeric string),
     * and each value is an array of **Tag IDs** for that category.
     * **Note**:
     * - The '$filter[tags]' query parameter JSON value should be url encoded.
     * - Some developer tools for invoking APIs may not url encode the '$filter[tags]' query parameter JSON
     * value by default. Ensure that only url encoded values are used.
     * - Example of JSON value: {"BASE-40845":["BASE-40849","BASE-40853"]}
     * - Example of URL encoded value: %7B%22BASE-40845%22%3A%5B%22BASE-40849%22%2C%22BASE-40853%22%5D%7D
     */
    @SpeakeasyMetadata("queryParam:style=form,explode=true,name=$filter[tags]")
    private Map<String, List<String>> filterTags;

    /**
     * An array of topic IDs. It is used to restrict search results to specific topics.
     */
    @SpeakeasyMetadata("queryParam:style=form,explode=true,name=$filter[topicIds]")
    private List<String> filterTopicIds;


    @SpeakeasyMetadata("request:mediaType=application/json")
    private RetrieveRequest body;

    @JsonCreator
    public RetrieveChunksRequest(
            @Nonnull String q,
            @Nonnull String portalID,
            @Nullable String filterUserProfileID,
            @Nonnull RequiredLanguageCode language,
            @Nullable Map<String, List<String>> filterTags,
            @Nullable List<String> filterTopicIds,
            @Nullable RetrieveRequest body) {
        this.q = Optional.ofNullable(q)
            .orElseThrow(() -> new IllegalArgumentException("q cannot be null"));
        this.portalID = Optional.ofNullable(portalID)
            .orElseThrow(() -> new IllegalArgumentException("portalID cannot be null"));
        this.filterUserProfileID = filterUserProfileID;
        this.language = Optional.ofNullable(language)
            .orElseThrow(() -> new IllegalArgumentException("language cannot be null"));
        this.filterTags = filterTags;
        this.filterTopicIds = filterTopicIds;
        this.body = body;
    }
    
    public RetrieveChunksRequest(
            @Nonnull String q,
            @Nonnull String portalID,
            @Nonnull RequiredLanguageCode language) {
        this(q, portalID, null,
            language, null, null,
            null);
    }

    /**
     * The search query string.
     */
    public String q() {
        return this.q;
    }

    /**
     * The ID of the portal being accessed.<br><br>A portal ID is composed of a 2-4 letter prefix, followed
     * by a dash and 4-15 digits.
     */
    public String portalID() {
        return this.portalID;
    }

    public Optional<String> filterUserProfileID() {
        return Optional.ofNullable(this.filterUserProfileID);
    }

    /**
     * The language that describes the details of a resource. Resources available in different languages
     * may differ from each other.
     */
    public RequiredLanguageCode language() {
        return this.language;
    }

    /**
     * An object where each key is a **Category Tag ID** (numeric string),
     * and each value is an array of **Tag IDs** for that category.
     * **Note**:
     * - The '$filter[tags]' query parameter JSON value should be url encoded.
     * - Some developer tools for invoking APIs may not url encode the '$filter[tags]' query parameter JSON
     * value by default. Ensure that only url encoded values are used.
     * - Example of JSON value: {"BASE-40845":["BASE-40849","BASE-40853"]}
     * - Example of URL encoded value: %7B%22BASE-40845%22%3A%5B%22BASE-40849%22%2C%22BASE-40853%22%5D%7D
     */
    public Optional<Map<String, List<String>>> filterTags() {
        return Optional.ofNullable(this.filterTags);
    }

    /**
     * An array of topic IDs. It is used to restrict search results to specific topics.
     */
    public Optional<List<String>> filterTopicIds() {
        return Optional.ofNullable(this.filterTopicIds);
    }

    public Optional<RetrieveRequest> body() {
        return Optional.ofNullable(this.body);
    }

    public static Builder builder() {
        return new Builder();
    }


    /**
     * The search query string.
     */
    public RetrieveChunksRequest withQ(@Nonnull String q) {
        this.q = Utils.checkNotNull(q, "q");
        return this;
    }


    /**
     * The ID of the portal being accessed.<br><br>A portal ID is composed of a 2-4 letter prefix, followed
     * by a dash and 4-15 digits.
     */
    public RetrieveChunksRequest withPortalID(@Nonnull String portalID) {
        this.portalID = Utils.checkNotNull(portalID, "portalID");
        return this;
    }


    public RetrieveChunksRequest withFilterUserProfileID(@Nullable String filterUserProfileID) {
        this.filterUserProfileID = filterUserProfileID;
        return this;
    }


    /**
     * The language that describes the details of a resource. Resources available in different languages
     * may differ from each other.
     */
    public RetrieveChunksRequest withLanguage(@Nonnull RequiredLanguageCode language) {
        this.language = Utils.checkNotNull(language, "language");
        return this;
    }


    /**
     * An object where each key is a **Category Tag ID** (numeric string),
     * and each value is an array of **Tag IDs** for that category.
     * **Note**:
     * - The '$filter[tags]' query parameter JSON value should be url encoded.
     * - Some developer tools for invoking APIs may not url encode the '$filter[tags]' query parameter JSON
     * value by default. Ensure that only url encoded values are used.
     * - Example of JSON value: {"BASE-40845":["BASE-40849","BASE-40853"]}
     * - Example of URL encoded value: %7B%22BASE-40845%22%3A%5B%22BASE-40849%22%2C%22BASE-40853%22%5D%7D
     */
    public RetrieveChunksRequest withFilterTags(@Nullable Map<String, List<String>> filterTags) {
        this.filterTags = filterTags;
        return this;
    }


    /**
     * An array of topic IDs. It is used to restrict search results to specific topics.
     */
    public RetrieveChunksRequest withFilterTopicIds(@Nullable List<String> filterTopicIds) {
        this.filterTopicIds = filterTopicIds;
        return this;
    }


    public RetrieveChunksRequest withBody(@Nullable RetrieveRequest body) {
        this.body = body;
        return this;
    }


    @Override
    public boolean equals(java.lang.Object o) {
        if (this == o) {
            return true;
        }
        if (o == null || getClass() != o.getClass()) {
            return false;
        }
        RetrieveChunksRequest other = (RetrieveChunksRequest) o;
        return 
            Utils.enhancedDeepEquals(this.q, other.q) &&
            Utils.enhancedDeepEquals(this.portalID, other.portalID) &&
            Utils.enhancedDeepEquals(this.filterUserProfileID, other.filterUserProfileID) &&
            Utils.enhancedDeepEquals(this.language, other.language) &&
            Utils.enhancedDeepEquals(this.filterTags, other.filterTags) &&
            Utils.enhancedDeepEquals(this.filterTopicIds, other.filterTopicIds) &&
            Utils.enhancedDeepEquals(this.body, other.body);
    }
    
    @Override
    public int hashCode() {
        return Utils.enhancedHash(
            q, portalID, filterUserProfileID,
            language, filterTags, filterTopicIds,
            body);
    }
    
    @Override
    public String toString() {
        return Utils.toString(RetrieveChunksRequest.class,
                "q", q,
                "portalID", portalID,
                "filterUserProfileID", filterUserProfileID,
                "language", language,
                "filterTags", filterTags,
                "filterTopicIds", filterTopicIds,
                "body", body);
    }

    @SuppressWarnings("UnusedReturnValue")
    public final static class Builder {

        private String q;

        private String portalID;

        private String filterUserProfileID;

        private RequiredLanguageCode language;

        private Map<String, List<String>> filterTags;

        private List<String> filterTopicIds;

        private RetrieveRequest body;

        private Builder() {
          // force use of static builder() method
        }

        /**
         * The search query string.
         */
        public Builder q(@Nonnull String q) {
            this.q = Utils.checkNotNull(q, "q");
            return this;
        }

        /**
         * The ID of the portal being accessed.<br><br>A portal ID is composed of a 2-4 letter prefix, followed
         * by a dash and 4-15 digits.
         */
        public Builder portalID(@Nonnull String portalID) {
            this.portalID = Utils.checkNotNull(portalID, "portalID");
            return this;
        }

        public Builder filterUserProfileID(@Nullable String filterUserProfileID) {
            this.filterUserProfileID = filterUserProfileID;
            return this;
        }

        /**
         * The language that describes the details of a resource. Resources available in different languages
         * may differ from each other.
         */
        public Builder language(@Nonnull RequiredLanguageCode language) {
            this.language = Utils.checkNotNull(language, "language");
            return this;
        }

        /**
         * An object where each key is a **Category Tag ID** (numeric string),
         * and each value is an array of **Tag IDs** for that category.
         * **Note**:
         * - The '$filter[tags]' query parameter JSON value should be url encoded.
         * - Some developer tools for invoking APIs may not url encode the '$filter[tags]' query parameter JSON
         * value by default. Ensure that only url encoded values are used.
         * - Example of JSON value: {"BASE-40845":["BASE-40849","BASE-40853"]}
         * - Example of URL encoded value: %7B%22BASE-40845%22%3A%5B%22BASE-40849%22%2C%22BASE-40853%22%5D%7D
         */
        public Builder filterTags(@Nullable Map<String, List<String>> filterTags) {
            this.filterTags = filterTags;
            return this;
        }

        /**
         * An array of topic IDs. It is used to restrict search results to specific topics.
         */
        public Builder filterTopicIds(@Nullable List<String> filterTopicIds) {
            this.filterTopicIds = filterTopicIds;
            return this;
        }

        public Builder body(@Nullable RetrieveRequest body) {
            this.body = body;
            return this;
        }

        public RetrieveChunksRequest build() {
            return new RetrieveChunksRequest(
                q, portalID, filterUserProfileID,
                language, filterTags, filterTopicIds,
                body);
        }

    }
}
