/* 
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */
package com.egain.sdk.models.operations;

import com.egain.sdk.models.components.AcceptLanguage;
import com.egain.sdk.models.components.OptionalArticleAttributes;
import com.egain.sdk.utils.LazySingletonValue;
import com.egain.sdk.utils.SpeakeasyMetadata;
import com.egain.sdk.utils.Utils;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.core.type.TypeReference;
import jakarta.annotation.Nonnull;
import jakarta.annotation.Nullable;
import java.lang.Integer;
import java.lang.Long;
import java.lang.Override;
import java.lang.String;
import java.util.Optional;


public class SearchPriorToEscalationRequest {
    /**
     * The Language locale accepted by the client (used for locale specific fields in resource
     * representation and in error responses).
     */
    @SpeakeasyMetadata("header:style=simple,explode=false,name=Accept-Language")
    private AcceptLanguage acceptLanguage;

    /**
     * The ID of the portal being accessed.<br><br>A portal ID is composed of a 2-4 letter prefix, followed
     * by a dash and 4-15 digits.
     */
    @SpeakeasyMetadata("pathParam:style=simple,explode=false,name=portalID")
    private String portalID;

    /**
     * The ID (uuid) of the customer escalation.
     */
    @SpeakeasyMetadata("pathParam:style=simple,explode=false,name=escalationId")
    private String escalationId;

    /**
     * This parameter will restrict the search scope to the provided topic and it's sub topic.
     */
    @SpeakeasyMetadata("queryParam:style=form,explode=true,name=filter[articles-in-topic-tree]")
    private String filterArticlesInTopicTree;

    /**
     * The fields of the article to be returned.
     */
    @SpeakeasyMetadata("queryParam:style=form,explode=true,name=additionalAttributes")
    private OptionalArticleAttributes additionalAttributes;

    /**
     * The "maxResults" parameter specifies the number of articles that should be included in the response.
     * 
     * <p>It is only required when the escalation type is chat escalation.If not specified then default value
     * 5 will be considered for chat escalation.
     * 
     * <p>If the escalation type is email, the maximum results value specified in the portal settings for
     * email escalation will be taken into consideration.
     */
    @SpeakeasyMetadata("queryParam:style=form,explode=true,name=maxResults")
    private Integer maxResults;

    /**
     * Pagination parameter that specifies the page number of results to be returned. Used in conjunction
     * with $pagesize.
     */
    @SpeakeasyMetadata("queryParam:style=form,explode=true,name=$pagenum")
    private Long pagenum;

    /**
     * Pagination parameter that specifies the number of results per page. Used in conjunction with
     * $pagenum.<br>Valid range of 5-75<br>_Default value_: 25
     */
    @SpeakeasyMetadata("queryParam:style=form,explode=true,name=$pagesize")
    private Long pagesize;

    @JsonCreator
    public SearchPriorToEscalationRequest(
            @Nonnull AcceptLanguage acceptLanguage,
            @Nonnull String portalID,
            @Nonnull String escalationId,
            @Nullable String filterArticlesInTopicTree,
            @Nullable OptionalArticleAttributes additionalAttributes,
            @Nullable Integer maxResults,
            @Nullable Long pagenum,
            @Nullable Long pagesize) {
        this.acceptLanguage = Optional.ofNullable(acceptLanguage)
            .orElseThrow(() -> new IllegalArgumentException("acceptLanguage cannot be null"));
        this.portalID = Optional.ofNullable(portalID)
            .orElseThrow(() -> new IllegalArgumentException("portalID cannot be null"));
        this.escalationId = Optional.ofNullable(escalationId)
            .orElseThrow(() -> new IllegalArgumentException("escalationId cannot be null"));
        this.filterArticlesInTopicTree = filterArticlesInTopicTree;
        this.additionalAttributes = additionalAttributes;
        this.maxResults = maxResults;
        this.pagenum = Optional.ofNullable(pagenum)
            .orElse(Builder._SINGLETON_VALUE_Pagenum.value());
        this.pagesize = Optional.ofNullable(pagesize)
            .orElse(Builder._SINGLETON_VALUE_Pagesize.value());
    }
    
    public SearchPriorToEscalationRequest(
            @Nonnull AcceptLanguage acceptLanguage,
            @Nonnull String portalID,
            @Nonnull String escalationId) {
        this(acceptLanguage, portalID, escalationId,
            null, null, null,
            null, null);
    }

    /**
     * The Language locale accepted by the client (used for locale specific fields in resource
     * representation and in error responses).
     */
    public AcceptLanguage acceptLanguage() {
        return this.acceptLanguage;
    }

    /**
     * The ID of the portal being accessed.<br><br>A portal ID is composed of a 2-4 letter prefix, followed
     * by a dash and 4-15 digits.
     */
    public String portalID() {
        return this.portalID;
    }

    /**
     * The ID (uuid) of the customer escalation.
     */
    public String escalationId() {
        return this.escalationId;
    }

    /**
     * This parameter will restrict the search scope to the provided topic and it's sub topic.
     */
    public Optional<String> filterArticlesInTopicTree() {
        return Optional.ofNullable(this.filterArticlesInTopicTree);
    }

    /**
     * The fields of the article to be returned.
     */
    public Optional<OptionalArticleAttributes> additionalAttributes() {
        return Optional.ofNullable(this.additionalAttributes);
    }

    /**
     * The "maxResults" parameter specifies the number of articles that should be included in the response.
     * 
     * <p>It is only required when the escalation type is chat escalation.If not specified then default value
     * 5 will be considered for chat escalation.
     * 
     * <p>If the escalation type is email, the maximum results value specified in the portal settings for
     * email escalation will be taken into consideration.
     */
    public Optional<Integer> maxResults() {
        return Optional.ofNullable(this.maxResults);
    }

    /**
     * Pagination parameter that specifies the page number of results to be returned. Used in conjunction
     * with $pagesize.
     */
    public Optional<Long> pagenum() {
        return Optional.ofNullable(this.pagenum);
    }

    /**
     * Pagination parameter that specifies the number of results per page. Used in conjunction with
     * $pagenum.<br>Valid range of 5-75<br>_Default value_: 25
     */
    public Optional<Long> pagesize() {
        return Optional.ofNullable(this.pagesize);
    }

    public static Builder builder() {
        return new Builder();
    }


    /**
     * The Language locale accepted by the client (used for locale specific fields in resource
     * representation and in error responses).
     */
    public SearchPriorToEscalationRequest withAcceptLanguage(@Nonnull AcceptLanguage acceptLanguage) {
        this.acceptLanguage = Utils.checkNotNull(acceptLanguage, "acceptLanguage");
        return this;
    }


    /**
     * The ID of the portal being accessed.<br><br>A portal ID is composed of a 2-4 letter prefix, followed
     * by a dash and 4-15 digits.
     */
    public SearchPriorToEscalationRequest withPortalID(@Nonnull String portalID) {
        this.portalID = Utils.checkNotNull(portalID, "portalID");
        return this;
    }


    /**
     * The ID (uuid) of the customer escalation.
     */
    public SearchPriorToEscalationRequest withEscalationId(@Nonnull String escalationId) {
        this.escalationId = Utils.checkNotNull(escalationId, "escalationId");
        return this;
    }


    /**
     * This parameter will restrict the search scope to the provided topic and it's sub topic.
     */
    public SearchPriorToEscalationRequest withFilterArticlesInTopicTree(@Nullable String filterArticlesInTopicTree) {
        this.filterArticlesInTopicTree = filterArticlesInTopicTree;
        return this;
    }


    /**
     * The fields of the article to be returned.
     */
    public SearchPriorToEscalationRequest withAdditionalAttributes(@Nullable OptionalArticleAttributes additionalAttributes) {
        this.additionalAttributes = additionalAttributes;
        return this;
    }


    /**
     * The "maxResults" parameter specifies the number of articles that should be included in the response.
     * 
     * <p>It is only required when the escalation type is chat escalation.If not specified then default value
     * 5 will be considered for chat escalation.
     * 
     * <p>If the escalation type is email, the maximum results value specified in the portal settings for
     * email escalation will be taken into consideration.
     */
    public SearchPriorToEscalationRequest withMaxResults(@Nullable Integer maxResults) {
        this.maxResults = maxResults;
        return this;
    }


    /**
     * Pagination parameter that specifies the page number of results to be returned. Used in conjunction
     * with $pagesize.
     */
    public SearchPriorToEscalationRequest withPagenum(@Nullable Long pagenum) {
        this.pagenum = pagenum;
        return this;
    }


    /**
     * Pagination parameter that specifies the number of results per page. Used in conjunction with
     * $pagenum.<br>Valid range of 5-75<br>_Default value_: 25
     */
    public SearchPriorToEscalationRequest withPagesize(@Nullable Long pagesize) {
        this.pagesize = pagesize;
        return this;
    }


    @Override
    public boolean equals(java.lang.Object o) {
        if (this == o) {
            return true;
        }
        if (o == null || getClass() != o.getClass()) {
            return false;
        }
        SearchPriorToEscalationRequest other = (SearchPriorToEscalationRequest) o;
        return 
            Utils.enhancedDeepEquals(this.acceptLanguage, other.acceptLanguage) &&
            Utils.enhancedDeepEquals(this.portalID, other.portalID) &&
            Utils.enhancedDeepEquals(this.escalationId, other.escalationId) &&
            Utils.enhancedDeepEquals(this.filterArticlesInTopicTree, other.filterArticlesInTopicTree) &&
            Utils.enhancedDeepEquals(this.additionalAttributes, other.additionalAttributes) &&
            Utils.enhancedDeepEquals(this.maxResults, other.maxResults) &&
            Utils.enhancedDeepEquals(this.pagenum, other.pagenum) &&
            Utils.enhancedDeepEquals(this.pagesize, other.pagesize);
    }
    
    @Override
    public int hashCode() {
        return Utils.enhancedHash(
            acceptLanguage, portalID, escalationId,
            filterArticlesInTopicTree, additionalAttributes, maxResults,
            pagenum, pagesize);
    }
    
    @Override
    public String toString() {
        return Utils.toString(SearchPriorToEscalationRequest.class,
                "acceptLanguage", acceptLanguage,
                "portalID", portalID,
                "escalationId", escalationId,
                "filterArticlesInTopicTree", filterArticlesInTopicTree,
                "additionalAttributes", additionalAttributes,
                "maxResults", maxResults,
                "pagenum", pagenum,
                "pagesize", pagesize);
    }

    @SuppressWarnings("UnusedReturnValue")
    public final static class Builder {

        private AcceptLanguage acceptLanguage;

        private String portalID;

        private String escalationId;

        private String filterArticlesInTopicTree;

        private OptionalArticleAttributes additionalAttributes;

        private Integer maxResults;

        private Long pagenum;

        private Long pagesize;

        private Builder() {
          // force use of static builder() method
        }

        /**
         * The Language locale accepted by the client (used for locale specific fields in resource
         * representation and in error responses).
         */
        public Builder acceptLanguage(@Nonnull AcceptLanguage acceptLanguage) {
            this.acceptLanguage = Utils.checkNotNull(acceptLanguage, "acceptLanguage");
            return this;
        }

        /**
         * The ID of the portal being accessed.<br><br>A portal ID is composed of a 2-4 letter prefix, followed
         * by a dash and 4-15 digits.
         */
        public Builder portalID(@Nonnull String portalID) {
            this.portalID = Utils.checkNotNull(portalID, "portalID");
            return this;
        }

        /**
         * The ID (uuid) of the customer escalation.
         */
        public Builder escalationId(@Nonnull String escalationId) {
            this.escalationId = Utils.checkNotNull(escalationId, "escalationId");
            return this;
        }

        /**
         * This parameter will restrict the search scope to the provided topic and it's sub topic.
         */
        public Builder filterArticlesInTopicTree(@Nullable String filterArticlesInTopicTree) {
            this.filterArticlesInTopicTree = filterArticlesInTopicTree;
            return this;
        }

        /**
         * The fields of the article to be returned.
         */
        public Builder additionalAttributes(@Nullable OptionalArticleAttributes additionalAttributes) {
            this.additionalAttributes = additionalAttributes;
            return this;
        }

        /**
         * The "maxResults" parameter specifies the number of articles that should be included in the response.
         * 
         * <p>It is only required when the escalation type is chat escalation.If not specified then default value
         * 5 will be considered for chat escalation.
         * 
         * <p>If the escalation type is email, the maximum results value specified in the portal settings for
         * email escalation will be taken into consideration.
         */
        public Builder maxResults(@Nullable Integer maxResults) {
            this.maxResults = maxResults;
            return this;
        }

        /**
         * Pagination parameter that specifies the page number of results to be returned. Used in conjunction
         * with $pagesize.
         */
        public Builder pagenum(@Nullable Long pagenum) {
            this.pagenum = pagenum;
            return this;
        }

        /**
         * Pagination parameter that specifies the number of results per page. Used in conjunction with
         * $pagenum.<br>Valid range of 5-75<br>_Default value_: 25
         */
        public Builder pagesize(@Nullable Long pagesize) {
            this.pagesize = pagesize;
            return this;
        }

        public SearchPriorToEscalationRequest build() {
            return new SearchPriorToEscalationRequest(
                acceptLanguage, portalID, escalationId,
                filterArticlesInTopicTree, additionalAttributes, maxResults,
                pagenum, pagesize);
        }


        private static final LazySingletonValue<Long> _SINGLETON_VALUE_Pagenum =
                new LazySingletonValue<>(
                        "pagenum",
                        "1",
                        new TypeReference<Long>() {});

        private static final LazySingletonValue<Long> _SINGLETON_VALUE_Pagesize =
                new LazySingletonValue<>(
                        "pagesize",
                        "25",
                        new TypeReference<Long>() {});
    }
}
