/* 
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */
package com.egain.sdk.models.operations;

import com.egain.sdk.models.components.AcceptLanguage;
import com.egain.sdk.models.components.GHSearchRequest;
import com.egain.sdk.models.components.LanguageQueryParameter;
import com.egain.sdk.utils.SpeakeasyMetadata;
import com.egain.sdk.utils.Utils;
import com.fasterxml.jackson.annotation.JsonCreator;
import jakarta.annotation.Nonnull;
import jakarta.annotation.Nullable;
import java.lang.Override;
import java.lang.String;
import java.util.Optional;


public class StartGHSearchRequest {
    /**
     * The Language locale accepted by the client (used for locale specific fields in resource
     * representation and in error responses).
     */
    @SpeakeasyMetadata("header:style=simple,explode=false,name=Accept-Language")
    private AcceptLanguage acceptLanguage;

    /**
     * The ID of the portal being accessed.<br><br>A portal ID is composed of a 2-4 letter prefix, followed
     * by a dash and 4-15 digits.
     */
    @SpeakeasyMetadata("pathParam:style=simple,explode=false,name=portalID")
    private String portalID;

    /**
     * The language that describes the details of a resource. Resources available in different languages
     * may differ from each other.<li>If <code>lang</code> is not passed, then the portal's default
     * language is used.&lt;/li&gt;
     */
    @SpeakeasyMetadata("queryParam:style=form,explode=true,name=$lang")
    private LanguageQueryParameter language;


    @SpeakeasyMetadata("queryParam:style=form,explode=true,name=ghCustomAdditionalAttributes")
    private String ghCustomAdditionalAttributes;


    @SpeakeasyMetadata("request:mediaType=application/json")
    private GHSearchRequest body;

    @JsonCreator
    public StartGHSearchRequest(
            @Nonnull AcceptLanguage acceptLanguage,
            @Nonnull String portalID,
            @Nullable LanguageQueryParameter language,
            @Nullable String ghCustomAdditionalAttributes,
            @Nonnull GHSearchRequest body) {
        this.acceptLanguage = Optional.ofNullable(acceptLanguage)
            .orElseThrow(() -> new IllegalArgumentException("acceptLanguage cannot be null"));
        this.portalID = Optional.ofNullable(portalID)
            .orElseThrow(() -> new IllegalArgumentException("portalID cannot be null"));
        this.language = language;
        this.ghCustomAdditionalAttributes = ghCustomAdditionalAttributes;
        this.body = Optional.ofNullable(body)
            .orElseThrow(() -> new IllegalArgumentException("body cannot be null"));
    }
    
    public StartGHSearchRequest(
            @Nonnull AcceptLanguage acceptLanguage,
            @Nonnull String portalID,
            @Nonnull GHSearchRequest body) {
        this(acceptLanguage, portalID, null,
            null, body);
    }

    /**
     * The Language locale accepted by the client (used for locale specific fields in resource
     * representation and in error responses).
     */
    public AcceptLanguage acceptLanguage() {
        return this.acceptLanguage;
    }

    /**
     * The ID of the portal being accessed.<br><br>A portal ID is composed of a 2-4 letter prefix, followed
     * by a dash and 4-15 digits.
     */
    public String portalID() {
        return this.portalID;
    }

    /**
     * The language that describes the details of a resource. Resources available in different languages
     * may differ from each other.<li>If <code>lang</code> is not passed, then the portal's default
     * language is used.&lt;/li&gt;
     */
    public Optional<LanguageQueryParameter> language() {
        return Optional.ofNullable(this.language);
    }

    public Optional<String> ghCustomAdditionalAttributes() {
        return Optional.ofNullable(this.ghCustomAdditionalAttributes);
    }

    public GHSearchRequest body() {
        return this.body;
    }

    public static Builder builder() {
        return new Builder();
    }


    /**
     * The Language locale accepted by the client (used for locale specific fields in resource
     * representation and in error responses).
     */
    public StartGHSearchRequest withAcceptLanguage(@Nonnull AcceptLanguage acceptLanguage) {
        this.acceptLanguage = Utils.checkNotNull(acceptLanguage, "acceptLanguage");
        return this;
    }


    /**
     * The ID of the portal being accessed.<br><br>A portal ID is composed of a 2-4 letter prefix, followed
     * by a dash and 4-15 digits.
     */
    public StartGHSearchRequest withPortalID(@Nonnull String portalID) {
        this.portalID = Utils.checkNotNull(portalID, "portalID");
        return this;
    }


    /**
     * The language that describes the details of a resource. Resources available in different languages
     * may differ from each other.<li>If <code>lang</code> is not passed, then the portal's default
     * language is used.&lt;/li&gt;
     */
    public StartGHSearchRequest withLanguage(@Nullable LanguageQueryParameter language) {
        this.language = language;
        return this;
    }


    public StartGHSearchRequest withGhCustomAdditionalAttributes(@Nullable String ghCustomAdditionalAttributes) {
        this.ghCustomAdditionalAttributes = ghCustomAdditionalAttributes;
        return this;
    }


    public StartGHSearchRequest withBody(@Nonnull GHSearchRequest body) {
        this.body = Utils.checkNotNull(body, "body");
        return this;
    }


    @Override
    public boolean equals(java.lang.Object o) {
        if (this == o) {
            return true;
        }
        if (o == null || getClass() != o.getClass()) {
            return false;
        }
        StartGHSearchRequest other = (StartGHSearchRequest) o;
        return 
            Utils.enhancedDeepEquals(this.acceptLanguage, other.acceptLanguage) &&
            Utils.enhancedDeepEquals(this.portalID, other.portalID) &&
            Utils.enhancedDeepEquals(this.language, other.language) &&
            Utils.enhancedDeepEquals(this.ghCustomAdditionalAttributes, other.ghCustomAdditionalAttributes) &&
            Utils.enhancedDeepEquals(this.body, other.body);
    }
    
    @Override
    public int hashCode() {
        return Utils.enhancedHash(
            acceptLanguage, portalID, language,
            ghCustomAdditionalAttributes, body);
    }
    
    @Override
    public String toString() {
        return Utils.toString(StartGHSearchRequest.class,
                "acceptLanguage", acceptLanguage,
                "portalID", portalID,
                "language", language,
                "ghCustomAdditionalAttributes", ghCustomAdditionalAttributes,
                "body", body);
    }

    @SuppressWarnings("UnusedReturnValue")
    public final static class Builder {

        private AcceptLanguage acceptLanguage;

        private String portalID;

        private LanguageQueryParameter language;

        private String ghCustomAdditionalAttributes;

        private GHSearchRequest body;

        private Builder() {
          // force use of static builder() method
        }

        /**
         * The Language locale accepted by the client (used for locale specific fields in resource
         * representation and in error responses).
         */
        public Builder acceptLanguage(@Nonnull AcceptLanguage acceptLanguage) {
            this.acceptLanguage = Utils.checkNotNull(acceptLanguage, "acceptLanguage");
            return this;
        }

        /**
         * The ID of the portal being accessed.<br><br>A portal ID is composed of a 2-4 letter prefix, followed
         * by a dash and 4-15 digits.
         */
        public Builder portalID(@Nonnull String portalID) {
            this.portalID = Utils.checkNotNull(portalID, "portalID");
            return this;
        }

        /**
         * The language that describes the details of a resource. Resources available in different languages
         * may differ from each other.<li>If <code>lang</code> is not passed, then the portal's default
         * language is used.&lt;/li&gt;
         */
        public Builder language(@Nullable LanguageQueryParameter language) {
            this.language = language;
            return this;
        }

        public Builder ghCustomAdditionalAttributes(@Nullable String ghCustomAdditionalAttributes) {
            this.ghCustomAdditionalAttributes = ghCustomAdditionalAttributes;
            return this;
        }

        public Builder body(@Nonnull GHSearchRequest body) {
            this.body = Utils.checkNotNull(body, "body");
            return this;
        }

        public StartGHSearchRequest build() {
            return new StartGHSearchRequest(
                acceptLanguage, portalID, language,
                ghCustomAdditionalAttributes, body);
        }

    }
}
